-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pov_eta_wr is
generic (
    C_M_AXI_VOX_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_VOX_ID_WIDTH : INTEGER := 1;
    C_M_AXI_VOX_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_VOX_DATA_WIDTH : INTEGER := 64;
    C_M_AXI_VOX_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_VOX_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_VOX_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_VOX_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_OUT_R_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_OUT_R_ID_WIDTH : INTEGER := 1;
    C_M_AXI_OUT_R_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_OUT_R_DATA_WIDTH : INTEGER := 64;
    C_M_AXI_OUT_R_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_OUT_R_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_OUT_R_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_OUT_R_BUSER_WIDTH : INTEGER := 1;
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 7;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_OUT_R_USER_VALUE : INTEGER := 0;
    C_M_AXI_OUT_R_PROT_VALUE : INTEGER := 0;
    C_M_AXI_OUT_R_CACHE_VALUE : INTEGER := 3;
    C_M_AXI_VOX_USER_VALUE : INTEGER := 0;
    C_M_AXI_VOX_PROT_VALUE : INTEGER := 0;
    C_M_AXI_VOX_CACHE_VALUE : INTEGER := 3 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_vox_AWVALID : OUT STD_LOGIC;
    m_axi_vox_AWREADY : IN STD_LOGIC;
    m_axi_vox_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_VOX_ADDR_WIDTH-1 downto 0);
    m_axi_vox_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_VOX_ID_WIDTH-1 downto 0);
    m_axi_vox_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_vox_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_vox_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_vox_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_vox_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_vox_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_vox_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_vox_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_vox_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_VOX_AWUSER_WIDTH-1 downto 0);
    m_axi_vox_WVALID : OUT STD_LOGIC;
    m_axi_vox_WREADY : IN STD_LOGIC;
    m_axi_vox_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_VOX_DATA_WIDTH-1 downto 0);
    m_axi_vox_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_VOX_DATA_WIDTH/8-1 downto 0);
    m_axi_vox_WLAST : OUT STD_LOGIC;
    m_axi_vox_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_VOX_ID_WIDTH-1 downto 0);
    m_axi_vox_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_VOX_WUSER_WIDTH-1 downto 0);
    m_axi_vox_ARVALID : OUT STD_LOGIC;
    m_axi_vox_ARREADY : IN STD_LOGIC;
    m_axi_vox_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_VOX_ADDR_WIDTH-1 downto 0);
    m_axi_vox_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_VOX_ID_WIDTH-1 downto 0);
    m_axi_vox_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_vox_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_vox_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_vox_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_vox_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_vox_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_vox_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_vox_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_vox_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_VOX_ARUSER_WIDTH-1 downto 0);
    m_axi_vox_RVALID : IN STD_LOGIC;
    m_axi_vox_RREADY : OUT STD_LOGIC;
    m_axi_vox_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_VOX_DATA_WIDTH-1 downto 0);
    m_axi_vox_RLAST : IN STD_LOGIC;
    m_axi_vox_RID : IN STD_LOGIC_VECTOR (C_M_AXI_VOX_ID_WIDTH-1 downto 0);
    m_axi_vox_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_VOX_RUSER_WIDTH-1 downto 0);
    m_axi_vox_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_vox_BVALID : IN STD_LOGIC;
    m_axi_vox_BREADY : OUT STD_LOGIC;
    m_axi_vox_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_vox_BID : IN STD_LOGIC_VECTOR (C_M_AXI_VOX_ID_WIDTH-1 downto 0);
    m_axi_vox_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_VOX_BUSER_WIDTH-1 downto 0);
    m_axi_out_r_AWVALID : OUT STD_LOGIC;
    m_axi_out_r_AWREADY : IN STD_LOGIC;
    m_axi_out_r_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_R_ADDR_WIDTH-1 downto 0);
    m_axi_out_r_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_R_ID_WIDTH-1 downto 0);
    m_axi_out_r_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_out_r_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_out_r_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_r_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_r_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_r_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_out_r_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_r_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_r_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_R_AWUSER_WIDTH-1 downto 0);
    m_axi_out_r_WVALID : OUT STD_LOGIC;
    m_axi_out_r_WREADY : IN STD_LOGIC;
    m_axi_out_r_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_R_DATA_WIDTH-1 downto 0);
    m_axi_out_r_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_R_DATA_WIDTH/8-1 downto 0);
    m_axi_out_r_WLAST : OUT STD_LOGIC;
    m_axi_out_r_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_R_ID_WIDTH-1 downto 0);
    m_axi_out_r_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_R_WUSER_WIDTH-1 downto 0);
    m_axi_out_r_ARVALID : OUT STD_LOGIC;
    m_axi_out_r_ARREADY : IN STD_LOGIC;
    m_axi_out_r_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_R_ADDR_WIDTH-1 downto 0);
    m_axi_out_r_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_R_ID_WIDTH-1 downto 0);
    m_axi_out_r_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_out_r_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_out_r_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_r_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_r_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_r_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_out_r_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_r_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_r_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_R_ARUSER_WIDTH-1 downto 0);
    m_axi_out_r_RVALID : IN STD_LOGIC;
    m_axi_out_r_RREADY : OUT STD_LOGIC;
    m_axi_out_r_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_OUT_R_DATA_WIDTH-1 downto 0);
    m_axi_out_r_RLAST : IN STD_LOGIC;
    m_axi_out_r_RID : IN STD_LOGIC_VECTOR (C_M_AXI_OUT_R_ID_WIDTH-1 downto 0);
    m_axi_out_r_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_OUT_R_RUSER_WIDTH-1 downto 0);
    m_axi_out_r_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_r_BVALID : IN STD_LOGIC;
    m_axi_out_r_BREADY : OUT STD_LOGIC;
    m_axi_out_r_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_r_BID : IN STD_LOGIC_VECTOR (C_M_AXI_OUT_R_ID_WIDTH-1 downto 0);
    m_axi_out_r_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_OUT_R_BUSER_WIDTH-1 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of pov_eta_wr is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "pov_eta_wr_pov_eta_wr,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-2,HLS_INPUT_CLOCK=6.670000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.869100,HLS_SYN_LAT=3908808,HLS_SYN_TPT=none,HLS_SYN_MEM=10,HLS_SYN_DSP=0,HLS_SYN_FF=6018,HLS_SYN_LUT=5794,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant C_M_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv45_0 : STD_LOGIC_VECTOR (44 downto 0) := "000000000000000000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal voxel : STD_LOGIC_VECTOR (63 downto 0);
    signal slot_base : STD_LOGIC_VECTOR (63 downto 0);
    signal phase : STD_LOGIC_VECTOR (31 downto 0);
    signal slot_start : STD_LOGIC_VECTOR (31 downto 0);
    signal n_slots : STD_LOGIC_VECTOR (31 downto 0);
    signal axis_off_q8 : STD_LOGIC_VECTOR (31 downto 0);
    signal mirror_u : STD_LOGIC_VECTOR (31 downto 0);
    signal out_r_blk_n_AW : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal out_r_blk_n_B : STD_LOGIC;
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal mirror_u_read_reg_426 : STD_LOGIC_VECTOR (31 downto 0);
    signal axis_off_q8_read_reg_431 : STD_LOGIC_VECTOR (31 downto 0);
    signal phase_read_reg_436 : STD_LOGIC_VECTOR (31 downto 0);
    signal slot_base_read_reg_441 : STD_LOGIC_VECTOR (63 downto 0);
    signal voxel_read_reg_446 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln14_1_fu_198_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln14_1_reg_451 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_reg_457 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln43_fu_218_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln43_reg_462 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_28_fu_226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_28_reg_470 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_fu_238_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_reg_475 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln46_3_fu_286_p2 : STD_LOGIC_VECTOR (44 downto 0);
    signal add_ln46_3_reg_480 : STD_LOGIC_VECTOR (44 downto 0);
    signal add_ln46_5_fu_331_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln46_5_reg_485 : STD_LOGIC_VECTOR (47 downto 0);
    signal smax_fu_337_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal smax_reg_490 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln1_reg_497 : STD_LOGIC_VECTOR (60 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal empty_fu_361_p3 : STD_LOGIC_VECTOR (44 downto 0);
    signal empty_reg_503 : STD_LOGIC_VECTOR (44 downto 0);
    signal add_ln14_1_fu_420_p2 : STD_LOGIC_VECTOR (44 downto 0);
    signal add_ln14_1_reg_513 : STD_LOGIC_VECTOR (44 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_start : STD_LOGIC;
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_done : STD_LOGIC;
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_idle : STD_LOGIC;
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_ready : STD_LOGIC;
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWVALID : STD_LOGIC;
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WVALID : STD_LOGIC;
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WSTRB : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WLAST : STD_LOGIC;
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARVALID : STD_LOGIC;
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_RREADY : STD_LOGIC;
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_BREADY : STD_LOGIC;
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWVALID : STD_LOGIC;
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WVALID : STD_LOGIC;
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WSTRB : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WLAST : STD_LOGIC;
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARVALID : STD_LOGIC;
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_RREADY : STD_LOGIC;
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_BREADY : STD_LOGIC;
    signal out_r_0_AWVALID : STD_LOGIC;
    signal out_r_0_AWREADY : STD_LOGIC;
    signal out_r_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal out_r_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal out_r_0_WVALID : STD_LOGIC;
    signal out_r_0_WREADY : STD_LOGIC;
    signal out_r_0_ARREADY : STD_LOGIC;
    signal out_r_0_RVALID : STD_LOGIC;
    signal out_r_0_RDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal out_r_0_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal out_r_0_BVALID : STD_LOGIC;
    signal out_r_0_BREADY : STD_LOGIC;
    signal vox_0_AWREADY : STD_LOGIC;
    signal vox_0_WREADY : STD_LOGIC;
    signal vox_0_ARVALID : STD_LOGIC;
    signal vox_0_ARREADY : STD_LOGIC;
    signal vox_0_RVALID : STD_LOGIC;
    signal vox_0_RREADY : STD_LOGIC;
    signal vox_0_RDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal vox_0_RFIFONUM : STD_LOGIC_VECTOR (10 downto 0);
    signal vox_0_BVALID : STD_LOGIC;
    signal grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_NS_fsm_state5 : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal sext_ln46_fu_367_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln46_3_fu_377_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_3_fu_210_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln14_fu_194_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln42_fu_232_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_4_fu_244_p3 : STD_LOGIC_VECTOR (43 downto 0);
    signal tmp_5_fu_256_p3 : STD_LOGIC_VECTOR (41 downto 0);
    signal zext_ln46_fu_252_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal zext_ln46_1_fu_264_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal tmp_6_fu_274_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal add_ln46_2_fu_268_p2 : STD_LOGIC_VECTOR (44 downto 0);
    signal zext_ln46_4_fu_282_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal tmp_7_fu_292_p3 : STD_LOGIC_VECTOR (46 downto 0);
    signal tmp_8_fu_303_p3 : STD_LOGIC_VECTOR (44 downto 0);
    signal zext_ln46_5_fu_299_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal zext_ln46_6_fu_310_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_9_fu_320_p3 : STD_LOGIC_VECTOR (40 downto 0);
    signal add_ln46_4_fu_314_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal zext_ln46_7_fu_327_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal zext_ln46_2_fu_343_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln46_fu_346_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_10_fu_381_p3 : STD_LOGIC_VECTOR (43 downto 0);
    signal tmp_11_fu_392_p3 : STD_LOGIC_VECTOR (41 downto 0);
    signal zext_ln14_fu_388_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal zext_ln14_1_fu_399_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal tmp_12_fu_409_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal add_ln14_fu_403_p2 : STD_LOGIC_VECTOR (44 downto 0);
    signal zext_ln14_2_fu_416_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pov_eta_wr_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_vox_0_AWVALID : OUT STD_LOGIC;
        m_axi_vox_0_AWREADY : IN STD_LOGIC;
        m_axi_vox_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_vox_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_vox_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_vox_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_vox_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_vox_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_vox_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_vox_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_vox_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_vox_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_vox_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_vox_0_WVALID : OUT STD_LOGIC;
        m_axi_vox_0_WREADY : IN STD_LOGIC;
        m_axi_vox_0_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_vox_0_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_vox_0_WLAST : OUT STD_LOGIC;
        m_axi_vox_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_vox_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_vox_0_ARVALID : OUT STD_LOGIC;
        m_axi_vox_0_ARREADY : IN STD_LOGIC;
        m_axi_vox_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_vox_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_vox_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_vox_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_vox_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_vox_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_vox_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_vox_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_vox_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_vox_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_vox_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_vox_0_RVALID : IN STD_LOGIC;
        m_axi_vox_0_RREADY : OUT STD_LOGIC;
        m_axi_vox_0_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        m_axi_vox_0_RLAST : IN STD_LOGIC;
        m_axi_vox_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_vox_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
        m_axi_vox_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_vox_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_vox_0_BVALID : IN STD_LOGIC;
        m_axi_vox_0_BREADY : OUT STD_LOGIC;
        m_axi_vox_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_vox_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_vox_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_r_0_AWVALID : OUT STD_LOGIC;
        m_axi_out_r_0_AWREADY : IN STD_LOGIC;
        m_axi_out_r_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_out_r_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_r_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_out_r_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_out_r_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_r_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_r_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_r_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_out_r_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_r_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_r_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_r_0_WVALID : OUT STD_LOGIC;
        m_axi_out_r_0_WREADY : IN STD_LOGIC;
        m_axi_out_r_0_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_out_r_0_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_out_r_0_WLAST : OUT STD_LOGIC;
        m_axi_out_r_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_r_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_r_0_ARVALID : OUT STD_LOGIC;
        m_axi_out_r_0_ARREADY : IN STD_LOGIC;
        m_axi_out_r_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_out_r_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_r_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_out_r_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_out_r_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_r_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_r_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_r_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_out_r_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_r_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_r_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_r_0_RVALID : IN STD_LOGIC;
        m_axi_out_r_0_RREADY : OUT STD_LOGIC;
        m_axi_out_r_0_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        m_axi_out_r_0_RLAST : IN STD_LOGIC;
        m_axi_out_r_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_r_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_out_r_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_r_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_r_0_BVALID : IN STD_LOGIC;
        m_axi_out_r_0_BREADY : OUT STD_LOGIC;
        m_axi_out_r_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_r_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_r_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        mul_ln14 : IN STD_LOGIC_VECTOR (44 downto 0);
        sext_ln46 : IN STD_LOGIC_VECTOR (60 downto 0);
        phase : IN STD_LOGIC_VECTOR (31 downto 0);
        zext_ln18 : IN STD_LOGIC_VECTOR (30 downto 0);
        axis_off_q8 : IN STD_LOGIC_VECTOR (31 downto 0);
        voxel : IN STD_LOGIC_VECTOR (63 downto 0);
        mirror_u : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component pov_eta_wr_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        voxel : OUT STD_LOGIC_VECTOR (63 downto 0);
        slot_base : OUT STD_LOGIC_VECTOR (63 downto 0);
        phase : OUT STD_LOGIC_VECTOR (31 downto 0);
        slot_start : OUT STD_LOGIC_VECTOR (31 downto 0);
        n_slots : OUT STD_LOGIC_VECTOR (31 downto 0);
        axis_off_q8 : OUT STD_LOGIC_VECTOR (31 downto 0);
        mirror_u : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component pov_eta_wr_out_r_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;


    component pov_eta_wr_vox_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (10 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;



begin
    grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175 : component pov_eta_wr_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_start,
        ap_done => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_done,
        ap_idle => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_idle,
        ap_ready => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_ready,
        m_axi_vox_0_AWVALID => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWVALID,
        m_axi_vox_0_AWREADY => ap_const_logic_0,
        m_axi_vox_0_AWADDR => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWADDR,
        m_axi_vox_0_AWID => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWID,
        m_axi_vox_0_AWLEN => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWLEN,
        m_axi_vox_0_AWSIZE => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWSIZE,
        m_axi_vox_0_AWBURST => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWBURST,
        m_axi_vox_0_AWLOCK => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWLOCK,
        m_axi_vox_0_AWCACHE => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWCACHE,
        m_axi_vox_0_AWPROT => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWPROT,
        m_axi_vox_0_AWQOS => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWQOS,
        m_axi_vox_0_AWREGION => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWREGION,
        m_axi_vox_0_AWUSER => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWUSER,
        m_axi_vox_0_WVALID => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WVALID,
        m_axi_vox_0_WREADY => ap_const_logic_0,
        m_axi_vox_0_WDATA => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WDATA,
        m_axi_vox_0_WSTRB => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WSTRB,
        m_axi_vox_0_WLAST => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WLAST,
        m_axi_vox_0_WID => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WID,
        m_axi_vox_0_WUSER => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WUSER,
        m_axi_vox_0_ARVALID => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARVALID,
        m_axi_vox_0_ARREADY => vox_0_ARREADY,
        m_axi_vox_0_ARADDR => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARADDR,
        m_axi_vox_0_ARID => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARID,
        m_axi_vox_0_ARLEN => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARLEN,
        m_axi_vox_0_ARSIZE => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARSIZE,
        m_axi_vox_0_ARBURST => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARBURST,
        m_axi_vox_0_ARLOCK => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARLOCK,
        m_axi_vox_0_ARCACHE => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARCACHE,
        m_axi_vox_0_ARPROT => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARPROT,
        m_axi_vox_0_ARQOS => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARQOS,
        m_axi_vox_0_ARREGION => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARREGION,
        m_axi_vox_0_ARUSER => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARUSER,
        m_axi_vox_0_RVALID => vox_0_RVALID,
        m_axi_vox_0_RREADY => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_RREADY,
        m_axi_vox_0_RDATA => vox_0_RDATA,
        m_axi_vox_0_RLAST => ap_const_logic_0,
        m_axi_vox_0_RID => ap_const_lv1_0,
        m_axi_vox_0_RFIFONUM => vox_0_RFIFONUM,
        m_axi_vox_0_RUSER => ap_const_lv1_0,
        m_axi_vox_0_RRESP => ap_const_lv2_0,
        m_axi_vox_0_BVALID => ap_const_logic_0,
        m_axi_vox_0_BREADY => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_BREADY,
        m_axi_vox_0_BRESP => ap_const_lv2_0,
        m_axi_vox_0_BID => ap_const_lv1_0,
        m_axi_vox_0_BUSER => ap_const_lv1_0,
        m_axi_out_r_0_AWVALID => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWVALID,
        m_axi_out_r_0_AWREADY => out_r_0_AWREADY,
        m_axi_out_r_0_AWADDR => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWADDR,
        m_axi_out_r_0_AWID => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWID,
        m_axi_out_r_0_AWLEN => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWLEN,
        m_axi_out_r_0_AWSIZE => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWSIZE,
        m_axi_out_r_0_AWBURST => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWBURST,
        m_axi_out_r_0_AWLOCK => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWLOCK,
        m_axi_out_r_0_AWCACHE => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWCACHE,
        m_axi_out_r_0_AWPROT => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWPROT,
        m_axi_out_r_0_AWQOS => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWQOS,
        m_axi_out_r_0_AWREGION => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWREGION,
        m_axi_out_r_0_AWUSER => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWUSER,
        m_axi_out_r_0_WVALID => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WVALID,
        m_axi_out_r_0_WREADY => out_r_0_WREADY,
        m_axi_out_r_0_WDATA => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WDATA,
        m_axi_out_r_0_WSTRB => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WSTRB,
        m_axi_out_r_0_WLAST => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WLAST,
        m_axi_out_r_0_WID => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WID,
        m_axi_out_r_0_WUSER => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WUSER,
        m_axi_out_r_0_ARVALID => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARVALID,
        m_axi_out_r_0_ARREADY => ap_const_logic_0,
        m_axi_out_r_0_ARADDR => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARADDR,
        m_axi_out_r_0_ARID => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARID,
        m_axi_out_r_0_ARLEN => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARLEN,
        m_axi_out_r_0_ARSIZE => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARSIZE,
        m_axi_out_r_0_ARBURST => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARBURST,
        m_axi_out_r_0_ARLOCK => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARLOCK,
        m_axi_out_r_0_ARCACHE => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARCACHE,
        m_axi_out_r_0_ARPROT => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARPROT,
        m_axi_out_r_0_ARQOS => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARQOS,
        m_axi_out_r_0_ARREGION => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARREGION,
        m_axi_out_r_0_ARUSER => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARUSER,
        m_axi_out_r_0_RVALID => ap_const_logic_0,
        m_axi_out_r_0_RREADY => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_RREADY,
        m_axi_out_r_0_RDATA => ap_const_lv64_0,
        m_axi_out_r_0_RLAST => ap_const_logic_0,
        m_axi_out_r_0_RID => ap_const_lv1_0,
        m_axi_out_r_0_RFIFONUM => ap_const_lv9_0,
        m_axi_out_r_0_RUSER => ap_const_lv1_0,
        m_axi_out_r_0_RRESP => ap_const_lv2_0,
        m_axi_out_r_0_BVALID => out_r_0_BVALID,
        m_axi_out_r_0_BREADY => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_BREADY,
        m_axi_out_r_0_BRESP => ap_const_lv2_0,
        m_axi_out_r_0_BID => ap_const_lv1_0,
        m_axi_out_r_0_BUSER => ap_const_lv1_0,
        mul_ln14 => add_ln14_1_reg_513,
        sext_ln46 => trunc_ln1_reg_497,
        phase => phase_read_reg_436,
        zext_ln18 => select_ln43_reg_462,
        axis_off_q8 => axis_off_q8_read_reg_431,
        voxel => voxel_read_reg_446,
        mirror_u => mirror_u_read_reg_426);

    control_s_axi_U : component pov_eta_wr_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        voxel => voxel,
        slot_base => slot_base,
        phase => phase,
        slot_start => slot_start,
        n_slots => n_slots,
        axis_off_q8 => axis_off_q8,
        mirror_u => mirror_u);

    out_r_m_axi_U : component pov_eta_wr_out_r_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 4,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 64,
        C_M_AXI_ID_WIDTH => C_M_AXI_OUT_R_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_OUT_R_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_OUT_R_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_OUT_R_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_OUT_R_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_OUT_R_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_OUT_R_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_OUT_R_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_OUT_R_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_OUT_R_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_OUT_R_CACHE_VALUE,
        CH0_USER_RFIFONUM_WIDTH => 9,
        CH0_USER_DW => 64,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 0,
        NUM_WRITE_OUTSTANDING => 16)
    port map (
        AWVALID => m_axi_out_r_AWVALID,
        AWREADY => m_axi_out_r_AWREADY,
        AWADDR => m_axi_out_r_AWADDR,
        AWID => m_axi_out_r_AWID,
        AWLEN => m_axi_out_r_AWLEN,
        AWSIZE => m_axi_out_r_AWSIZE,
        AWBURST => m_axi_out_r_AWBURST,
        AWLOCK => m_axi_out_r_AWLOCK,
        AWCACHE => m_axi_out_r_AWCACHE,
        AWPROT => m_axi_out_r_AWPROT,
        AWQOS => m_axi_out_r_AWQOS,
        AWREGION => m_axi_out_r_AWREGION,
        AWUSER => m_axi_out_r_AWUSER,
        WVALID => m_axi_out_r_WVALID,
        WREADY => m_axi_out_r_WREADY,
        WDATA => m_axi_out_r_WDATA,
        WSTRB => m_axi_out_r_WSTRB,
        WLAST => m_axi_out_r_WLAST,
        WID => m_axi_out_r_WID,
        WUSER => m_axi_out_r_WUSER,
        ARVALID => m_axi_out_r_ARVALID,
        ARREADY => m_axi_out_r_ARREADY,
        ARADDR => m_axi_out_r_ARADDR,
        ARID => m_axi_out_r_ARID,
        ARLEN => m_axi_out_r_ARLEN,
        ARSIZE => m_axi_out_r_ARSIZE,
        ARBURST => m_axi_out_r_ARBURST,
        ARLOCK => m_axi_out_r_ARLOCK,
        ARCACHE => m_axi_out_r_ARCACHE,
        ARPROT => m_axi_out_r_ARPROT,
        ARQOS => m_axi_out_r_ARQOS,
        ARREGION => m_axi_out_r_ARREGION,
        ARUSER => m_axi_out_r_ARUSER,
        RVALID => m_axi_out_r_RVALID,
        RREADY => m_axi_out_r_RREADY,
        RDATA => m_axi_out_r_RDATA,
        RLAST => m_axi_out_r_RLAST,
        RID => m_axi_out_r_RID,
        RUSER => m_axi_out_r_RUSER,
        RRESP => m_axi_out_r_RRESP,
        BVALID => m_axi_out_r_BVALID,
        BREADY => m_axi_out_r_BREADY,
        BRESP => m_axi_out_r_BRESP,
        BID => m_axi_out_r_BID,
        BUSER => m_axi_out_r_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => ap_const_logic_0,
        I_CH0_ARREADY => out_r_0_ARREADY,
        I_CH0_ARADDR => ap_const_lv64_0,
        I_CH0_ARLEN => ap_const_lv32_0,
        I_CH0_RVALID => out_r_0_RVALID,
        I_CH0_RREADY => ap_const_logic_0,
        I_CH0_RDATA => out_r_0_RDATA,
        I_CH0_RFIFONUM => out_r_0_RFIFONUM,
        I_CH0_AWVALID => out_r_0_AWVALID,
        I_CH0_AWREADY => out_r_0_AWREADY,
        I_CH0_AWADDR => out_r_0_AWADDR,
        I_CH0_AWLEN => out_r_0_AWLEN,
        I_CH0_WVALID => out_r_0_WVALID,
        I_CH0_WREADY => out_r_0_WREADY,
        I_CH0_WDATA => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WDATA,
        I_CH0_WSTRB => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WSTRB,
        I_CH0_BVALID => out_r_0_BVALID,
        I_CH0_BREADY => out_r_0_BREADY);

    vox_m_axi_U : component pov_eta_wr_vox_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 7,
        MAX_READ_BURST_LENGTH => 64,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_VOX_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_VOX_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_VOX_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_VOX_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_VOX_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_VOX_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_VOX_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_VOX_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_VOX_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_VOX_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_VOX_CACHE_VALUE,
        CH0_USER_RFIFONUM_WIDTH => 11,
        CH0_USER_DW => 64,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 0)
    port map (
        AWVALID => m_axi_vox_AWVALID,
        AWREADY => m_axi_vox_AWREADY,
        AWADDR => m_axi_vox_AWADDR,
        AWID => m_axi_vox_AWID,
        AWLEN => m_axi_vox_AWLEN,
        AWSIZE => m_axi_vox_AWSIZE,
        AWBURST => m_axi_vox_AWBURST,
        AWLOCK => m_axi_vox_AWLOCK,
        AWCACHE => m_axi_vox_AWCACHE,
        AWPROT => m_axi_vox_AWPROT,
        AWQOS => m_axi_vox_AWQOS,
        AWREGION => m_axi_vox_AWREGION,
        AWUSER => m_axi_vox_AWUSER,
        WVALID => m_axi_vox_WVALID,
        WREADY => m_axi_vox_WREADY,
        WDATA => m_axi_vox_WDATA,
        WSTRB => m_axi_vox_WSTRB,
        WLAST => m_axi_vox_WLAST,
        WID => m_axi_vox_WID,
        WUSER => m_axi_vox_WUSER,
        ARVALID => m_axi_vox_ARVALID,
        ARREADY => m_axi_vox_ARREADY,
        ARADDR => m_axi_vox_ARADDR,
        ARID => m_axi_vox_ARID,
        ARLEN => m_axi_vox_ARLEN,
        ARSIZE => m_axi_vox_ARSIZE,
        ARBURST => m_axi_vox_ARBURST,
        ARLOCK => m_axi_vox_ARLOCK,
        ARCACHE => m_axi_vox_ARCACHE,
        ARPROT => m_axi_vox_ARPROT,
        ARQOS => m_axi_vox_ARQOS,
        ARREGION => m_axi_vox_ARREGION,
        ARUSER => m_axi_vox_ARUSER,
        RVALID => m_axi_vox_RVALID,
        RREADY => m_axi_vox_RREADY,
        RDATA => m_axi_vox_RDATA,
        RLAST => m_axi_vox_RLAST,
        RID => m_axi_vox_RID,
        RUSER => m_axi_vox_RUSER,
        RRESP => m_axi_vox_RRESP,
        BVALID => m_axi_vox_BVALID,
        BREADY => m_axi_vox_BREADY,
        BRESP => m_axi_vox_BRESP,
        BID => m_axi_vox_BID,
        BUSER => m_axi_vox_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => vox_0_ARVALID,
        I_CH0_ARREADY => vox_0_ARREADY,
        I_CH0_ARADDR => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARADDR,
        I_CH0_ARLEN => grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARLEN,
        I_CH0_RVALID => vox_0_RVALID,
        I_CH0_RREADY => vox_0_RREADY,
        I_CH0_RDATA => vox_0_RDATA,
        I_CH0_RFIFONUM => vox_0_RFIFONUM,
        I_CH0_AWVALID => ap_const_logic_0,
        I_CH0_AWREADY => vox_0_AWREADY,
        I_CH0_AWADDR => ap_const_lv64_0,
        I_CH0_AWLEN => ap_const_lv32_0,
        I_CH0_WVALID => ap_const_logic_0,
        I_CH0_WREADY => vox_0_WREADY,
        I_CH0_WDATA => ap_const_lv64_0,
        I_CH0_WSTRB => ap_const_lv8_0,
        I_CH0_BVALID => vox_0_BVALID,
        I_CH0_BREADY => ap_const_logic_0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_NS_fsm_state5) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_ready = ap_const_logic_1)) then 
                    grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                    add_ln14_1_reg_513(44 downto 7) <= add_ln14_1_fu_420_p2(44 downto 7);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                    add_ln46_3_reg_480(44 downto 7) <= add_ln46_3_fu_286_p2(44 downto 7);
                    add_ln46_5_reg_485(47 downto 10) <= add_ln46_5_fu_331_p2(47 downto 10);
                icmp_ln46_reg_475 <= icmp_ln46_fu_238_p2;
                smax_reg_490 <= smax_fu_337_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                axis_off_q8_read_reg_431 <= axis_off_q8;
                empty_28_reg_470 <= empty_28_fu_226_p2;
                mirror_u_read_reg_426 <= mirror_u;
                phase_read_reg_436 <= phase;
                select_ln43_reg_462 <= select_ln43_fu_218_p3;
                slot_base_read_reg_441 <= slot_base;
                tmp_reg_457 <= n_slots(31 downto 31);
                trunc_ln14_1_reg_451 <= trunc_ln14_1_fu_198_p1;
                voxel_read_reg_446 <= voxel;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                    empty_reg_503(44 downto 7) <= empty_fu_361_p3(44 downto 7);
                trunc_ln1_reg_497 <= add_ln46_fu_346_p2(63 downto 3);
            end if;
        end if;
    end process;
    add_ln46_3_reg_480(6 downto 0) <= "0000000";
    add_ln46_5_reg_485(9 downto 0) <= "0000000000";
    empty_reg_503(6 downto 0) <= "0000000";
    add_ln14_1_reg_513(6 downto 0) <= "0000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, ap_CS_fsm_state11, grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_done, out_r_0_AWREADY, out_r_0_BVALID, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((out_r_0_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                if (((out_r_0_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;
    add_ln14_1_fu_420_p2 <= std_logic_vector(unsigned(add_ln14_fu_403_p2) + unsigned(zext_ln14_2_fu_416_p1));
    add_ln14_fu_403_p2 <= std_logic_vector(unsigned(zext_ln14_fu_388_p1) + unsigned(zext_ln14_1_fu_399_p1));
    add_ln46_2_fu_268_p2 <= std_logic_vector(unsigned(zext_ln46_fu_252_p1) + unsigned(zext_ln46_1_fu_264_p1));
    add_ln46_3_fu_286_p2 <= std_logic_vector(unsigned(add_ln46_2_fu_268_p2) + unsigned(zext_ln46_4_fu_282_p1));
    add_ln46_4_fu_314_p2 <= std_logic_vector(unsigned(zext_ln46_5_fu_299_p1) + unsigned(zext_ln46_6_fu_310_p1));
    add_ln46_5_fu_331_p2 <= std_logic_vector(unsigned(add_ln46_4_fu_314_p2) + unsigned(zext_ln46_7_fu_327_p1));
    add_ln46_fu_346_p2 <= std_logic_vector(unsigned(zext_ln46_2_fu_343_p1) + unsigned(slot_base_read_reg_441));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_NS_fsm_state5 <= ap_NS_fsm(4);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state11_blk_assign_proc : process(out_r_0_BVALID)
    begin
        if ((out_r_0_BVALID = ap_const_logic_0)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(out_r_0_AWREADY)
    begin
        if ((out_r_0_AWREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_done)
    begin
        if ((grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state11, out_r_0_BVALID)
    begin
        if (((out_r_0_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state11, out_r_0_BVALID)
    begin
        if (((out_r_0_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    empty_28_fu_226_p2 <= "1" when (signed(n_slots) > signed(ap_const_lv32_0)) else "0";
    empty_fu_361_p3 <= 
        add_ln46_3_reg_480 when (icmp_ln46_reg_475(0) = '1') else 
        ap_const_lv45_0;
    grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_start <= grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_start_reg;
    icmp_ln46_fu_238_p2 <= "0" when (select_ln42_fu_232_p3 = ap_const_lv31_0) else "1";

    out_r_0_AWADDR_assign_proc : process(ap_CS_fsm_state4, grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWADDR, out_r_0_AWREADY, ap_CS_fsm_state5, ap_CS_fsm_state6, sext_ln46_fu_367_p1)
    begin
        if (((out_r_0_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            out_r_0_AWADDR <= sext_ln46_fu_367_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            out_r_0_AWADDR <= grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWADDR;
        else 
            out_r_0_AWADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    out_r_0_AWLEN_assign_proc : process(ap_CS_fsm_state4, grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWLEN, out_r_0_AWREADY, ap_CS_fsm_state5, ap_CS_fsm_state6, zext_ln46_3_fu_377_p1)
    begin
        if (((out_r_0_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            out_r_0_AWLEN <= zext_ln46_3_fu_377_p1(32 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            out_r_0_AWLEN <= grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWLEN;
        else 
            out_r_0_AWLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    out_r_0_AWVALID_assign_proc : process(ap_CS_fsm_state4, grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWVALID, out_r_0_AWREADY, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((out_r_0_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            out_r_0_AWVALID <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            out_r_0_AWVALID <= grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWVALID;
        else 
            out_r_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    out_r_0_BREADY_assign_proc : process(ap_CS_fsm_state11, grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_BREADY, out_r_0_BVALID, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((out_r_0_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            out_r_0_BREADY <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            out_r_0_BREADY <= grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_BREADY;
        else 
            out_r_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    out_r_0_WVALID_assign_proc : process(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WVALID, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            out_r_0_WVALID <= grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WVALID;
        else 
            out_r_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;


    out_r_blk_n_AW_assign_proc : process(m_axi_out_r_AWREADY, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            out_r_blk_n_AW <= m_axi_out_r_AWREADY;
        else 
            out_r_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    out_r_blk_n_B_assign_proc : process(m_axi_out_r_BVALID, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            out_r_blk_n_B <= m_axi_out_r_BVALID;
        else 
            out_r_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;

    select_ln42_fu_232_p3 <= 
        ap_const_lv31_0 when (tmp_reg_457(0) = '1') else 
        trunc_ln14_1_reg_451;
    select_ln43_fu_218_p3 <= 
        ap_const_lv31_0 when (tmp_3_fu_210_p3(0) = '1') else 
        trunc_ln14_fu_194_p1;
        sext_ln46_fu_367_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1_reg_497),64));

    smax_fu_337_p3 <= 
        trunc_ln14_1_reg_451 when (empty_28_reg_470(0) = '1') else 
        ap_const_lv31_0;
    tmp_10_fu_381_p3 <= (smax_reg_490 & ap_const_lv13_0);
    tmp_11_fu_392_p3 <= (smax_reg_490 & ap_const_lv11_0);
    tmp_12_fu_409_p3 <= (smax_reg_490 & ap_const_lv7_0);
    tmp_3_fu_210_p3 <= slot_start(31 downto 31);
    tmp_4_fu_244_p3 <= (select_ln42_fu_232_p3 & ap_const_lv13_0);
    tmp_5_fu_256_p3 <= (select_ln42_fu_232_p3 & ap_const_lv11_0);
    tmp_6_fu_274_p3 <= (select_ln42_fu_232_p3 & ap_const_lv7_0);
    tmp_7_fu_292_p3 <= (select_ln43_reg_462 & ap_const_lv16_0);
    tmp_8_fu_303_p3 <= (select_ln43_reg_462 & ap_const_lv14_0);
    tmp_9_fu_320_p3 <= (select_ln43_reg_462 & ap_const_lv10_0);
    trunc_ln14_1_fu_198_p1 <= n_slots(31 - 1 downto 0);
    trunc_ln14_fu_194_p1 <= slot_start(31 - 1 downto 0);

    vox_0_ARVALID_assign_proc : process(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARVALID, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            vox_0_ARVALID <= grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARVALID;
        else 
            vox_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;


    vox_0_RREADY_assign_proc : process(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_RREADY, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            vox_0_RREADY <= grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_RREADY;
        else 
            vox_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln14_1_fu_399_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_fu_392_p3),45));
    zext_ln14_2_fu_416_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_12_fu_409_p3),45));
    zext_ln14_fu_388_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_381_p3),45));
    zext_ln46_1_fu_264_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_256_p3),45));
    zext_ln46_2_fu_343_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln46_5_reg_485),64));
    zext_ln46_3_fu_377_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_reg_503),64));
    zext_ln46_4_fu_282_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_274_p3),45));
    zext_ln46_5_fu_299_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_292_p3),48));
    zext_ln46_6_fu_310_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_303_p3),48));
    zext_ln46_7_fu_327_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_320_p3),48));
    zext_ln46_fu_252_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_244_p3),45));
end behav;
