// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="pov_eta_rd_pov_eta_rd,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-2,HLS_INPUT_CLOCK=6.670000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.869100,HLS_SYN_LAT=3131416,HLS_SYN_TPT=none,HLS_SYN_MEM=6,HLS_SYN_DSP=0,HLS_SYN_FF=3493,HLS_SYN_LUT=3304,HLS_VERSION=2024_2}" *)

module pov_eta_rd (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_vox_AWVALID,
        m_axi_vox_AWREADY,
        m_axi_vox_AWADDR,
        m_axi_vox_AWID,
        m_axi_vox_AWLEN,
        m_axi_vox_AWSIZE,
        m_axi_vox_AWBURST,
        m_axi_vox_AWLOCK,
        m_axi_vox_AWCACHE,
        m_axi_vox_AWPROT,
        m_axi_vox_AWQOS,
        m_axi_vox_AWREGION,
        m_axi_vox_AWUSER,
        m_axi_vox_WVALID,
        m_axi_vox_WREADY,
        m_axi_vox_WDATA,
        m_axi_vox_WSTRB,
        m_axi_vox_WLAST,
        m_axi_vox_WID,
        m_axi_vox_WUSER,
        m_axi_vox_ARVALID,
        m_axi_vox_ARREADY,
        m_axi_vox_ARADDR,
        m_axi_vox_ARID,
        m_axi_vox_ARLEN,
        m_axi_vox_ARSIZE,
        m_axi_vox_ARBURST,
        m_axi_vox_ARLOCK,
        m_axi_vox_ARCACHE,
        m_axi_vox_ARPROT,
        m_axi_vox_ARQOS,
        m_axi_vox_ARREGION,
        m_axi_vox_ARUSER,
        m_axi_vox_RVALID,
        m_axi_vox_RREADY,
        m_axi_vox_RDATA,
        m_axi_vox_RLAST,
        m_axi_vox_RID,
        m_axi_vox_RUSER,
        m_axi_vox_RRESP,
        m_axi_vox_BVALID,
        m_axi_vox_BREADY,
        m_axi_vox_BRESP,
        m_axi_vox_BID,
        m_axi_vox_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 39'd1;
parameter    ap_ST_fsm_state2 = 39'd2;
parameter    ap_ST_fsm_state3 = 39'd4;
parameter    ap_ST_fsm_state4 = 39'd8;
parameter    ap_ST_fsm_state5 = 39'd16;
parameter    ap_ST_fsm_state6 = 39'd32;
parameter    ap_ST_fsm_state7 = 39'd64;
parameter    ap_ST_fsm_state8 = 39'd128;
parameter    ap_ST_fsm_state9 = 39'd256;
parameter    ap_ST_fsm_state10 = 39'd512;
parameter    ap_ST_fsm_state11 = 39'd1024;
parameter    ap_ST_fsm_state12 = 39'd2048;
parameter    ap_ST_fsm_state13 = 39'd4096;
parameter    ap_ST_fsm_state14 = 39'd8192;
parameter    ap_ST_fsm_state15 = 39'd16384;
parameter    ap_ST_fsm_state16 = 39'd32768;
parameter    ap_ST_fsm_state17 = 39'd65536;
parameter    ap_ST_fsm_state18 = 39'd131072;
parameter    ap_ST_fsm_state19 = 39'd262144;
parameter    ap_ST_fsm_state20 = 39'd524288;
parameter    ap_ST_fsm_state21 = 39'd1048576;
parameter    ap_ST_fsm_state22 = 39'd2097152;
parameter    ap_ST_fsm_state23 = 39'd4194304;
parameter    ap_ST_fsm_state24 = 39'd8388608;
parameter    ap_ST_fsm_state25 = 39'd16777216;
parameter    ap_ST_fsm_state26 = 39'd33554432;
parameter    ap_ST_fsm_state27 = 39'd67108864;
parameter    ap_ST_fsm_state28 = 39'd134217728;
parameter    ap_ST_fsm_state29 = 39'd268435456;
parameter    ap_ST_fsm_state30 = 39'd536870912;
parameter    ap_ST_fsm_state31 = 39'd1073741824;
parameter    ap_ST_fsm_state32 = 39'd2147483648;
parameter    ap_ST_fsm_state33 = 39'd4294967296;
parameter    ap_ST_fsm_state34 = 39'd8589934592;
parameter    ap_ST_fsm_state35 = 39'd17179869184;
parameter    ap_ST_fsm_state36 = 39'd34359738368;
parameter    ap_ST_fsm_state37 = 39'd68719476736;
parameter    ap_ST_fsm_state38 = 39'd137438953472;
parameter    ap_ST_fsm_state39 = 39'd274877906944;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_VOX_ID_WIDTH = 1;
parameter    C_M_AXI_VOX_ADDR_WIDTH = 64;
parameter    C_M_AXI_VOX_DATA_WIDTH = 64;
parameter    C_M_AXI_VOX_AWUSER_WIDTH = 1;
parameter    C_M_AXI_VOX_ARUSER_WIDTH = 1;
parameter    C_M_AXI_VOX_WUSER_WIDTH = 1;
parameter    C_M_AXI_VOX_RUSER_WIDTH = 1;
parameter    C_M_AXI_VOX_BUSER_WIDTH = 1;
parameter    C_M_AXI_VOX_USER_VALUE = 0;
parameter    C_M_AXI_VOX_PROT_VALUE = 0;
parameter    C_M_AXI_VOX_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_VOX_WSTRB_WIDTH = (64 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_vox_AWVALID;
input   m_axi_vox_AWREADY;
output  [C_M_AXI_VOX_ADDR_WIDTH - 1:0] m_axi_vox_AWADDR;
output  [C_M_AXI_VOX_ID_WIDTH - 1:0] m_axi_vox_AWID;
output  [7:0] m_axi_vox_AWLEN;
output  [2:0] m_axi_vox_AWSIZE;
output  [1:0] m_axi_vox_AWBURST;
output  [1:0] m_axi_vox_AWLOCK;
output  [3:0] m_axi_vox_AWCACHE;
output  [2:0] m_axi_vox_AWPROT;
output  [3:0] m_axi_vox_AWQOS;
output  [3:0] m_axi_vox_AWREGION;
output  [C_M_AXI_VOX_AWUSER_WIDTH - 1:0] m_axi_vox_AWUSER;
output   m_axi_vox_WVALID;
input   m_axi_vox_WREADY;
output  [C_M_AXI_VOX_DATA_WIDTH - 1:0] m_axi_vox_WDATA;
output  [C_M_AXI_VOX_WSTRB_WIDTH - 1:0] m_axi_vox_WSTRB;
output   m_axi_vox_WLAST;
output  [C_M_AXI_VOX_ID_WIDTH - 1:0] m_axi_vox_WID;
output  [C_M_AXI_VOX_WUSER_WIDTH - 1:0] m_axi_vox_WUSER;
output   m_axi_vox_ARVALID;
input   m_axi_vox_ARREADY;
output  [C_M_AXI_VOX_ADDR_WIDTH - 1:0] m_axi_vox_ARADDR;
output  [C_M_AXI_VOX_ID_WIDTH - 1:0] m_axi_vox_ARID;
output  [7:0] m_axi_vox_ARLEN;
output  [2:0] m_axi_vox_ARSIZE;
output  [1:0] m_axi_vox_ARBURST;
output  [1:0] m_axi_vox_ARLOCK;
output  [3:0] m_axi_vox_ARCACHE;
output  [2:0] m_axi_vox_ARPROT;
output  [3:0] m_axi_vox_ARQOS;
output  [3:0] m_axi_vox_ARREGION;
output  [C_M_AXI_VOX_ARUSER_WIDTH - 1:0] m_axi_vox_ARUSER;
input   m_axi_vox_RVALID;
output   m_axi_vox_RREADY;
input  [C_M_AXI_VOX_DATA_WIDTH - 1:0] m_axi_vox_RDATA;
input   m_axi_vox_RLAST;
input  [C_M_AXI_VOX_ID_WIDTH - 1:0] m_axi_vox_RID;
input  [C_M_AXI_VOX_RUSER_WIDTH - 1:0] m_axi_vox_RUSER;
input  [1:0] m_axi_vox_RRESP;
input   m_axi_vox_BVALID;
output   m_axi_vox_BREADY;
input  [1:0] m_axi_vox_BRESP;
input  [C_M_AXI_VOX_ID_WIDTH - 1:0] m_axi_vox_BID;
input  [C_M_AXI_VOX_BUSER_WIDTH - 1:0] m_axi_vox_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [38:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] voxel;
wire   [31:0] phase;
wire   [31:0] n_slots;
wire   [31:0] axis_off_q8;
wire   [31:0] mirror_u;
wire   [31:0] pf_cols;
reg    xor_out_ap_vld;
reg   [31:0] mirror_u_read_reg_362;
reg   [31:0] axis_off_q8_read_reg_367;
reg   [63:0] voxel_read_reg_377;
wire   [0:0] icmp_ln51_fu_225_p2;
reg   [0:0] icmp_ln51_reg_388;
wire   [2:0] pf_1_fu_257_p3;
reg   [2:0] pf_1_reg_393;
wire   [19:0] sub_ln59_fu_295_p2;
reg   [19:0] sub_ln59_reg_399;
wire   [19:0] total_cols_fu_301_p3;
reg   [19:0] total_cols_reg_404;
wire    ap_CS_fsm_state33;
wire   [9:0] trunc_ln56_fu_334_p1;
reg   [9:0] trunc_ln56_reg_414;
wire    ap_CS_fsm_state36;
reg   [0:0] tmp_5_reg_419;
wire   [9:0] add_ln57_fu_346_p2;
reg   [9:0] add_ln57_reg_424;
wire   [25:0] grp_fu_328_p2;
reg   [25:0] mul_ln65_reg_429;
wire   [9:0] ang0_1_fu_352_p3;
reg   [9:0] ang0_1_reg_434;
wire    ap_CS_fsm_state37;
wire    grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_start;
wire    grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_done;
wire    grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_idle;
wire    grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_ready;
wire    grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWVALID;
wire   [63:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWADDR;
wire   [0:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWID;
wire   [31:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWLEN;
wire   [2:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWSIZE;
wire   [1:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWBURST;
wire   [1:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWLOCK;
wire   [3:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWCACHE;
wire   [2:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWPROT;
wire   [3:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWQOS;
wire   [3:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWREGION;
wire   [0:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWUSER;
wire    grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WVALID;
wire   [63:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WDATA;
wire   [7:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WSTRB;
wire    grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WLAST;
wire   [0:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WID;
wire   [0:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WUSER;
wire    grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARVALID;
wire   [63:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARADDR;
wire   [0:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARID;
wire   [31:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARLEN;
wire   [2:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARSIZE;
wire   [1:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARBURST;
wire   [1:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARLOCK;
wire   [3:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARCACHE;
wire   [2:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARPROT;
wire   [3:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARQOS;
wire   [3:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARREGION;
wire   [0:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARUSER;
wire    grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_RREADY;
wire    grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_BREADY;
wire   [63:0] grp_pov_eta_rd_Pipeline_FLAT_fu_173_acc_out;
wire    grp_pov_eta_rd_Pipeline_FLAT_fu_173_acc_out_ap_vld;
wire    vox_0_AWREADY;
wire    vox_0_WREADY;
reg    vox_0_ARVALID;
wire    vox_0_ARREADY;
wire    vox_0_RVALID;
reg    vox_0_RREADY;
wire   [63:0] vox_0_RDATA;
wire   [9:0] vox_0_RFIFONUM;
wire    vox_0_BVALID;
reg    grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_start_reg;
wire    ap_CS_fsm_state38;
wire    ap_CS_fsm_state39;
wire   [0:0] tmp_fu_199_p3;
wire   [30:0] trunc_ln29_1_fu_195_p1;
wire   [30:0] ns_fu_207_p3;
wire   [18:0] tmp_3_fu_215_p4;
wire   [0:0] tmp_4_fu_231_p3;
wire   [30:0] trunc_ln29_fu_191_p1;
wire   [30:0] pf_fu_239_p3;
wire   [0:0] icmp_ln54_fu_251_p2;
wire   [2:0] trunc_ln52_fu_247_p1;
wire   [10:0] grp_fu_265_p1;
wire   [11:0] trunc_ln59_fu_271_p1;
wire   [13:0] trunc_ln59_1_fu_283_p1;
wire   [19:0] p_shl_fu_275_p3;
wire   [19:0] p_shl3_fu_287_p3;
wire   [16:0] tmp_1_fu_307_p4;
wire   [19:0] tmp_2_fu_317_p3;
wire   [19:0] grp_fu_328_p0;
wire   [6:0] grp_fu_328_p1;
wire   [31:0] grp_fu_265_p2;
reg    grp_fu_265_ap_start;
wire    grp_fu_265_ap_done;
reg   [38:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
reg    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire   [25:0] grp_fu_328_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 39'd1;
#0 grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_start_reg = 1'b0;
end

pov_eta_rd_pov_eta_rd_Pipeline_FLAT grp_pov_eta_rd_Pipeline_FLAT_fu_173(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_start),
    .ap_done(grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_done),
    .ap_idle(grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_idle),
    .ap_ready(grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_ready),
    .m_axi_vox_0_AWVALID(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWVALID),
    .m_axi_vox_0_AWREADY(1'b0),
    .m_axi_vox_0_AWADDR(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWADDR),
    .m_axi_vox_0_AWID(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWID),
    .m_axi_vox_0_AWLEN(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWLEN),
    .m_axi_vox_0_AWSIZE(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWSIZE),
    .m_axi_vox_0_AWBURST(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWBURST),
    .m_axi_vox_0_AWLOCK(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWLOCK),
    .m_axi_vox_0_AWCACHE(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWCACHE),
    .m_axi_vox_0_AWPROT(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWPROT),
    .m_axi_vox_0_AWQOS(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWQOS),
    .m_axi_vox_0_AWREGION(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWREGION),
    .m_axi_vox_0_AWUSER(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWUSER),
    .m_axi_vox_0_WVALID(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WVALID),
    .m_axi_vox_0_WREADY(1'b0),
    .m_axi_vox_0_WDATA(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WDATA),
    .m_axi_vox_0_WSTRB(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WSTRB),
    .m_axi_vox_0_WLAST(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WLAST),
    .m_axi_vox_0_WID(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WID),
    .m_axi_vox_0_WUSER(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WUSER),
    .m_axi_vox_0_ARVALID(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARVALID),
    .m_axi_vox_0_ARREADY(vox_0_ARREADY),
    .m_axi_vox_0_ARADDR(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARADDR),
    .m_axi_vox_0_ARID(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARID),
    .m_axi_vox_0_ARLEN(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARLEN),
    .m_axi_vox_0_ARSIZE(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARSIZE),
    .m_axi_vox_0_ARBURST(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARBURST),
    .m_axi_vox_0_ARLOCK(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARLOCK),
    .m_axi_vox_0_ARCACHE(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARCACHE),
    .m_axi_vox_0_ARPROT(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARPROT),
    .m_axi_vox_0_ARQOS(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARQOS),
    .m_axi_vox_0_ARREGION(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARREGION),
    .m_axi_vox_0_ARUSER(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARUSER),
    .m_axi_vox_0_RVALID(vox_0_RVALID),
    .m_axi_vox_0_RREADY(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_RREADY),
    .m_axi_vox_0_RDATA(vox_0_RDATA),
    .m_axi_vox_0_RLAST(1'b0),
    .m_axi_vox_0_RID(1'd0),
    .m_axi_vox_0_RFIFONUM(vox_0_RFIFONUM),
    .m_axi_vox_0_RUSER(1'd0),
    .m_axi_vox_0_RRESP(2'd0),
    .m_axi_vox_0_BVALID(1'b0),
    .m_axi_vox_0_BREADY(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_BREADY),
    .m_axi_vox_0_BRESP(2'd0),
    .m_axi_vox_0_BID(1'd0),
    .m_axi_vox_0_BUSER(1'd0),
    .mul_ln65(mul_ln65_reg_429),
    .zext_ln52(pf_1_reg_393),
    .zext_ln59(total_cols_reg_404),
    .zext_ln56(ang0_1_reg_434),
    .axis_off_q8(axis_off_q8_read_reg_367),
    .voxel(voxel_read_reg_377),
    .mirror_u(mirror_u_read_reg_362),
    .acc_out(grp_pov_eta_rd_Pipeline_FLAT_fu_173_acc_out),
    .acc_out_ap_vld(grp_pov_eta_rd_Pipeline_FLAT_fu_173_acc_out_ap_vld)
);

pov_eta_rd_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .voxel(voxel),
    .phase(phase),
    .n_slots(n_slots),
    .axis_off_q8(axis_off_q8),
    .mirror_u(mirror_u),
    .pf_cols(pf_cols),
    .xor_out(grp_pov_eta_rd_Pipeline_FLAT_fu_173_acc_out),
    .xor_out_ap_vld(xor_out_ap_vld)
);

pov_eta_rd_vox_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 64 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_VOX_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_VOX_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_VOX_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_VOX_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_VOX_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_VOX_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_VOX_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_VOX_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_VOX_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_VOX_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_VOX_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 10 ),
    .CH0_USER_DW( 64 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 8 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
vox_m_axi_U(
    .AWVALID(m_axi_vox_AWVALID),
    .AWREADY(m_axi_vox_AWREADY),
    .AWADDR(m_axi_vox_AWADDR),
    .AWID(m_axi_vox_AWID),
    .AWLEN(m_axi_vox_AWLEN),
    .AWSIZE(m_axi_vox_AWSIZE),
    .AWBURST(m_axi_vox_AWBURST),
    .AWLOCK(m_axi_vox_AWLOCK),
    .AWCACHE(m_axi_vox_AWCACHE),
    .AWPROT(m_axi_vox_AWPROT),
    .AWQOS(m_axi_vox_AWQOS),
    .AWREGION(m_axi_vox_AWREGION),
    .AWUSER(m_axi_vox_AWUSER),
    .WVALID(m_axi_vox_WVALID),
    .WREADY(m_axi_vox_WREADY),
    .WDATA(m_axi_vox_WDATA),
    .WSTRB(m_axi_vox_WSTRB),
    .WLAST(m_axi_vox_WLAST),
    .WID(m_axi_vox_WID),
    .WUSER(m_axi_vox_WUSER),
    .ARVALID(m_axi_vox_ARVALID),
    .ARREADY(m_axi_vox_ARREADY),
    .ARADDR(m_axi_vox_ARADDR),
    .ARID(m_axi_vox_ARID),
    .ARLEN(m_axi_vox_ARLEN),
    .ARSIZE(m_axi_vox_ARSIZE),
    .ARBURST(m_axi_vox_ARBURST),
    .ARLOCK(m_axi_vox_ARLOCK),
    .ARCACHE(m_axi_vox_ARCACHE),
    .ARPROT(m_axi_vox_ARPROT),
    .ARQOS(m_axi_vox_ARQOS),
    .ARREGION(m_axi_vox_ARREGION),
    .ARUSER(m_axi_vox_ARUSER),
    .RVALID(m_axi_vox_RVALID),
    .RREADY(m_axi_vox_RREADY),
    .RDATA(m_axi_vox_RDATA),
    .RLAST(m_axi_vox_RLAST),
    .RID(m_axi_vox_RID),
    .RUSER(m_axi_vox_RUSER),
    .RRESP(m_axi_vox_RRESP),
    .BVALID(m_axi_vox_BVALID),
    .BREADY(m_axi_vox_BREADY),
    .BRESP(m_axi_vox_BRESP),
    .BID(m_axi_vox_BID),
    .BUSER(m_axi_vox_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(vox_0_ARVALID),
    .I_CH0_ARREADY(vox_0_ARREADY),
    .I_CH0_ARADDR(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARADDR),
    .I_CH0_ARLEN(grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARLEN),
    .I_CH0_RVALID(vox_0_RVALID),
    .I_CH0_RREADY(vox_0_RREADY),
    .I_CH0_RDATA(vox_0_RDATA),
    .I_CH0_RFIFONUM(vox_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(vox_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(vox_0_WREADY),
    .I_CH0_WDATA(64'd0),
    .I_CH0_WSTRB(8'd0),
    .I_CH0_BVALID(vox_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

pov_eta_rd_srem_32ns_11ns_32_36_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
srem_32ns_11ns_32_36_seq_1_U23(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_265_ap_start),
    .done(grp_fu_265_ap_done),
    .din0(phase),
    .din1(grp_fu_265_p1),
    .ce(1'b1),
    .dout(grp_fu_265_p2)
);

pov_eta_rd_mul_20ns_7ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 26 ))
mul_20ns_7ns_26_4_1_U24(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_328_p0),
    .din1(grp_fu_328_p1),
    .ce(1'b1),
    .dout(grp_fu_328_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state37)) begin
            grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_start_reg <= 1'b1;
        end else if ((grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_ready == 1'b1)) begin
            grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        add_ln57_reg_424 <= add_ln57_fu_346_p2;
        mul_ln65_reg_429 <= grp_fu_328_p2;
        tmp_5_reg_419 <= grp_fu_265_p2[32'd10];
        trunc_ln56_reg_414 <= trunc_ln56_fu_334_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        ang0_1_reg_434 <= ang0_1_fu_352_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        axis_off_q8_read_reg_367 <= axis_off_q8;
        icmp_ln51_reg_388 <= icmp_ln51_fu_225_p2;
        mirror_u_read_reg_362 <= mirror_u;
        pf_1_reg_393 <= pf_1_fu_257_p3;
        sub_ln59_reg_399[19 : 6] <= sub_ln59_fu_295_p2[19 : 6];
        voxel_read_reg_377 <= voxel;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        total_cols_reg_404[19 : 6] <= total_cols_fu_301_p3[19 : 6];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

always @ (*) begin
    if ((grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_done == 1'b0)) begin
        ap_ST_fsm_state38_blk = 1'b1;
    end else begin
        ap_ST_fsm_state38_blk = 1'b0;
    end
end

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_265_ap_start = 1'b1;
    end else begin
        grp_fu_265_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37))) begin
        vox_0_ARVALID = grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARVALID;
    end else begin
        vox_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37))) begin
        vox_0_RREADY = grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_RREADY;
    end else begin
        vox_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        xor_out_ap_vld = 1'b1;
    end else begin
        xor_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            if (((1'b1 == ap_CS_fsm_state38) & (grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state39;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln57_fu_346_p2 = ($signed(trunc_ln56_fu_334_p1) + $signed(10'd603));

assign ang0_1_fu_352_p3 = ((tmp_5_reg_419[0:0] == 1'b1) ? add_ln57_reg_424 : trunc_ln56_reg_414);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_fu_265_p1 = 32'd603;

assign grp_fu_328_p0 = grp_fu_328_p00;

assign grp_fu_328_p00 = tmp_2_fu_317_p3;

assign grp_fu_328_p1 = 26'd54;

assign grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_start = grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_start_reg;

assign icmp_ln51_fu_225_p2 = ((tmp_3_fu_215_p4 != 19'd0) ? 1'b1 : 1'b0);

assign icmp_ln54_fu_251_p2 = ((pf_fu_239_p3 > 31'd6) ? 1'b1 : 1'b0);

assign ns_fu_207_p3 = ((tmp_fu_199_p3[0:0] == 1'b1) ? 31'd0 : trunc_ln29_1_fu_195_p1);

assign p_shl3_fu_287_p3 = {{trunc_ln59_1_fu_283_p1}, {6'd0}};

assign p_shl_fu_275_p3 = {{trunc_ln59_fu_271_p1}, {8'd0}};

assign pf_1_fu_257_p3 = ((icmp_ln54_fu_251_p2[0:0] == 1'b1) ? 3'd6 : trunc_ln52_fu_247_p1);

assign pf_fu_239_p3 = ((tmp_4_fu_231_p3[0:0] == 1'b1) ? 31'd0 : trunc_ln29_fu_191_p1);

assign sub_ln59_fu_295_p2 = (p_shl_fu_275_p3 - p_shl3_fu_287_p3);

assign tmp_1_fu_307_p4 = {{total_cols_fu_301_p3[19:3]}};

assign tmp_2_fu_317_p3 = {{tmp_1_fu_307_p4}, {pf_1_reg_393}};

assign tmp_3_fu_215_p4 = {{ns_fu_207_p3[30:12]}};

assign tmp_4_fu_231_p3 = pf_cols[32'd31];

assign tmp_fu_199_p3 = n_slots[32'd31];

assign total_cols_fu_301_p3 = ((icmp_ln51_reg_388[0:0] == 1'b1) ? 20'd786240 : sub_ln59_reg_399);

assign trunc_ln29_1_fu_195_p1 = n_slots[30:0];

assign trunc_ln29_fu_191_p1 = pf_cols[30:0];

assign trunc_ln52_fu_247_p1 = pf_fu_239_p3[2:0];

assign trunc_ln56_fu_334_p1 = grp_fu_265_p2[9:0];

assign trunc_ln59_1_fu_283_p1 = ns_fu_207_p3[13:0];

assign trunc_ln59_fu_271_p1 = ns_fu_207_p3[11:0];

always @ (posedge ap_clk) begin
    sub_ln59_reg_399[5:0] <= 6'b000000;
    total_cols_reg_404[5:0] <= 6'b000000;
end

endmodule //pov_eta_rd
