-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pov_eta_rd is
generic (
    C_M_AXI_VOX_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_VOX_ID_WIDTH : INTEGER := 1;
    C_M_AXI_VOX_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_VOX_DATA_WIDTH : INTEGER := 64;
    C_M_AXI_VOX_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_VOX_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_VOX_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_VOX_BUSER_WIDTH : INTEGER := 1;
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 7;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_VOX_USER_VALUE : INTEGER := 0;
    C_M_AXI_VOX_PROT_VALUE : INTEGER := 0;
    C_M_AXI_VOX_CACHE_VALUE : INTEGER := 3 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_vox_AWVALID : OUT STD_LOGIC;
    m_axi_vox_AWREADY : IN STD_LOGIC;
    m_axi_vox_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_VOX_ADDR_WIDTH-1 downto 0);
    m_axi_vox_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_VOX_ID_WIDTH-1 downto 0);
    m_axi_vox_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_vox_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_vox_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_vox_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_vox_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_vox_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_vox_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_vox_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_vox_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_VOX_AWUSER_WIDTH-1 downto 0);
    m_axi_vox_WVALID : OUT STD_LOGIC;
    m_axi_vox_WREADY : IN STD_LOGIC;
    m_axi_vox_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_VOX_DATA_WIDTH-1 downto 0);
    m_axi_vox_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_VOX_DATA_WIDTH/8-1 downto 0);
    m_axi_vox_WLAST : OUT STD_LOGIC;
    m_axi_vox_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_VOX_ID_WIDTH-1 downto 0);
    m_axi_vox_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_VOX_WUSER_WIDTH-1 downto 0);
    m_axi_vox_ARVALID : OUT STD_LOGIC;
    m_axi_vox_ARREADY : IN STD_LOGIC;
    m_axi_vox_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_VOX_ADDR_WIDTH-1 downto 0);
    m_axi_vox_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_VOX_ID_WIDTH-1 downto 0);
    m_axi_vox_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_vox_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_vox_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_vox_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_vox_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_vox_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_vox_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_vox_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_vox_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_VOX_ARUSER_WIDTH-1 downto 0);
    m_axi_vox_RVALID : IN STD_LOGIC;
    m_axi_vox_RREADY : OUT STD_LOGIC;
    m_axi_vox_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_VOX_DATA_WIDTH-1 downto 0);
    m_axi_vox_RLAST : IN STD_LOGIC;
    m_axi_vox_RID : IN STD_LOGIC_VECTOR (C_M_AXI_VOX_ID_WIDTH-1 downto 0);
    m_axi_vox_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_VOX_RUSER_WIDTH-1 downto 0);
    m_axi_vox_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_vox_BVALID : IN STD_LOGIC;
    m_axi_vox_BREADY : OUT STD_LOGIC;
    m_axi_vox_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_vox_BID : IN STD_LOGIC_VECTOR (C_M_AXI_VOX_ID_WIDTH-1 downto 0);
    m_axi_vox_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_VOX_BUSER_WIDTH-1 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of pov_eta_rd is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "pov_eta_rd_pov_eta_rd,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-2,HLS_INPUT_CLOCK=6.670000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.869100,HLS_SYN_LAT=3131416,HLS_SYN_TPT=none,HLS_SYN_MEM=6,HLS_SYN_DSP=0,HLS_SYN_FF=3493,HLS_SYN_LUT=3304,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (38 downto 0) := "000000000001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (38 downto 0) := "000000000010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (38 downto 0) := "000000000100000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (38 downto 0) := "000000001000000000000000000000000000000";
    constant ap_ST_fsm_state32 : STD_LOGIC_VECTOR (38 downto 0) := "000000010000000000000000000000000000000";
    constant ap_ST_fsm_state33 : STD_LOGIC_VECTOR (38 downto 0) := "000000100000000000000000000000000000000";
    constant ap_ST_fsm_state34 : STD_LOGIC_VECTOR (38 downto 0) := "000001000000000000000000000000000000000";
    constant ap_ST_fsm_state35 : STD_LOGIC_VECTOR (38 downto 0) := "000010000000000000000000000000000000000";
    constant ap_ST_fsm_state36 : STD_LOGIC_VECTOR (38 downto 0) := "000100000000000000000000000000000000000";
    constant ap_ST_fsm_state37 : STD_LOGIC_VECTOR (38 downto 0) := "001000000000000000000000000000000000000";
    constant ap_ST_fsm_state38 : STD_LOGIC_VECTOR (38 downto 0) := "010000000000000000000000000000000000000";
    constant ap_ST_fsm_state39 : STD_LOGIC_VECTOR (38 downto 0) := "100000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant C_M_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv19_0 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    constant ap_const_lv31_6 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000110";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv32_25B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001011011";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv20_BFF40 : STD_LOGIC_VECTOR (19 downto 0) := "10111111111101000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv26_36 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000110110";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv10_25B : STD_LOGIC_VECTOR (9 downto 0) := "1001011011";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal voxel : STD_LOGIC_VECTOR (63 downto 0);
    signal phase : STD_LOGIC_VECTOR (31 downto 0);
    signal n_slots : STD_LOGIC_VECTOR (31 downto 0);
    signal axis_off_q8 : STD_LOGIC_VECTOR (31 downto 0);
    signal mirror_u : STD_LOGIC_VECTOR (31 downto 0);
    signal pf_cols : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_out_ap_vld : STD_LOGIC;
    signal mirror_u_read_reg_362 : STD_LOGIC_VECTOR (31 downto 0);
    signal axis_off_q8_read_reg_367 : STD_LOGIC_VECTOR (31 downto 0);
    signal voxel_read_reg_377 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln51_fu_225_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_reg_388 : STD_LOGIC_VECTOR (0 downto 0);
    signal pf_1_fu_257_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal pf_1_reg_393 : STD_LOGIC_VECTOR (2 downto 0);
    signal sub_ln59_fu_295_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal sub_ln59_reg_399 : STD_LOGIC_VECTOR (19 downto 0);
    signal total_cols_fu_301_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal total_cols_reg_404 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_CS_fsm_state33 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state33 : signal is "none";
    signal trunc_ln56_fu_334_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln56_reg_414 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state36 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state36 : signal is "none";
    signal tmp_5_reg_419 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln57_fu_346_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln57_reg_424 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_328_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln65_reg_429 : STD_LOGIC_VECTOR (25 downto 0);
    signal ang0_1_fu_352_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal ang0_1_reg_434 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state37 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state37 : signal is "none";
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_start : STD_LOGIC;
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_done : STD_LOGIC;
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_idle : STD_LOGIC;
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_ready : STD_LOGIC;
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWVALID : STD_LOGIC;
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WVALID : STD_LOGIC;
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WSTRB : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WLAST : STD_LOGIC;
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARVALID : STD_LOGIC;
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_RREADY : STD_LOGIC;
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_BREADY : STD_LOGIC;
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_acc_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_acc_out_ap_vld : STD_LOGIC;
    signal vox_0_AWREADY : STD_LOGIC;
    signal vox_0_WREADY : STD_LOGIC;
    signal vox_0_ARVALID : STD_LOGIC;
    signal vox_0_ARREADY : STD_LOGIC;
    signal vox_0_RVALID : STD_LOGIC;
    signal vox_0_RREADY : STD_LOGIC;
    signal vox_0_RDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal vox_0_RFIFONUM : STD_LOGIC_VECTOR (9 downto 0);
    signal vox_0_BVALID : STD_LOGIC;
    signal grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state38 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state38 : signal is "none";
    signal ap_CS_fsm_state39 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state39 : signal is "none";
    signal tmp_fu_199_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln29_1_fu_195_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal ns_fu_207_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_3_fu_215_p4 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_4_fu_231_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln29_fu_191_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal pf_fu_239_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln54_fu_251_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_fu_247_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_265_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln59_fu_271_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln59_1_fu_283_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_shl_fu_275_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_shl3_fu_287_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_1_fu_307_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_2_fu_317_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_fu_328_p0 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_fu_328_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_265_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_265_ap_start : STD_LOGIC;
    signal grp_fu_265_ap_done : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (38 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ST_fsm_state25_blk : STD_LOGIC;
    signal ap_ST_fsm_state26_blk : STD_LOGIC;
    signal ap_ST_fsm_state27_blk : STD_LOGIC;
    signal ap_ST_fsm_state28_blk : STD_LOGIC;
    signal ap_ST_fsm_state29_blk : STD_LOGIC;
    signal ap_ST_fsm_state30_blk : STD_LOGIC;
    signal ap_ST_fsm_state31_blk : STD_LOGIC;
    signal ap_ST_fsm_state32_blk : STD_LOGIC;
    signal ap_ST_fsm_state33_blk : STD_LOGIC;
    signal ap_ST_fsm_state34_blk : STD_LOGIC;
    signal ap_ST_fsm_state35_blk : STD_LOGIC;
    signal ap_ST_fsm_state36_blk : STD_LOGIC;
    signal ap_ST_fsm_state37_blk : STD_LOGIC;
    signal ap_ST_fsm_state38_blk : STD_LOGIC;
    signal ap_ST_fsm_state39_blk : STD_LOGIC;
    signal grp_fu_328_p00 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component pov_eta_rd_pov_eta_rd_Pipeline_FLAT IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_vox_0_AWVALID : OUT STD_LOGIC;
        m_axi_vox_0_AWREADY : IN STD_LOGIC;
        m_axi_vox_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_vox_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_vox_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_vox_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_vox_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_vox_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_vox_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_vox_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_vox_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_vox_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_vox_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_vox_0_WVALID : OUT STD_LOGIC;
        m_axi_vox_0_WREADY : IN STD_LOGIC;
        m_axi_vox_0_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_vox_0_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_vox_0_WLAST : OUT STD_LOGIC;
        m_axi_vox_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_vox_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_vox_0_ARVALID : OUT STD_LOGIC;
        m_axi_vox_0_ARREADY : IN STD_LOGIC;
        m_axi_vox_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_vox_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_vox_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_vox_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_vox_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_vox_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_vox_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_vox_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_vox_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_vox_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_vox_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_vox_0_RVALID : IN STD_LOGIC;
        m_axi_vox_0_RREADY : OUT STD_LOGIC;
        m_axi_vox_0_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        m_axi_vox_0_RLAST : IN STD_LOGIC;
        m_axi_vox_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_vox_0_RFIFONUM : IN STD_LOGIC_VECTOR (9 downto 0);
        m_axi_vox_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_vox_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_vox_0_BVALID : IN STD_LOGIC;
        m_axi_vox_0_BREADY : OUT STD_LOGIC;
        m_axi_vox_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_vox_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_vox_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        mul_ln65 : IN STD_LOGIC_VECTOR (25 downto 0);
        zext_ln52 : IN STD_LOGIC_VECTOR (2 downto 0);
        zext_ln59 : IN STD_LOGIC_VECTOR (19 downto 0);
        zext_ln56 : IN STD_LOGIC_VECTOR (9 downto 0);
        axis_off_q8 : IN STD_LOGIC_VECTOR (31 downto 0);
        voxel : IN STD_LOGIC_VECTOR (63 downto 0);
        mirror_u : IN STD_LOGIC_VECTOR (31 downto 0);
        acc_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        acc_out_ap_vld : OUT STD_LOGIC );
    end component;


    component pov_eta_rd_srem_32ns_11ns_32_36_seq_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        start : IN STD_LOGIC;
        done : OUT STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component pov_eta_rd_mul_20ns_7ns_26_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (19 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component pov_eta_rd_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        voxel : OUT STD_LOGIC_VECTOR (63 downto 0);
        phase : OUT STD_LOGIC_VECTOR (31 downto 0);
        n_slots : OUT STD_LOGIC_VECTOR (31 downto 0);
        axis_off_q8 : OUT STD_LOGIC_VECTOR (31 downto 0);
        mirror_u : OUT STD_LOGIC_VECTOR (31 downto 0);
        pf_cols : OUT STD_LOGIC_VECTOR (31 downto 0);
        xor_out : IN STD_LOGIC_VECTOR (63 downto 0);
        xor_out_ap_vld : IN STD_LOGIC );
    end component;


    component pov_eta_rd_vox_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (9 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;



begin
    grp_pov_eta_rd_Pipeline_FLAT_fu_173 : component pov_eta_rd_pov_eta_rd_Pipeline_FLAT
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_start,
        ap_done => grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_done,
        ap_idle => grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_idle,
        ap_ready => grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_ready,
        m_axi_vox_0_AWVALID => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWVALID,
        m_axi_vox_0_AWREADY => ap_const_logic_0,
        m_axi_vox_0_AWADDR => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWADDR,
        m_axi_vox_0_AWID => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWID,
        m_axi_vox_0_AWLEN => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWLEN,
        m_axi_vox_0_AWSIZE => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWSIZE,
        m_axi_vox_0_AWBURST => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWBURST,
        m_axi_vox_0_AWLOCK => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWLOCK,
        m_axi_vox_0_AWCACHE => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWCACHE,
        m_axi_vox_0_AWPROT => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWPROT,
        m_axi_vox_0_AWQOS => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWQOS,
        m_axi_vox_0_AWREGION => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWREGION,
        m_axi_vox_0_AWUSER => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_AWUSER,
        m_axi_vox_0_WVALID => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WVALID,
        m_axi_vox_0_WREADY => ap_const_logic_0,
        m_axi_vox_0_WDATA => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WDATA,
        m_axi_vox_0_WSTRB => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WSTRB,
        m_axi_vox_0_WLAST => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WLAST,
        m_axi_vox_0_WID => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WID,
        m_axi_vox_0_WUSER => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_WUSER,
        m_axi_vox_0_ARVALID => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARVALID,
        m_axi_vox_0_ARREADY => vox_0_ARREADY,
        m_axi_vox_0_ARADDR => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARADDR,
        m_axi_vox_0_ARID => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARID,
        m_axi_vox_0_ARLEN => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARLEN,
        m_axi_vox_0_ARSIZE => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARSIZE,
        m_axi_vox_0_ARBURST => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARBURST,
        m_axi_vox_0_ARLOCK => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARLOCK,
        m_axi_vox_0_ARCACHE => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARCACHE,
        m_axi_vox_0_ARPROT => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARPROT,
        m_axi_vox_0_ARQOS => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARQOS,
        m_axi_vox_0_ARREGION => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARREGION,
        m_axi_vox_0_ARUSER => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARUSER,
        m_axi_vox_0_RVALID => vox_0_RVALID,
        m_axi_vox_0_RREADY => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_RREADY,
        m_axi_vox_0_RDATA => vox_0_RDATA,
        m_axi_vox_0_RLAST => ap_const_logic_0,
        m_axi_vox_0_RID => ap_const_lv1_0,
        m_axi_vox_0_RFIFONUM => vox_0_RFIFONUM,
        m_axi_vox_0_RUSER => ap_const_lv1_0,
        m_axi_vox_0_RRESP => ap_const_lv2_0,
        m_axi_vox_0_BVALID => ap_const_logic_0,
        m_axi_vox_0_BREADY => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_BREADY,
        m_axi_vox_0_BRESP => ap_const_lv2_0,
        m_axi_vox_0_BID => ap_const_lv1_0,
        m_axi_vox_0_BUSER => ap_const_lv1_0,
        mul_ln65 => mul_ln65_reg_429,
        zext_ln52 => pf_1_reg_393,
        zext_ln59 => total_cols_reg_404,
        zext_ln56 => ang0_1_reg_434,
        axis_off_q8 => axis_off_q8_read_reg_367,
        voxel => voxel_read_reg_377,
        mirror_u => mirror_u_read_reg_362,
        acc_out => grp_pov_eta_rd_Pipeline_FLAT_fu_173_acc_out,
        acc_out_ap_vld => grp_pov_eta_rd_Pipeline_FLAT_fu_173_acc_out_ap_vld);

    control_s_axi_U : component pov_eta_rd_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        voxel => voxel,
        phase => phase,
        n_slots => n_slots,
        axis_off_q8 => axis_off_q8,
        mirror_u => mirror_u,
        pf_cols => pf_cols,
        xor_out => grp_pov_eta_rd_Pipeline_FLAT_fu_173_acc_out,
        xor_out_ap_vld => xor_out_ap_vld);

    vox_m_axi_U : component pov_eta_rd_vox_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 7,
        MAX_READ_BURST_LENGTH => 64,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_VOX_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_VOX_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_VOX_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_VOX_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_VOX_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_VOX_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_VOX_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_VOX_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_VOX_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_VOX_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_VOX_CACHE_VALUE,
        CH0_USER_RFIFONUM_WIDTH => 10,
        CH0_USER_DW => 64,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 8,
        NUM_WRITE_OUTSTANDING => 0)
    port map (
        AWVALID => m_axi_vox_AWVALID,
        AWREADY => m_axi_vox_AWREADY,
        AWADDR => m_axi_vox_AWADDR,
        AWID => m_axi_vox_AWID,
        AWLEN => m_axi_vox_AWLEN,
        AWSIZE => m_axi_vox_AWSIZE,
        AWBURST => m_axi_vox_AWBURST,
        AWLOCK => m_axi_vox_AWLOCK,
        AWCACHE => m_axi_vox_AWCACHE,
        AWPROT => m_axi_vox_AWPROT,
        AWQOS => m_axi_vox_AWQOS,
        AWREGION => m_axi_vox_AWREGION,
        AWUSER => m_axi_vox_AWUSER,
        WVALID => m_axi_vox_WVALID,
        WREADY => m_axi_vox_WREADY,
        WDATA => m_axi_vox_WDATA,
        WSTRB => m_axi_vox_WSTRB,
        WLAST => m_axi_vox_WLAST,
        WID => m_axi_vox_WID,
        WUSER => m_axi_vox_WUSER,
        ARVALID => m_axi_vox_ARVALID,
        ARREADY => m_axi_vox_ARREADY,
        ARADDR => m_axi_vox_ARADDR,
        ARID => m_axi_vox_ARID,
        ARLEN => m_axi_vox_ARLEN,
        ARSIZE => m_axi_vox_ARSIZE,
        ARBURST => m_axi_vox_ARBURST,
        ARLOCK => m_axi_vox_ARLOCK,
        ARCACHE => m_axi_vox_ARCACHE,
        ARPROT => m_axi_vox_ARPROT,
        ARQOS => m_axi_vox_ARQOS,
        ARREGION => m_axi_vox_ARREGION,
        ARUSER => m_axi_vox_ARUSER,
        RVALID => m_axi_vox_RVALID,
        RREADY => m_axi_vox_RREADY,
        RDATA => m_axi_vox_RDATA,
        RLAST => m_axi_vox_RLAST,
        RID => m_axi_vox_RID,
        RUSER => m_axi_vox_RUSER,
        RRESP => m_axi_vox_RRESP,
        BVALID => m_axi_vox_BVALID,
        BREADY => m_axi_vox_BREADY,
        BRESP => m_axi_vox_BRESP,
        BID => m_axi_vox_BID,
        BUSER => m_axi_vox_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => vox_0_ARVALID,
        I_CH0_ARREADY => vox_0_ARREADY,
        I_CH0_ARADDR => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARADDR,
        I_CH0_ARLEN => grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARLEN,
        I_CH0_RVALID => vox_0_RVALID,
        I_CH0_RREADY => vox_0_RREADY,
        I_CH0_RDATA => vox_0_RDATA,
        I_CH0_RFIFONUM => vox_0_RFIFONUM,
        I_CH0_AWVALID => ap_const_logic_0,
        I_CH0_AWREADY => vox_0_AWREADY,
        I_CH0_AWADDR => ap_const_lv64_0,
        I_CH0_AWLEN => ap_const_lv32_0,
        I_CH0_WVALID => ap_const_logic_0,
        I_CH0_WREADY => vox_0_WREADY,
        I_CH0_WDATA => ap_const_lv64_0,
        I_CH0_WSTRB => ap_const_lv8_0,
        I_CH0_BVALID => vox_0_BVALID,
        I_CH0_BREADY => ap_const_logic_0);

    srem_32ns_11ns_32_36_seq_1_U23 : component pov_eta_rd_srem_32ns_11ns_32_36_seq_1
    generic map (
        ID => 1,
        NUM_STAGE => 36,
        din0_WIDTH => 32,
        din1_WIDTH => 11,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        start => grp_fu_265_ap_start,
        done => grp_fu_265_ap_done,
        din0 => phase,
        din1 => grp_fu_265_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_265_p2);

    mul_20ns_7ns_26_4_1_U24 : component pov_eta_rd_mul_20ns_7ns_26_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 20,
        din1_WIDTH => 7,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_328_p0,
        din1 => grp_fu_328_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_328_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state37)) then 
                    grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_ready = ap_const_logic_1)) then 
                    grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state36)) then
                add_ln57_reg_424 <= add_ln57_fu_346_p2;
                mul_ln65_reg_429 <= grp_fu_328_p2;
                tmp_5_reg_419 <= grp_fu_265_p2(10 downto 10);
                trunc_ln56_reg_414 <= trunc_ln56_fu_334_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state37)) then
                ang0_1_reg_434 <= ang0_1_fu_352_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                axis_off_q8_read_reg_367 <= axis_off_q8;
                icmp_ln51_reg_388 <= icmp_ln51_fu_225_p2;
                mirror_u_read_reg_362 <= mirror_u;
                pf_1_reg_393 <= pf_1_fu_257_p3;
                    sub_ln59_reg_399(19 downto 6) <= sub_ln59_fu_295_p2(19 downto 6);
                voxel_read_reg_377 <= voxel;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state33)) then
                    total_cols_reg_404(19 downto 6) <= total_cols_fu_301_p3(19 downto 6);
            end if;
        end if;
    end process;
    sub_ln59_reg_399(5 downto 0) <= "000000";
    total_cols_reg_404(5 downto 0) <= "000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_done, ap_CS_fsm_state38)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state29;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state30;
            when ap_ST_fsm_state30 => 
                ap_NS_fsm <= ap_ST_fsm_state31;
            when ap_ST_fsm_state31 => 
                ap_NS_fsm <= ap_ST_fsm_state32;
            when ap_ST_fsm_state32 => 
                ap_NS_fsm <= ap_ST_fsm_state33;
            when ap_ST_fsm_state33 => 
                ap_NS_fsm <= ap_ST_fsm_state34;
            when ap_ST_fsm_state34 => 
                ap_NS_fsm <= ap_ST_fsm_state35;
            when ap_ST_fsm_state35 => 
                ap_NS_fsm <= ap_ST_fsm_state36;
            when ap_ST_fsm_state36 => 
                ap_NS_fsm <= ap_ST_fsm_state37;
            when ap_ST_fsm_state37 => 
                ap_NS_fsm <= ap_ST_fsm_state38;
            when ap_ST_fsm_state38 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state38) and (grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state39;
                else
                    ap_NS_fsm <= ap_ST_fsm_state38;
                end if;
            when ap_ST_fsm_state39 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln57_fu_346_p2 <= std_logic_vector(unsigned(trunc_ln56_fu_334_p1) + unsigned(ap_const_lv10_25B));
    ang0_1_fu_352_p3 <= 
        add_ln57_reg_424 when (tmp_5_reg_419(0) = '1') else 
        trunc_ln56_reg_414;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state33 <= ap_CS_fsm(32);
    ap_CS_fsm_state36 <= ap_CS_fsm(35);
    ap_CS_fsm_state37 <= ap_CS_fsm(36);
    ap_CS_fsm_state38 <= ap_CS_fsm(37);
    ap_CS_fsm_state39 <= ap_CS_fsm(38);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state24_blk <= ap_const_logic_0;
    ap_ST_fsm_state25_blk <= ap_const_logic_0;
    ap_ST_fsm_state26_blk <= ap_const_logic_0;
    ap_ST_fsm_state27_blk <= ap_const_logic_0;
    ap_ST_fsm_state28_blk <= ap_const_logic_0;
    ap_ST_fsm_state29_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state30_blk <= ap_const_logic_0;
    ap_ST_fsm_state31_blk <= ap_const_logic_0;
    ap_ST_fsm_state32_blk <= ap_const_logic_0;
    ap_ST_fsm_state33_blk <= ap_const_logic_0;
    ap_ST_fsm_state34_blk <= ap_const_logic_0;
    ap_ST_fsm_state35_blk <= ap_const_logic_0;
    ap_ST_fsm_state36_blk <= ap_const_logic_0;
    ap_ST_fsm_state37_blk <= ap_const_logic_0;

    ap_ST_fsm_state38_blk_assign_proc : process(grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_done)
    begin
        if ((grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state38_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state38_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state39_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state39)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state39)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state39)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state39)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    grp_fu_265_ap_start_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            grp_fu_265_ap_start <= ap_const_logic_1;
        else 
            grp_fu_265_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_265_p1 <= ap_const_lv32_25B(11 - 1 downto 0);
    grp_fu_328_p0 <= grp_fu_328_p00(20 - 1 downto 0);
    grp_fu_328_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_317_p3),26));
    grp_fu_328_p1 <= ap_const_lv26_36(7 - 1 downto 0);
    grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_start <= grp_pov_eta_rd_Pipeline_FLAT_fu_173_ap_start_reg;
    icmp_ln51_fu_225_p2 <= "0" when (tmp_3_fu_215_p4 = ap_const_lv19_0) else "1";
    icmp_ln54_fu_251_p2 <= "1" when (unsigned(pf_fu_239_p3) > unsigned(ap_const_lv31_6)) else "0";
    ns_fu_207_p3 <= 
        ap_const_lv31_0 when (tmp_fu_199_p3(0) = '1') else 
        trunc_ln29_1_fu_195_p1;
    p_shl3_fu_287_p3 <= (trunc_ln59_1_fu_283_p1 & ap_const_lv6_0);
    p_shl_fu_275_p3 <= (trunc_ln59_fu_271_p1 & ap_const_lv8_0);
    pf_1_fu_257_p3 <= 
        ap_const_lv3_6 when (icmp_ln54_fu_251_p2(0) = '1') else 
        trunc_ln52_fu_247_p1;
    pf_fu_239_p3 <= 
        ap_const_lv31_0 when (tmp_4_fu_231_p3(0) = '1') else 
        trunc_ln29_fu_191_p1;
    sub_ln59_fu_295_p2 <= std_logic_vector(unsigned(p_shl_fu_275_p3) - unsigned(p_shl3_fu_287_p3));
    tmp_1_fu_307_p4 <= total_cols_fu_301_p3(19 downto 3);
    tmp_2_fu_317_p3 <= (tmp_1_fu_307_p4 & pf_1_reg_393);
    tmp_3_fu_215_p4 <= ns_fu_207_p3(30 downto 12);
    tmp_4_fu_231_p3 <= pf_cols(31 downto 31);
    tmp_fu_199_p3 <= n_slots(31 downto 31);
    total_cols_fu_301_p3 <= 
        ap_const_lv20_BFF40 when (icmp_ln51_reg_388(0) = '1') else 
        sub_ln59_reg_399;
    trunc_ln29_1_fu_195_p1 <= n_slots(31 - 1 downto 0);
    trunc_ln29_fu_191_p1 <= pf_cols(31 - 1 downto 0);
    trunc_ln52_fu_247_p1 <= pf_fu_239_p3(3 - 1 downto 0);
    trunc_ln56_fu_334_p1 <= grp_fu_265_p2(10 - 1 downto 0);
    trunc_ln59_1_fu_283_p1 <= ns_fu_207_p3(14 - 1 downto 0);
    trunc_ln59_fu_271_p1 <= ns_fu_207_p3(12 - 1 downto 0);

    vox_0_ARVALID_assign_proc : process(ap_CS_fsm_state37, grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARVALID, ap_CS_fsm_state38)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state38) or (ap_const_logic_1 = ap_CS_fsm_state37))) then 
            vox_0_ARVALID <= grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_ARVALID;
        else 
            vox_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;


    vox_0_RREADY_assign_proc : process(ap_CS_fsm_state37, grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_RREADY, ap_CS_fsm_state38)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state38) or (ap_const_logic_1 = ap_CS_fsm_state37))) then 
            vox_0_RREADY <= grp_pov_eta_rd_Pipeline_FLAT_fu_173_m_axi_vox_0_RREADY;
        else 
            vox_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;


    xor_out_ap_vld_assign_proc : process(ap_CS_fsm_state39)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state39)) then 
            xor_out_ap_vld <= ap_const_logic_1;
        else 
            xor_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
