-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pov_eta_rd_pov_eta_rd_Pipeline_FLAT is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_vox_0_AWVALID : OUT STD_LOGIC;
    m_axi_vox_0_AWREADY : IN STD_LOGIC;
    m_axi_vox_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_vox_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_vox_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_vox_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_vox_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_vox_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_vox_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_vox_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_vox_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_vox_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_vox_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_vox_0_WVALID : OUT STD_LOGIC;
    m_axi_vox_0_WREADY : IN STD_LOGIC;
    m_axi_vox_0_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_vox_0_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_vox_0_WLAST : OUT STD_LOGIC;
    m_axi_vox_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_vox_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_vox_0_ARVALID : OUT STD_LOGIC;
    m_axi_vox_0_ARREADY : IN STD_LOGIC;
    m_axi_vox_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_vox_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_vox_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_vox_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_vox_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_vox_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_vox_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_vox_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_vox_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_vox_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_vox_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_vox_0_RVALID : IN STD_LOGIC;
    m_axi_vox_0_RREADY : OUT STD_LOGIC;
    m_axi_vox_0_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_vox_0_RLAST : IN STD_LOGIC;
    m_axi_vox_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_vox_0_RFIFONUM : IN STD_LOGIC_VECTOR (9 downto 0);
    m_axi_vox_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_vox_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_vox_0_BVALID : IN STD_LOGIC;
    m_axi_vox_0_BREADY : OUT STD_LOGIC;
    m_axi_vox_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_vox_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_vox_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    mul_ln65 : IN STD_LOGIC_VECTOR (25 downto 0);
    zext_ln52 : IN STD_LOGIC_VECTOR (2 downto 0);
    zext_ln59 : IN STD_LOGIC_VECTOR (19 downto 0);
    zext_ln56 : IN STD_LOGIC_VECTOR (9 downto 0);
    axis_off_q8 : IN STD_LOGIC_VECTOR (31 downto 0);
    voxel : IN STD_LOGIC_VECTOR (63 downto 0);
    mirror_u : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    acc_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of pov_eta_rd_pov_eta_rd_Pipeline_FLAT is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv64_36 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000110110";
    constant ap_const_lv53_0 : STD_LOGIC_VECTOR (52 downto 0) := "00000000000000000000000000000000000000000000000000000";
    constant ap_const_lv52_0 : STD_LOGIC_VECTOR (51 downto 0) := "0000000000000000000000000000000000000000000000000000";
    constant ap_const_lv26_0 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000000";
    constant ap_const_lv26_1 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000001";
    constant ap_const_lv52_4BDA130 : STD_LOGIC_VECTOR (51 downto 0) := "0000000000000000000000000100101111011010000100110000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_33 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110011";
    constant ap_const_lv26_36 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000110110";
    constant ap_const_lv53_6522C40 : STD_LOGIC_VECTOR (52 downto 0) := "00000000000000000000000000110010100100010110001000000";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv13_25A : STD_LOGIC_VECTOR (12 downto 0) := "0001001011010";
    constant ap_const_lv10_1A5 : STD_LOGIC_VECTOR (9 downto 0) := "0110100101";
    constant ap_const_lv21_1FFFA0 : STD_LOGIC_VECTOR (20 downto 0) := "111111111111110100000";
    constant ap_const_lv21_60 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000001100000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv25_80 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000010000000";
    constant ap_const_lv22_60 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000001100000";
    constant ap_const_lv22_C0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000011000000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv21_36 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000110110";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv29_80 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000010000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter21 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter22 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter23 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter24 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter25 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal and_ln72_reg_851 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln72_reg_851_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state17_io_grp1 : BOOLEAN;
    signal icmp_ln96_reg_866 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_reg_866_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state25_pp0_stage0_iter24_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln65_fu_315_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal PV2_COS8_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal PV2_COS8_q0 : STD_LOGIC_VECTOR (9 downto 0);
    signal PV2_SIN8_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal PV2_SIN8_q0 : STD_LOGIC_VECTOR (9 downto 0);
    signal vox_blk_n_AR : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal vox_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal zext_ln56_cast_fu_278_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln56_cast_reg_811 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln52_cast_fu_282_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal zext_ln52_cast_reg_816 : STD_LOGIC_VECTOR (20 downto 0);
    signal tobool_fu_286_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tobool_reg_821 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_2_reg_826 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_2_reg_826_pp0_iter1_reg : STD_LOGIC_VECTOR (25 downto 0);
    signal i_2_reg_826_pp0_iter2_reg : STD_LOGIC_VECTOR (25 downto 0);
    signal i_2_reg_826_pp0_iter3_reg : STD_LOGIC_VECTOR (25 downto 0);
    signal i_2_reg_826_pp0_iter4_reg : STD_LOGIC_VECTOR (25 downto 0);
    signal icmp_ln65_reg_831 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_831_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_831_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_831_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_831_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_831_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_831_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_831_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_831_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_831_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_831_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_831_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_831_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_831_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_831_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_831_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_831_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_831_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_831_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_831_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_831_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_831_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_831_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_831_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_341_p4 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_reg_835 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_reg_835_pp0_iter2_reg : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_reg_835_pp0_iter3_reg : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_reg_835_pp0_iter4_reg : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_fu_355_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln72_reg_846 : STD_LOGIC_VECTOR (25 downto 0);
    signal and_ln72_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln72_reg_851_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln72_reg_851_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln72_reg_851_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln72_reg_851_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln72_reg_851_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln72_reg_851_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln72_reg_851_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln72_reg_851_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln72_reg_851_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal px_fu_428_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal px_reg_855 : STD_LOGIC_VECTOR (20 downto 0);
    signal angle_1_fu_455_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal angle_1_reg_861 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln96_fu_463_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_reg_866_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_reg_866_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_reg_866_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_reg_866_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_reg_866_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_reg_866_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_reg_866_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_reg_866_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_reg_866_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_reg_866_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_reg_866_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_reg_866_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_reg_866_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_reg_866_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_reg_866_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_reg_866_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_reg_866_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln96_reg_866_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal u_2_fu_488_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal u_2_reg_880 : STD_LOGIC_VECTOR (20 downto 0);
    signal u_2_reg_880_pp0_iter7_reg : STD_LOGIC_VECTOR (20 downto 0);
    signal cs_reg_885 : STD_LOGIC_VECTOR (9 downto 0);
    signal sn_reg_891 : STD_LOGIC_VECTOR (9 downto 0);
    signal sn_reg_891_pp0_iter8_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln85_fu_503_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln85_reg_907 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln7_reg_923 : STD_LOGIC_VECTOR (23 downto 0);
    signal off_z_q8_reg_928 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln8_reg_933 : STD_LOGIC_VECTOR (20 downto 0);
    signal rx_fu_566_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal rx_reg_943 : STD_LOGIC_VECTOR (21 downto 0);
    signal rz_fu_585_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal rz_reg_949 : STD_LOGIC_VECTOR (21 downto 0);
    signal trunc_ln91_fu_591_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln91_reg_955 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln91_1_fu_595_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln91_1_reg_960 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln91_fu_681_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln91_reg_965 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln92_fu_690_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal mul_ln92_reg_970 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln_reg_975 : STD_LOGIC_VECTOR (60 downto 0);
    signal v_reg_985 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln78_fu_473_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln92_fu_722_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal phi_mul3_fu_166 : STD_LOGIC_VECTOR (52 downto 0) := "00000000000000000000000000000000000000000000000000000";
    signal add_ln72_fu_386_p2 : STD_LOGIC_VECTOR (52 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal phi_mul_fu_170 : STD_LOGIC_VECTOR (51 downto 0) := "0000000000000000000000000000000000000000000000000000";
    signal add_ln69_fu_335_p2 : STD_LOGIC_VECTOR (51 downto 0);
    signal i_fu_174 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000000";
    signal i_1_fu_321_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_sig_allocacmp_i_2 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal acc_fu_178 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal acc_1_fu_735_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter18_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter19_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter20_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter21_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter22_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter23_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter24_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_01001_grp0 : BOOLEAN;
    signal PV2_COS8_ce0_local : STD_LOGIC;
    signal PV2_SIN8_ce0_local : STD_LOGIC;
    signal grp_fu_355_p0 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_fu_355_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln72_fu_372_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln72_1_fu_376_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln5_fu_392_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_1_fu_410_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln74_fu_418_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal p_shl1_fu_402_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal sub_ln74_fu_422_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal zext_ln69_1_fu_369_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal angle_fu_434_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln75_fu_439_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln76_fu_443_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln76_fu_449_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal u_1_fu_483_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal u_fu_478_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal grp_fu_270_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_274_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_749_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln81_fu_532_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln85_fu_538_p2 : STD_LOGIC_VECTOR (28 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of sub_ln85_fu_538_p2 : signal is "no";
    signal sext_ln81_1_fu_535_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln86_fu_553_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln85_2_fu_563_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_fu_758_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln9_fu_572_p4 : STD_LOGIC_VECTOR (20 downto 0);
    signal sext_ln86_2_fu_581_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln91_fu_602_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_2_fu_610_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_fu_624_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln88_fu_618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln87_fu_629_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln87_fu_605_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal inside_fu_635_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln85_fu_599_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal vx_fu_641_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_shl_fu_653_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_shl2_fu_660_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln91_fu_667_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln91_fu_673_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln89_fu_649_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln92_fu_690_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln92_fu_690_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln_fu_696_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln92_1_fu_703_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln92_fu_707_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_749_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_758_p0 : STD_LOGIC_VECTOR (20 downto 0);
    signal grp_fu_270_ce : STD_LOGIC;
    signal grp_fu_274_ce : STD_LOGIC;
    signal grp_fu_355_ce : STD_LOGIC;
    signal grp_fu_749_ce : STD_LOGIC;
    signal grp_fu_758_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_355_p00 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln92_fu_690_p00 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component pov_eta_rd_mul_10s_32s_32_3_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (9 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component pov_eta_rd_mul_20ns_7ns_26_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (19 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component pov_eta_rd_mul_16ns_7ns_21_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        dout : OUT STD_LOGIC_VECTOR (20 downto 0) );
    end component;


    component pov_eta_rd_mac_muladd_21s_10s_8ns_29_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (20 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component pov_eta_rd_mac_muladd_21s_10s_25s_29_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (20 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        din2 : IN STD_LOGIC_VECTOR (24 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component pov_eta_rd_pov_eta_rd_Pipeline_FLAT_PV2_COS8_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component pov_eta_rd_pov_eta_rd_Pipeline_FLAT_PV2_SIN8_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component pov_eta_rd_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    PV2_COS8_U : component pov_eta_rd_pov_eta_rd_Pipeline_FLAT_PV2_COS8_ROM_AUTO_1R
    generic map (
        DataWidth => 10,
        AddressRange => 603,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => PV2_COS8_address0,
        ce0 => PV2_COS8_ce0_local,
        q0 => PV2_COS8_q0);

    PV2_SIN8_U : component pov_eta_rd_pov_eta_rd_Pipeline_FLAT_PV2_SIN8_ROM_AUTO_1R
    generic map (
        DataWidth => 10,
        AddressRange => 603,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => PV2_SIN8_address0,
        ce0 => PV2_SIN8_ce0_local,
        q0 => PV2_SIN8_q0);

    mul_10s_32s_32_3_1_U1 : component pov_eta_rd_mul_10s_32s_32_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 10,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sn_reg_891,
        din1 => axis_off_q8,
        ce => grp_fu_270_ce,
        dout => grp_fu_270_p2);

    mul_10s_32s_32_3_1_U2 : component pov_eta_rd_mul_10s_32s_32_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 10,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => cs_reg_885,
        din1 => axis_off_q8,
        ce => grp_fu_274_ce,
        dout => grp_fu_274_p2);

    mul_20ns_7ns_26_4_1_U3 : component pov_eta_rd_mul_20ns_7ns_26_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 20,
        din1_WIDTH => 7,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_355_p0,
        din1 => grp_fu_355_p1,
        ce => grp_fu_355_ce,
        dout => grp_fu_355_p2);

    mul_16ns_7ns_21_1_1_U4 : component pov_eta_rd_mul_16ns_7ns_21_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 7,
        dout_WIDTH => 21)
    port map (
        din0 => mul_ln92_fu_690_p0,
        din1 => mul_ln92_fu_690_p1,
        dout => mul_ln92_fu_690_p2);

    mac_muladd_21s_10s_8ns_29_4_1_U5 : component pov_eta_rd_mac_muladd_21s_10s_8ns_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 21,
        din1_WIDTH => 10,
        din2_WIDTH => 8,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => u_2_reg_880_pp0_iter7_reg,
        din1 => cs_reg_885,
        din2 => grp_fu_749_p2,
        ce => grp_fu_749_ce,
        dout => grp_fu_749_p3);

    mac_muladd_21s_10s_25s_29_4_1_U6 : component pov_eta_rd_mac_muladd_21s_10s_25s_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 21,
        din1_WIDTH => 10,
        din2_WIDTH => 25,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_758_p0,
        din1 => sn_reg_891_pp0_iter8_reg,
        din2 => add_ln86_fu_553_p2,
        ce => grp_fu_758_ce,
        dout => grp_fu_758_p3);

    flow_control_loop_pipe_sequential_init_U : component pov_eta_rd_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter24_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter21_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter21 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter22_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter22 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter23_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter23 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter24_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter24 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter25_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter25 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    acc_fu_178_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_fu_178 <= ap_const_lv64_0;
                elsif (((ap_enable_reg_pp0_iter25 = ap_const_logic_1) and (icmp_ln96_reg_866_pp0_iter24_reg = ap_const_lv1_0))) then 
                    acc_fu_178 <= acc_1_fu_735_p2;
                end if;
            end if; 
        end if;
    end process;

    i_fu_174_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln65_fu_315_p2 = ap_const_lv1_0))) then 
                    i_fu_174 <= i_1_fu_321_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_174 <= ap_const_lv26_0;
                end if;
            end if; 
        end if;
    end process;

    phi_mul3_fu_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    phi_mul3_fu_166 <= ap_const_lv53_0;
                elsif ((ap_enable_reg_pp0_iter5 = ap_const_logic_1)) then 
                    phi_mul3_fu_166 <= add_ln72_fu_386_p2;
                end if;
            end if; 
        end if;
    end process;

    phi_mul_fu_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    phi_mul_fu_170 <= ap_const_lv52_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    phi_mul_fu_170 <= add_ln69_fu_335_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                add_ln91_reg_965 <= add_ln91_fu_681_p2;
                and_ln72_reg_851 <= and_ln72_fu_380_p2;
                and_ln72_reg_851_pp0_iter10_reg <= and_ln72_reg_851_pp0_iter9_reg;
                and_ln72_reg_851_pp0_iter11_reg <= and_ln72_reg_851_pp0_iter10_reg;
                and_ln72_reg_851_pp0_iter12_reg <= and_ln72_reg_851_pp0_iter11_reg;
                and_ln72_reg_851_pp0_iter13_reg <= and_ln72_reg_851_pp0_iter12_reg;
                and_ln72_reg_851_pp0_iter14_reg <= and_ln72_reg_851_pp0_iter13_reg;
                and_ln72_reg_851_pp0_iter15_reg <= and_ln72_reg_851_pp0_iter14_reg;
                and_ln72_reg_851_pp0_iter6_reg <= and_ln72_reg_851;
                and_ln72_reg_851_pp0_iter7_reg <= and_ln72_reg_851_pp0_iter6_reg;
                and_ln72_reg_851_pp0_iter8_reg <= and_ln72_reg_851_pp0_iter7_reg;
                and_ln72_reg_851_pp0_iter9_reg <= and_ln72_reg_851_pp0_iter8_reg;
                angle_1_reg_861 <= angle_1_fu_455_p3;
                cs_reg_885 <= PV2_COS8_q0;
                icmp_ln96_reg_866 <= icmp_ln96_fu_463_p2;
                icmp_ln96_reg_866_pp0_iter10_reg <= icmp_ln96_reg_866_pp0_iter9_reg;
                icmp_ln96_reg_866_pp0_iter11_reg <= icmp_ln96_reg_866_pp0_iter10_reg;
                icmp_ln96_reg_866_pp0_iter12_reg <= icmp_ln96_reg_866_pp0_iter11_reg;
                icmp_ln96_reg_866_pp0_iter13_reg <= icmp_ln96_reg_866_pp0_iter12_reg;
                icmp_ln96_reg_866_pp0_iter14_reg <= icmp_ln96_reg_866_pp0_iter13_reg;
                icmp_ln96_reg_866_pp0_iter15_reg <= icmp_ln96_reg_866_pp0_iter14_reg;
                icmp_ln96_reg_866_pp0_iter16_reg <= icmp_ln96_reg_866_pp0_iter15_reg;
                icmp_ln96_reg_866_pp0_iter17_reg <= icmp_ln96_reg_866_pp0_iter16_reg;
                icmp_ln96_reg_866_pp0_iter18_reg <= icmp_ln96_reg_866_pp0_iter17_reg;
                icmp_ln96_reg_866_pp0_iter19_reg <= icmp_ln96_reg_866_pp0_iter18_reg;
                icmp_ln96_reg_866_pp0_iter20_reg <= icmp_ln96_reg_866_pp0_iter19_reg;
                icmp_ln96_reg_866_pp0_iter21_reg <= icmp_ln96_reg_866_pp0_iter20_reg;
                icmp_ln96_reg_866_pp0_iter22_reg <= icmp_ln96_reg_866_pp0_iter21_reg;
                icmp_ln96_reg_866_pp0_iter23_reg <= icmp_ln96_reg_866_pp0_iter22_reg;
                icmp_ln96_reg_866_pp0_iter24_reg <= icmp_ln96_reg_866_pp0_iter23_reg;
                icmp_ln96_reg_866_pp0_iter6_reg <= icmp_ln96_reg_866;
                icmp_ln96_reg_866_pp0_iter7_reg <= icmp_ln96_reg_866_pp0_iter6_reg;
                icmp_ln96_reg_866_pp0_iter8_reg <= icmp_ln96_reg_866_pp0_iter7_reg;
                icmp_ln96_reg_866_pp0_iter9_reg <= icmp_ln96_reg_866_pp0_iter8_reg;
                mul_ln72_reg_846 <= grp_fu_355_p2;
                mul_ln92_reg_970 <= mul_ln92_fu_690_p2;
                off_z_q8_reg_928 <= grp_fu_274_p2(31 downto 8);
                px_reg_855 <= px_fu_428_p2;
                rx_reg_943 <= rx_fu_566_p2;
                rz_reg_949 <= rz_fu_585_p2;
                sext_ln85_reg_907 <= sext_ln85_fu_503_p1;
                sn_reg_891 <= PV2_SIN8_q0;
                sn_reg_891_pp0_iter8_reg <= sn_reg_891;
                tmp_reg_835_pp0_iter2_reg <= tmp_reg_835;
                tmp_reg_835_pp0_iter3_reg <= tmp_reg_835_pp0_iter2_reg;
                tmp_reg_835_pp0_iter4_reg <= tmp_reg_835_pp0_iter3_reg;
                trunc_ln7_reg_923 <= grp_fu_270_p2(31 downto 8);
                trunc_ln8_reg_933 <= sub_ln85_fu_538_p2(28 downto 8);
                trunc_ln91_1_reg_960 <= trunc_ln91_1_fu_595_p1;
                trunc_ln91_reg_955 <= trunc_ln91_fu_591_p1;
                trunc_ln_reg_975 <= add_ln92_fu_707_p2(63 downto 3);
                u_2_reg_880 <= u_2_fu_488_p3;
                u_2_reg_880_pp0_iter7_reg <= u_2_reg_880;
                v_reg_985 <= m_axi_vox_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
                ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
                ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
                ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
                ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
                ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
                ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
                ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                i_2_reg_826_pp0_iter2_reg <= i_2_reg_826_pp0_iter1_reg;
                i_2_reg_826_pp0_iter3_reg <= i_2_reg_826_pp0_iter2_reg;
                i_2_reg_826_pp0_iter4_reg <= i_2_reg_826_pp0_iter3_reg;
                icmp_ln65_reg_831_pp0_iter10_reg <= icmp_ln65_reg_831_pp0_iter9_reg;
                icmp_ln65_reg_831_pp0_iter11_reg <= icmp_ln65_reg_831_pp0_iter10_reg;
                icmp_ln65_reg_831_pp0_iter12_reg <= icmp_ln65_reg_831_pp0_iter11_reg;
                icmp_ln65_reg_831_pp0_iter13_reg <= icmp_ln65_reg_831_pp0_iter12_reg;
                icmp_ln65_reg_831_pp0_iter14_reg <= icmp_ln65_reg_831_pp0_iter13_reg;
                icmp_ln65_reg_831_pp0_iter15_reg <= icmp_ln65_reg_831_pp0_iter14_reg;
                icmp_ln65_reg_831_pp0_iter16_reg <= icmp_ln65_reg_831_pp0_iter15_reg;
                icmp_ln65_reg_831_pp0_iter17_reg <= icmp_ln65_reg_831_pp0_iter16_reg;
                icmp_ln65_reg_831_pp0_iter18_reg <= icmp_ln65_reg_831_pp0_iter17_reg;
                icmp_ln65_reg_831_pp0_iter19_reg <= icmp_ln65_reg_831_pp0_iter18_reg;
                icmp_ln65_reg_831_pp0_iter20_reg <= icmp_ln65_reg_831_pp0_iter19_reg;
                icmp_ln65_reg_831_pp0_iter21_reg <= icmp_ln65_reg_831_pp0_iter20_reg;
                icmp_ln65_reg_831_pp0_iter22_reg <= icmp_ln65_reg_831_pp0_iter21_reg;
                icmp_ln65_reg_831_pp0_iter23_reg <= icmp_ln65_reg_831_pp0_iter22_reg;
                icmp_ln65_reg_831_pp0_iter2_reg <= icmp_ln65_reg_831_pp0_iter1_reg;
                icmp_ln65_reg_831_pp0_iter3_reg <= icmp_ln65_reg_831_pp0_iter2_reg;
                icmp_ln65_reg_831_pp0_iter4_reg <= icmp_ln65_reg_831_pp0_iter3_reg;
                icmp_ln65_reg_831_pp0_iter5_reg <= icmp_ln65_reg_831_pp0_iter4_reg;
                icmp_ln65_reg_831_pp0_iter6_reg <= icmp_ln65_reg_831_pp0_iter5_reg;
                icmp_ln65_reg_831_pp0_iter7_reg <= icmp_ln65_reg_831_pp0_iter6_reg;
                icmp_ln65_reg_831_pp0_iter8_reg <= icmp_ln65_reg_831_pp0_iter7_reg;
                icmp_ln65_reg_831_pp0_iter9_reg <= icmp_ln65_reg_831_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                i_2_reg_826 <= ap_sig_allocacmp_i_2;
                i_2_reg_826_pp0_iter1_reg <= i_2_reg_826;
                icmp_ln65_reg_831 <= icmp_ln65_fu_315_p2;
                icmp_ln65_reg_831_pp0_iter1_reg <= icmp_ln65_reg_831;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                tmp_reg_835 <= phi_mul_fu_170(51 downto 32);
                tobool_reg_821 <= tobool_fu_286_p2;
                    zext_ln52_cast_reg_816(2 downto 0) <= zext_ln52_cast_fu_282_p1(2 downto 0);
                    zext_ln56_cast_reg_811(9 downto 0) <= zext_ln56_cast_fu_278_p1(9 downto 0);
            end if;
        end if;
    end process;
    zext_ln56_cast_reg_811(12 downto 10) <= "000";
    zext_ln52_cast_reg_816(20 downto 3) <= "000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    PV2_COS8_address0 <= zext_ln78_fu_473_p1(10 - 1 downto 0);

    PV2_COS8_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            PV2_COS8_ce0_local <= ap_const_logic_1;
        else 
            PV2_COS8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    PV2_SIN8_address0 <= zext_ln78_fu_473_p1(10 - 1 downto 0);

    PV2_SIN8_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            PV2_SIN8_ce0_local <= ap_const_logic_1;
        else 
            PV2_SIN8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_1_fu_735_p2 <= (v_reg_985 xor acc_fu_178);
    acc_out <= acc_fu_178;

    acc_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, icmp_ln65_reg_831_pp0_iter23_reg, ap_loop_exit_ready_pp0_iter24_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter24_reg = ap_const_logic_1) and (icmp_ln65_reg_831_pp0_iter23_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            acc_out_ap_vld <= ap_const_logic_1;
        else 
            acc_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln69_fu_335_p2 <= std_logic_vector(unsigned(phi_mul_fu_170) + unsigned(ap_const_lv52_4BDA130));
    add_ln72_fu_386_p2 <= std_logic_vector(unsigned(phi_mul3_fu_166) + unsigned(ap_const_lv53_6522C40));
    add_ln76_fu_449_p2 <= std_logic_vector(unsigned(trunc_ln75_fu_439_p1) + unsigned(ap_const_lv10_1A5));
    add_ln86_fu_553_p2 <= std_logic_vector(signed(sext_ln81_1_fu_535_p1) + signed(ap_const_lv25_80));
    add_ln91_fu_681_p2 <= std_logic_vector(unsigned(select_ln91_fu_673_p3) + unsigned(zext_ln89_fu_649_p1));
    add_ln92_fu_707_p2 <= std_logic_vector(unsigned(zext_ln92_1_fu_703_p1) + unsigned(voxel));
    and_ln72_fu_380_p2 <= (icmp_ln72_fu_372_p2 and icmp_ln72_1_fu_376_p2);
    and_ln87_fu_629_p2 <= (xor_ln88_fu_618_p2 and icmp_ln88_fu_624_p2);
    angle_1_fu_455_p3 <= 
        add_ln76_fu_449_p2 when (icmp_ln76_fu_443_p2(0) = '1') else 
        trunc_ln75_fu_439_p1;
    angle_fu_434_p2 <= std_logic_vector(unsigned(trunc_ln5_fu_392_p4) + unsigned(zext_ln56_cast_reg_811));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter24, ap_block_state17_io_grp1, ap_block_state25_pp0_stage0_iter24_grp1)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter24 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state25_pp0_stage0_iter24_grp1)) or ((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state17_io_grp1)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter24, ap_block_state17_io_grp1, ap_block_state25_pp0_stage0_iter24_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((ap_enable_reg_pp0_iter24 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state25_pp0_stage0_iter24_grp1)) or ((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state17_io_grp1)));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter24, ap_block_state17_io_grp1, ap_block_state25_pp0_stage0_iter24_grp1)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter24 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state25_pp0_stage0_iter24_grp1)) or ((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state17_io_grp1)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state17_io_grp1_assign_proc : process(m_axi_vox_0_ARREADY, and_ln72_reg_851_pp0_iter15_reg)
    begin
                ap_block_state17_io_grp1 <= ((ap_const_lv1_1 = and_ln72_reg_851_pp0_iter15_reg) and (m_axi_vox_0_ARREADY = ap_const_logic_0));
    end process;


    ap_block_state25_pp0_stage0_iter24_grp1_assign_proc : process(m_axi_vox_0_RVALID, icmp_ln96_reg_866_pp0_iter23_reg)
    begin
                ap_block_state25_pp0_stage0_iter24_grp1 <= ((icmp_ln96_reg_866_pp0_iter23_reg = ap_const_lv1_0) and (m_axi_vox_0_RVALID = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln65_fu_315_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln65_fu_315_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter24_reg, ap_done_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter24_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23, ap_enable_reg_pp0_iter24, ap_enable_reg_pp0_iter25)
    begin
        if (((ap_enable_reg_pp0_iter25 = ap_const_logic_0) and (ap_enable_reg_pp0_iter24 = ap_const_logic_0) and (ap_enable_reg_pp0_iter23 = ap_const_logic_0) and (ap_enable_reg_pp0_iter22 = ap_const_logic_0) and (ap_enable_reg_pp0_iter21 = ap_const_logic_0) and (ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) 
    and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, i_fu_174, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_i_2 <= ap_const_lv26_0;
        else 
            ap_sig_allocacmp_i_2 <= i_fu_174;
        end if; 
    end process;


    grp_fu_270_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_270_ce <= ap_const_logic_1;
        else 
            grp_fu_270_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_274_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_274_ce <= ap_const_logic_1;
        else 
            grp_fu_274_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_355_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            grp_fu_355_ce <= ap_const_logic_1;
        else 
            grp_fu_355_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_355_p0 <= grp_fu_355_p00(20 - 1 downto 0);
    grp_fu_355_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_341_p4),26));
    grp_fu_355_p1 <= ap_const_lv26_36(7 - 1 downto 0);

    grp_fu_749_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_749_ce <= ap_const_logic_1;
        else 
            grp_fu_749_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_749_p2 <= ap_const_lv29_80(8 - 1 downto 0);

    grp_fu_758_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_758_ce <= ap_const_logic_1;
        else 
            grp_fu_758_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_758_p0 <= sext_ln85_reg_907(21 - 1 downto 0);
    i_1_fu_321_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_2) + unsigned(ap_const_lv26_1));
    icmp_ln65_fu_315_p2 <= "1" when (ap_sig_allocacmp_i_2 = mul_ln65) else "0";
    icmp_ln72_1_fu_376_p2 <= "1" when (unsigned(tmp_reg_835_pp0_iter4_reg) < unsigned(zext_ln59)) else "0";
    icmp_ln72_fu_372_p2 <= "1" when (i_2_reg_826_pp0_iter4_reg = mul_ln72_reg_846) else "0";
    icmp_ln76_fu_443_p2 <= "1" when (unsigned(angle_fu_434_p2) > unsigned(ap_const_lv13_25A)) else "0";
    icmp_ln87_fu_605_p2 <= "1" when (unsigned(rx_reg_943) < unsigned(ap_const_lv22_C0)) else "0";
    icmp_ln88_fu_624_p2 <= "1" when (signed(rz_reg_949) < signed(ap_const_lv22_C0)) else "0";
    icmp_ln96_fu_463_p2 <= "1" when (unsigned(zext_ln69_1_fu_369_p1) < unsigned(zext_ln52_cast_reg_816)) else "0";
    inside_fu_635_p2 <= (icmp_ln87_fu_605_p2 and and_ln87_fu_629_p2);
    m_axi_vox_0_ARADDR <= sext_ln92_fu_722_p1;
    m_axi_vox_0_ARBURST <= ap_const_lv2_0;
    m_axi_vox_0_ARCACHE <= ap_const_lv4_0;
    m_axi_vox_0_ARID <= ap_const_lv1_0;
    m_axi_vox_0_ARLEN <= ap_const_lv64_36(32 - 1 downto 0);
    m_axi_vox_0_ARLOCK <= ap_const_lv2_0;
    m_axi_vox_0_ARPROT <= ap_const_lv3_0;
    m_axi_vox_0_ARQOS <= ap_const_lv4_0;
    m_axi_vox_0_ARREGION <= ap_const_lv4_0;
    m_axi_vox_0_ARSIZE <= ap_const_lv3_0;
    m_axi_vox_0_ARUSER <= ap_const_lv1_0;

    m_axi_vox_0_ARVALID_assign_proc : process(ap_enable_reg_pp0_iter16, and_ln72_reg_851_pp0_iter15_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_1 = and_ln72_reg_851_pp0_iter15_reg))) then 
            m_axi_vox_0_ARVALID <= ap_const_logic_1;
        else 
            m_axi_vox_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_vox_0_AWADDR <= ap_const_lv64_0;
    m_axi_vox_0_AWBURST <= ap_const_lv2_0;
    m_axi_vox_0_AWCACHE <= ap_const_lv4_0;
    m_axi_vox_0_AWID <= ap_const_lv1_0;
    m_axi_vox_0_AWLEN <= ap_const_lv32_0;
    m_axi_vox_0_AWLOCK <= ap_const_lv2_0;
    m_axi_vox_0_AWPROT <= ap_const_lv3_0;
    m_axi_vox_0_AWQOS <= ap_const_lv4_0;
    m_axi_vox_0_AWREGION <= ap_const_lv4_0;
    m_axi_vox_0_AWSIZE <= ap_const_lv3_0;
    m_axi_vox_0_AWUSER <= ap_const_lv1_0;
    m_axi_vox_0_AWVALID <= ap_const_logic_0;
    m_axi_vox_0_BREADY <= ap_const_logic_0;

    m_axi_vox_0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter24, icmp_ln96_reg_866_pp0_iter23_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter24 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln96_reg_866_pp0_iter23_reg = ap_const_lv1_0))) then 
            m_axi_vox_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_vox_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_vox_0_WDATA <= ap_const_lv64_0;
    m_axi_vox_0_WID <= ap_const_lv1_0;
    m_axi_vox_0_WLAST <= ap_const_logic_0;
    m_axi_vox_0_WSTRB <= ap_const_lv8_0;
    m_axi_vox_0_WUSER <= ap_const_lv1_0;
    m_axi_vox_0_WVALID <= ap_const_logic_0;
    mul_ln92_fu_690_p0 <= mul_ln92_fu_690_p00(16 - 1 downto 0);
    mul_ln92_fu_690_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln91_reg_965),21));
    mul_ln92_fu_690_p1 <= ap_const_lv21_36(7 - 1 downto 0);
    p_shl1_fu_402_p3 <= (trunc_ln5_fu_392_p4 & ap_const_lv8_0);
    p_shl2_fu_660_p3 <= (trunc_ln91_1_reg_960 & ap_const_lv6_0);
    p_shl_fu_653_p3 <= (trunc_ln91_reg_955 & ap_const_lv8_0);
    px_fu_428_p2 <= std_logic_vector(unsigned(sub_ln74_fu_422_p2) + unsigned(zext_ln69_1_fu_369_p1));
    rx_fu_566_p2 <= std_logic_vector(signed(sext_ln85_2_fu_563_p1) + signed(ap_const_lv22_60));
    rz_fu_585_p2 <= std_logic_vector(signed(sext_ln86_2_fu_581_p1) + signed(ap_const_lv22_60));
    select_ln91_fu_673_p3 <= 
        sub_ln91_fu_667_p2 when (inside_fu_635_p2(0) = '1') else 
        ap_const_lv16_0;
        sext_ln81_1_fu_535_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(off_z_q8_reg_928),25));

        sext_ln81_fu_532_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln7_reg_923),29));

        sext_ln85_2_fu_563_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln8_reg_933),22));

        sext_ln85_fu_503_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(u_2_reg_880_pp0_iter7_reg),29));

        sext_ln86_2_fu_581_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln9_fu_572_p4),22));

        sext_ln91_fu_602_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rz_reg_949),25));

        sext_ln92_fu_722_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_reg_975),64));

    shl_ln_fu_696_p3 <= (mul_ln92_reg_970 & ap_const_lv3_0);
    sub_ln74_fu_422_p2 <= std_logic_vector(unsigned(zext_ln74_fu_418_p1) - unsigned(p_shl1_fu_402_p3));
    sub_ln85_fu_538_p2 <= std_logic_vector(signed(grp_fu_749_p3) - signed(sext_ln81_fu_532_p1));
    sub_ln91_fu_667_p2 <= std_logic_vector(unsigned(p_shl_fu_653_p3) - unsigned(p_shl2_fu_660_p3));
    tmp_1_fu_410_p3 <= (trunc_ln5_fu_392_p4 & ap_const_lv6_0);
    tmp_2_fu_610_p3 <= sext_ln91_fu_602_p1(24 downto 24);
    tmp_fu_341_p4 <= phi_mul_fu_170(51 downto 32);
    tobool_fu_286_p2 <= "0" when (mirror_u = ap_const_lv32_0) else "1";
    trunc_ln5_fu_392_p4 <= phi_mul3_fu_166(52 downto 40);
    trunc_ln75_fu_439_p1 <= angle_fu_434_p2(10 - 1 downto 0);
    trunc_ln85_fu_599_p1 <= rx_reg_943(8 - 1 downto 0);
    trunc_ln91_1_fu_595_p1 <= rz_fu_585_p2(10 - 1 downto 0);
    trunc_ln91_fu_591_p1 <= rz_fu_585_p2(8 - 1 downto 0);
    trunc_ln9_fu_572_p4 <= grp_fu_758_p3(28 downto 8);
    u_1_fu_483_p2 <= std_logic_vector(unsigned(ap_const_lv21_60) - unsigned(px_reg_855));
    u_2_fu_488_p3 <= 
        u_1_fu_483_p2 when (tobool_reg_821(0) = '1') else 
        u_fu_478_p2;
    u_fu_478_p2 <= std_logic_vector(unsigned(px_reg_855) + unsigned(ap_const_lv21_1FFFA0));

    vox_blk_n_AR_assign_proc : process(ap_enable_reg_pp0_iter16, m_axi_vox_0_ARREADY, and_ln72_reg_851_pp0_iter15_reg, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_const_lv1_1 = and_ln72_reg_851_pp0_iter15_reg))) then 
            vox_blk_n_AR <= m_axi_vox_0_ARREADY;
        else 
            vox_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    vox_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter24, m_axi_vox_0_RVALID, icmp_ln96_reg_866_pp0_iter23_reg, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter24 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln96_reg_866_pp0_iter23_reg = ap_const_lv1_0))) then 
            vox_blk_n_R <= m_axi_vox_0_RVALID;
        else 
            vox_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    vx_fu_641_p3 <= 
        trunc_ln85_fu_599_p1 when (inside_fu_635_p2(0) = '1') else 
        ap_const_lv8_0;
    xor_ln88_fu_618_p2 <= (tmp_2_fu_610_p3 xor ap_const_lv1_1);
    zext_ln52_cast_fu_282_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln52),21));
    zext_ln56_cast_fu_278_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln56),13));
    zext_ln69_1_fu_369_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_reg_835_pp0_iter4_reg),21));
    zext_ln74_fu_418_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_410_p3),21));
    zext_ln78_fu_473_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(angle_1_reg_861),64));
    zext_ln89_fu_649_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(vx_fu_641_p3),16));
    zext_ln92_1_fu_703_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_696_p3),64));
end behav;
