// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pov_eta_rd_pov_eta_rd_Pipeline_FLAT (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_vox_0_AWVALID,
        m_axi_vox_0_AWREADY,
        m_axi_vox_0_AWADDR,
        m_axi_vox_0_AWID,
        m_axi_vox_0_AWLEN,
        m_axi_vox_0_AWSIZE,
        m_axi_vox_0_AWBURST,
        m_axi_vox_0_AWLOCK,
        m_axi_vox_0_AWCACHE,
        m_axi_vox_0_AWPROT,
        m_axi_vox_0_AWQOS,
        m_axi_vox_0_AWREGION,
        m_axi_vox_0_AWUSER,
        m_axi_vox_0_WVALID,
        m_axi_vox_0_WREADY,
        m_axi_vox_0_WDATA,
        m_axi_vox_0_WSTRB,
        m_axi_vox_0_WLAST,
        m_axi_vox_0_WID,
        m_axi_vox_0_WUSER,
        m_axi_vox_0_ARVALID,
        m_axi_vox_0_ARREADY,
        m_axi_vox_0_ARADDR,
        m_axi_vox_0_ARID,
        m_axi_vox_0_ARLEN,
        m_axi_vox_0_ARSIZE,
        m_axi_vox_0_ARBURST,
        m_axi_vox_0_ARLOCK,
        m_axi_vox_0_ARCACHE,
        m_axi_vox_0_ARPROT,
        m_axi_vox_0_ARQOS,
        m_axi_vox_0_ARREGION,
        m_axi_vox_0_ARUSER,
        m_axi_vox_0_RVALID,
        m_axi_vox_0_RREADY,
        m_axi_vox_0_RDATA,
        m_axi_vox_0_RLAST,
        m_axi_vox_0_RID,
        m_axi_vox_0_RFIFONUM,
        m_axi_vox_0_RUSER,
        m_axi_vox_0_RRESP,
        m_axi_vox_0_BVALID,
        m_axi_vox_0_BREADY,
        m_axi_vox_0_BRESP,
        m_axi_vox_0_BID,
        m_axi_vox_0_BUSER,
        mul_ln65,
        zext_ln52,
        zext_ln59,
        zext_ln56,
        axis_off_q8,
        voxel,
        mirror_u,
        acc_out,
        acc_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_vox_0_AWVALID;
input   m_axi_vox_0_AWREADY;
output  [63:0] m_axi_vox_0_AWADDR;
output  [0:0] m_axi_vox_0_AWID;
output  [31:0] m_axi_vox_0_AWLEN;
output  [2:0] m_axi_vox_0_AWSIZE;
output  [1:0] m_axi_vox_0_AWBURST;
output  [1:0] m_axi_vox_0_AWLOCK;
output  [3:0] m_axi_vox_0_AWCACHE;
output  [2:0] m_axi_vox_0_AWPROT;
output  [3:0] m_axi_vox_0_AWQOS;
output  [3:0] m_axi_vox_0_AWREGION;
output  [0:0] m_axi_vox_0_AWUSER;
output   m_axi_vox_0_WVALID;
input   m_axi_vox_0_WREADY;
output  [63:0] m_axi_vox_0_WDATA;
output  [7:0] m_axi_vox_0_WSTRB;
output   m_axi_vox_0_WLAST;
output  [0:0] m_axi_vox_0_WID;
output  [0:0] m_axi_vox_0_WUSER;
output   m_axi_vox_0_ARVALID;
input   m_axi_vox_0_ARREADY;
output  [63:0] m_axi_vox_0_ARADDR;
output  [0:0] m_axi_vox_0_ARID;
output  [31:0] m_axi_vox_0_ARLEN;
output  [2:0] m_axi_vox_0_ARSIZE;
output  [1:0] m_axi_vox_0_ARBURST;
output  [1:0] m_axi_vox_0_ARLOCK;
output  [3:0] m_axi_vox_0_ARCACHE;
output  [2:0] m_axi_vox_0_ARPROT;
output  [3:0] m_axi_vox_0_ARQOS;
output  [3:0] m_axi_vox_0_ARREGION;
output  [0:0] m_axi_vox_0_ARUSER;
input   m_axi_vox_0_RVALID;
output   m_axi_vox_0_RREADY;
input  [63:0] m_axi_vox_0_RDATA;
input   m_axi_vox_0_RLAST;
input  [0:0] m_axi_vox_0_RID;
input  [9:0] m_axi_vox_0_RFIFONUM;
input  [0:0] m_axi_vox_0_RUSER;
input  [1:0] m_axi_vox_0_RRESP;
input   m_axi_vox_0_BVALID;
output   m_axi_vox_0_BREADY;
input  [1:0] m_axi_vox_0_BRESP;
input  [0:0] m_axi_vox_0_BID;
input  [0:0] m_axi_vox_0_BUSER;
input  [25:0] mul_ln65;
input  [2:0] zext_ln52;
input  [19:0] zext_ln59;
input  [9:0] zext_ln56;
input  [31:0] axis_off_q8;
input  [63:0] voxel;
input  [31:0] mirror_u;
output  [63:0] acc_out;
output   acc_out_ap_vld;

reg ap_idle;
reg m_axi_vox_0_ARVALID;
reg m_axi_vox_0_RREADY;
reg acc_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_idle_pp0;
reg   [0:0] and_ln72_reg_851;
reg   [0:0] and_ln72_reg_851_pp0_iter15_reg;
reg    ap_block_state17_io_grp1;
reg   [0:0] icmp_ln96_reg_866;
reg   [0:0] icmp_ln96_reg_866_pp0_iter23_reg;
reg    ap_block_state25_pp0_stage0_iter24_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln65_fu_315_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [9:0] PV2_COS8_address0;
wire   [9:0] PV2_COS8_q0;
wire   [9:0] PV2_SIN8_address0;
wire   [9:0] PV2_SIN8_q0;
reg    vox_blk_n_AR;
wire    ap_block_pp0_stage0_grp1;
reg    vox_blk_n_R;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [12:0] zext_ln56_cast_fu_278_p1;
reg   [12:0] zext_ln56_cast_reg_811;
wire   [20:0] zext_ln52_cast_fu_282_p1;
reg   [20:0] zext_ln52_cast_reg_816;
wire   [0:0] tobool_fu_286_p2;
reg   [0:0] tobool_reg_821;
reg   [25:0] i_2_reg_826;
reg    ap_block_pp0_stage0_11001;
reg   [25:0] i_2_reg_826_pp0_iter1_reg;
reg   [25:0] i_2_reg_826_pp0_iter2_reg;
reg   [25:0] i_2_reg_826_pp0_iter3_reg;
reg   [25:0] i_2_reg_826_pp0_iter4_reg;
reg   [0:0] icmp_ln65_reg_831;
reg   [0:0] icmp_ln65_reg_831_pp0_iter1_reg;
reg   [0:0] icmp_ln65_reg_831_pp0_iter2_reg;
reg   [0:0] icmp_ln65_reg_831_pp0_iter3_reg;
reg   [0:0] icmp_ln65_reg_831_pp0_iter4_reg;
reg   [0:0] icmp_ln65_reg_831_pp0_iter5_reg;
reg   [0:0] icmp_ln65_reg_831_pp0_iter6_reg;
reg   [0:0] icmp_ln65_reg_831_pp0_iter7_reg;
reg   [0:0] icmp_ln65_reg_831_pp0_iter8_reg;
reg   [0:0] icmp_ln65_reg_831_pp0_iter9_reg;
reg   [0:0] icmp_ln65_reg_831_pp0_iter10_reg;
reg   [0:0] icmp_ln65_reg_831_pp0_iter11_reg;
reg   [0:0] icmp_ln65_reg_831_pp0_iter12_reg;
reg   [0:0] icmp_ln65_reg_831_pp0_iter13_reg;
reg   [0:0] icmp_ln65_reg_831_pp0_iter14_reg;
reg   [0:0] icmp_ln65_reg_831_pp0_iter15_reg;
reg   [0:0] icmp_ln65_reg_831_pp0_iter16_reg;
reg   [0:0] icmp_ln65_reg_831_pp0_iter17_reg;
reg   [0:0] icmp_ln65_reg_831_pp0_iter18_reg;
reg   [0:0] icmp_ln65_reg_831_pp0_iter19_reg;
reg   [0:0] icmp_ln65_reg_831_pp0_iter20_reg;
reg   [0:0] icmp_ln65_reg_831_pp0_iter21_reg;
reg   [0:0] icmp_ln65_reg_831_pp0_iter22_reg;
reg   [0:0] icmp_ln65_reg_831_pp0_iter23_reg;
wire   [19:0] tmp_fu_341_p4;
reg   [19:0] tmp_reg_835;
reg   [19:0] tmp_reg_835_pp0_iter2_reg;
reg   [19:0] tmp_reg_835_pp0_iter3_reg;
reg   [19:0] tmp_reg_835_pp0_iter4_reg;
wire   [25:0] grp_fu_355_p2;
reg   [25:0] mul_ln72_reg_846;
wire   [0:0] and_ln72_fu_380_p2;
reg   [0:0] and_ln72_reg_851_pp0_iter6_reg;
reg   [0:0] and_ln72_reg_851_pp0_iter7_reg;
reg   [0:0] and_ln72_reg_851_pp0_iter8_reg;
reg   [0:0] and_ln72_reg_851_pp0_iter9_reg;
reg   [0:0] and_ln72_reg_851_pp0_iter10_reg;
reg   [0:0] and_ln72_reg_851_pp0_iter11_reg;
reg   [0:0] and_ln72_reg_851_pp0_iter12_reg;
reg   [0:0] and_ln72_reg_851_pp0_iter13_reg;
reg   [0:0] and_ln72_reg_851_pp0_iter14_reg;
wire   [20:0] px_fu_428_p2;
reg   [20:0] px_reg_855;
wire   [9:0] angle_1_fu_455_p3;
reg   [9:0] angle_1_reg_861;
wire   [0:0] icmp_ln96_fu_463_p2;
reg   [0:0] icmp_ln96_reg_866_pp0_iter6_reg;
reg   [0:0] icmp_ln96_reg_866_pp0_iter7_reg;
reg   [0:0] icmp_ln96_reg_866_pp0_iter8_reg;
reg   [0:0] icmp_ln96_reg_866_pp0_iter9_reg;
reg   [0:0] icmp_ln96_reg_866_pp0_iter10_reg;
reg   [0:0] icmp_ln96_reg_866_pp0_iter11_reg;
reg   [0:0] icmp_ln96_reg_866_pp0_iter12_reg;
reg   [0:0] icmp_ln96_reg_866_pp0_iter13_reg;
reg   [0:0] icmp_ln96_reg_866_pp0_iter14_reg;
reg   [0:0] icmp_ln96_reg_866_pp0_iter15_reg;
reg   [0:0] icmp_ln96_reg_866_pp0_iter16_reg;
reg   [0:0] icmp_ln96_reg_866_pp0_iter17_reg;
reg   [0:0] icmp_ln96_reg_866_pp0_iter18_reg;
reg   [0:0] icmp_ln96_reg_866_pp0_iter19_reg;
reg   [0:0] icmp_ln96_reg_866_pp0_iter20_reg;
reg   [0:0] icmp_ln96_reg_866_pp0_iter21_reg;
reg   [0:0] icmp_ln96_reg_866_pp0_iter22_reg;
reg   [0:0] icmp_ln96_reg_866_pp0_iter24_reg;
wire   [20:0] u_2_fu_488_p3;
reg   [20:0] u_2_reg_880;
reg  signed [20:0] u_2_reg_880_pp0_iter7_reg;
reg  signed [9:0] cs_reg_885;
reg  signed [9:0] sn_reg_891;
reg  signed [9:0] sn_reg_891_pp0_iter8_reg;
wire  signed [28:0] sext_ln85_fu_503_p1;
reg  signed [28:0] sext_ln85_reg_907;
reg   [23:0] trunc_ln7_reg_923;
reg   [23:0] off_z_q8_reg_928;
reg   [20:0] trunc_ln8_reg_933;
wire   [21:0] rx_fu_566_p2;
reg   [21:0] rx_reg_943;
wire  signed [21:0] rz_fu_585_p2;
reg  signed [21:0] rz_reg_949;
wire   [7:0] trunc_ln91_fu_591_p1;
reg   [7:0] trunc_ln91_reg_955;
wire   [9:0] trunc_ln91_1_fu_595_p1;
reg   [9:0] trunc_ln91_1_reg_960;
wire   [15:0] add_ln91_fu_681_p2;
reg   [15:0] add_ln91_reg_965;
wire   [20:0] mul_ln92_fu_690_p2;
reg   [20:0] mul_ln92_reg_970;
reg   [60:0] trunc_ln_reg_975;
reg   [63:0] v_reg_985;
wire   [63:0] zext_ln78_fu_473_p1;
wire  signed [63:0] sext_ln92_fu_722_p1;
reg   [52:0] phi_mul3_fu_166;
wire   [52:0] add_ln72_fu_386_p2;
wire    ap_loop_init;
reg   [51:0] phi_mul_fu_170;
wire   [51:0] add_ln69_fu_335_p2;
reg   [25:0] i_fu_174;
wire   [25:0] i_1_fu_321_p2;
reg   [25:0] ap_sig_allocacmp_i_2;
wire    ap_block_pp0_stage0;
reg   [63:0] acc_fu_178;
wire   [63:0] acc_1_fu_735_p2;
wire    ap_block_pp0_stage0_grp0;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
wire    ap_block_pp0_stage0_01001_grp0;
reg    PV2_COS8_ce0_local;
reg    PV2_SIN8_ce0_local;
wire   [19:0] grp_fu_355_p0;
wire   [6:0] grp_fu_355_p1;
wire   [0:0] icmp_ln72_fu_372_p2;
wire   [0:0] icmp_ln72_1_fu_376_p2;
wire   [12:0] trunc_ln5_fu_392_p4;
wire   [18:0] tmp_1_fu_410_p3;
wire   [20:0] zext_ln74_fu_418_p1;
wire   [20:0] p_shl1_fu_402_p3;
wire   [20:0] sub_ln74_fu_422_p2;
wire   [20:0] zext_ln69_1_fu_369_p1;
wire   [12:0] angle_fu_434_p2;
wire   [9:0] trunc_ln75_fu_439_p1;
wire   [0:0] icmp_ln76_fu_443_p2;
wire   [9:0] add_ln76_fu_449_p2;
wire   [20:0] u_1_fu_483_p2;
wire   [20:0] u_fu_478_p2;
wire   [31:0] grp_fu_270_p2;
wire   [31:0] grp_fu_274_p2;
wire  signed [28:0] grp_fu_749_p3;
wire  signed [28:0] sext_ln81_fu_532_p1;
(* use_dsp48 = "no" *) wire   [28:0] sub_ln85_fu_538_p2;
wire  signed [24:0] sext_ln81_1_fu_535_p1;
wire  signed [24:0] add_ln86_fu_553_p2;
wire  signed [21:0] sext_ln85_2_fu_563_p1;
wire  signed [28:0] grp_fu_758_p3;
wire   [20:0] trunc_ln9_fu_572_p4;
wire  signed [21:0] sext_ln86_2_fu_581_p1;
wire  signed [24:0] sext_ln91_fu_602_p1;
wire   [0:0] tmp_2_fu_610_p3;
wire   [0:0] icmp_ln88_fu_624_p2;
wire   [0:0] xor_ln88_fu_618_p2;
wire   [0:0] and_ln87_fu_629_p2;
wire   [0:0] icmp_ln87_fu_605_p2;
wire   [0:0] inside_fu_635_p2;
wire   [7:0] trunc_ln85_fu_599_p1;
wire   [7:0] vx_fu_641_p3;
wire   [15:0] p_shl_fu_653_p3;
wire   [15:0] p_shl2_fu_660_p3;
wire   [15:0] sub_ln91_fu_667_p2;
wire   [15:0] select_ln91_fu_673_p3;
wire   [15:0] zext_ln89_fu_649_p1;
wire   [15:0] mul_ln92_fu_690_p0;
wire   [6:0] mul_ln92_fu_690_p1;
wire   [23:0] shl_ln_fu_696_p3;
wire   [63:0] zext_ln92_1_fu_703_p1;
wire   [63:0] add_ln92_fu_707_p2;
wire   [7:0] grp_fu_749_p2;
wire  signed [20:0] grp_fu_758_p0;
reg    grp_fu_270_ce;
reg    grp_fu_274_ce;
reg    grp_fu_355_ce;
reg    grp_fu_749_ce;
reg    grp_fu_758_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [25:0] grp_fu_355_p00;
wire   [20:0] mul_ln92_fu_690_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 phi_mul3_fu_166 = 53'd0;
#0 phi_mul_fu_170 = 52'd0;
#0 i_fu_174 = 26'd0;
#0 acc_fu_178 = 64'd0;
#0 ap_done_reg = 1'b0;
end

pov_eta_rd_pov_eta_rd_Pipeline_FLAT_PV2_COS8_ROM_AUTO_1R #(
    .DataWidth( 10 ),
    .AddressRange( 603 ),
    .AddressWidth( 10 ))
PV2_COS8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(PV2_COS8_address0),
    .ce0(PV2_COS8_ce0_local),
    .q0(PV2_COS8_q0)
);

pov_eta_rd_pov_eta_rd_Pipeline_FLAT_PV2_SIN8_ROM_AUTO_1R #(
    .DataWidth( 10 ),
    .AddressRange( 603 ),
    .AddressWidth( 10 ))
PV2_SIN8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(PV2_SIN8_address0),
    .ce0(PV2_SIN8_ce0_local),
    .q0(PV2_SIN8_q0)
);

pov_eta_rd_mul_10s_32s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_10s_32s_32_3_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sn_reg_891),
    .din1(axis_off_q8),
    .ce(grp_fu_270_ce),
    .dout(grp_fu_270_p2)
);

pov_eta_rd_mul_10s_32s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_10s_32s_32_3_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(cs_reg_885),
    .din1(axis_off_q8),
    .ce(grp_fu_274_ce),
    .dout(grp_fu_274_p2)
);

pov_eta_rd_mul_20ns_7ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 26 ))
mul_20ns_7ns_26_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_355_p0),
    .din1(grp_fu_355_p1),
    .ce(grp_fu_355_ce),
    .dout(grp_fu_355_p2)
);

pov_eta_rd_mul_16ns_7ns_21_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 21 ))
mul_16ns_7ns_21_1_1_U4(
    .din0(mul_ln92_fu_690_p0),
    .din1(mul_ln92_fu_690_p1),
    .dout(mul_ln92_fu_690_p2)
);

pov_eta_rd_mac_muladd_21s_10s_8ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 29 ))
mac_muladd_21s_10s_8ns_29_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(u_2_reg_880_pp0_iter7_reg),
    .din1(cs_reg_885),
    .din2(grp_fu_749_p2),
    .ce(grp_fu_749_ce),
    .dout(grp_fu_749_p3)
);

pov_eta_rd_mac_muladd_21s_10s_25s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 25 ),
    .dout_WIDTH( 29 ))
mac_muladd_21s_10s_25s_29_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_758_p0),
    .din1(sn_reg_891_pp0_iter8_reg),
    .din2(add_ln86_fu_553_p2),
    .ce(grp_fu_758_ce),
    .dout(grp_fu_758_p3)
);

pov_eta_rd_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter24_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_fu_178 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter25 == 1'b1) & (icmp_ln96_reg_866_pp0_iter24_reg == 1'd0))) begin
            acc_fu_178 <= acc_1_fu_735_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln65_fu_315_p2 == 1'd0))) begin
            i_fu_174 <= i_1_fu_321_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_174 <= 26'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            phi_mul3_fu_166 <= 53'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            phi_mul3_fu_166 <= add_ln72_fu_386_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            phi_mul_fu_170 <= 52'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            phi_mul_fu_170 <= add_ln69_fu_335_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        add_ln91_reg_965 <= add_ln91_fu_681_p2;
        and_ln72_reg_851 <= and_ln72_fu_380_p2;
        and_ln72_reg_851_pp0_iter10_reg <= and_ln72_reg_851_pp0_iter9_reg;
        and_ln72_reg_851_pp0_iter11_reg <= and_ln72_reg_851_pp0_iter10_reg;
        and_ln72_reg_851_pp0_iter12_reg <= and_ln72_reg_851_pp0_iter11_reg;
        and_ln72_reg_851_pp0_iter13_reg <= and_ln72_reg_851_pp0_iter12_reg;
        and_ln72_reg_851_pp0_iter14_reg <= and_ln72_reg_851_pp0_iter13_reg;
        and_ln72_reg_851_pp0_iter15_reg <= and_ln72_reg_851_pp0_iter14_reg;
        and_ln72_reg_851_pp0_iter6_reg <= and_ln72_reg_851;
        and_ln72_reg_851_pp0_iter7_reg <= and_ln72_reg_851_pp0_iter6_reg;
        and_ln72_reg_851_pp0_iter8_reg <= and_ln72_reg_851_pp0_iter7_reg;
        and_ln72_reg_851_pp0_iter9_reg <= and_ln72_reg_851_pp0_iter8_reg;
        angle_1_reg_861 <= angle_1_fu_455_p3;
        cs_reg_885 <= PV2_COS8_q0;
        icmp_ln96_reg_866 <= icmp_ln96_fu_463_p2;
        icmp_ln96_reg_866_pp0_iter10_reg <= icmp_ln96_reg_866_pp0_iter9_reg;
        icmp_ln96_reg_866_pp0_iter11_reg <= icmp_ln96_reg_866_pp0_iter10_reg;
        icmp_ln96_reg_866_pp0_iter12_reg <= icmp_ln96_reg_866_pp0_iter11_reg;
        icmp_ln96_reg_866_pp0_iter13_reg <= icmp_ln96_reg_866_pp0_iter12_reg;
        icmp_ln96_reg_866_pp0_iter14_reg <= icmp_ln96_reg_866_pp0_iter13_reg;
        icmp_ln96_reg_866_pp0_iter15_reg <= icmp_ln96_reg_866_pp0_iter14_reg;
        icmp_ln96_reg_866_pp0_iter16_reg <= icmp_ln96_reg_866_pp0_iter15_reg;
        icmp_ln96_reg_866_pp0_iter17_reg <= icmp_ln96_reg_866_pp0_iter16_reg;
        icmp_ln96_reg_866_pp0_iter18_reg <= icmp_ln96_reg_866_pp0_iter17_reg;
        icmp_ln96_reg_866_pp0_iter19_reg <= icmp_ln96_reg_866_pp0_iter18_reg;
        icmp_ln96_reg_866_pp0_iter20_reg <= icmp_ln96_reg_866_pp0_iter19_reg;
        icmp_ln96_reg_866_pp0_iter21_reg <= icmp_ln96_reg_866_pp0_iter20_reg;
        icmp_ln96_reg_866_pp0_iter22_reg <= icmp_ln96_reg_866_pp0_iter21_reg;
        icmp_ln96_reg_866_pp0_iter23_reg <= icmp_ln96_reg_866_pp0_iter22_reg;
        icmp_ln96_reg_866_pp0_iter24_reg <= icmp_ln96_reg_866_pp0_iter23_reg;
        icmp_ln96_reg_866_pp0_iter6_reg <= icmp_ln96_reg_866;
        icmp_ln96_reg_866_pp0_iter7_reg <= icmp_ln96_reg_866_pp0_iter6_reg;
        icmp_ln96_reg_866_pp0_iter8_reg <= icmp_ln96_reg_866_pp0_iter7_reg;
        icmp_ln96_reg_866_pp0_iter9_reg <= icmp_ln96_reg_866_pp0_iter8_reg;
        mul_ln72_reg_846 <= grp_fu_355_p2;
        mul_ln92_reg_970 <= mul_ln92_fu_690_p2;
        off_z_q8_reg_928 <= {{grp_fu_274_p2[31:8]}};
        px_reg_855 <= px_fu_428_p2;
        rx_reg_943 <= rx_fu_566_p2;
        rz_reg_949 <= rz_fu_585_p2;
        sext_ln85_reg_907 <= sext_ln85_fu_503_p1;
        sn_reg_891 <= PV2_SIN8_q0;
        sn_reg_891_pp0_iter8_reg <= sn_reg_891;
        tmp_reg_835_pp0_iter2_reg <= tmp_reg_835;
        tmp_reg_835_pp0_iter3_reg <= tmp_reg_835_pp0_iter2_reg;
        tmp_reg_835_pp0_iter4_reg <= tmp_reg_835_pp0_iter3_reg;
        trunc_ln7_reg_923 <= {{grp_fu_270_p2[31:8]}};
        trunc_ln8_reg_933 <= {{sub_ln85_fu_538_p2[28:8]}};
        trunc_ln91_1_reg_960 <= trunc_ln91_1_fu_595_p1;
        trunc_ln91_reg_955 <= trunc_ln91_fu_591_p1;
        trunc_ln_reg_975 <= {{add_ln92_fu_707_p2[63:3]}};
        u_2_reg_880 <= u_2_fu_488_p3;
        u_2_reg_880_pp0_iter7_reg <= u_2_reg_880;
        v_reg_985 <= m_axi_vox_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        i_2_reg_826_pp0_iter2_reg <= i_2_reg_826_pp0_iter1_reg;
        i_2_reg_826_pp0_iter3_reg <= i_2_reg_826_pp0_iter2_reg;
        i_2_reg_826_pp0_iter4_reg <= i_2_reg_826_pp0_iter3_reg;
        icmp_ln65_reg_831_pp0_iter10_reg <= icmp_ln65_reg_831_pp0_iter9_reg;
        icmp_ln65_reg_831_pp0_iter11_reg <= icmp_ln65_reg_831_pp0_iter10_reg;
        icmp_ln65_reg_831_pp0_iter12_reg <= icmp_ln65_reg_831_pp0_iter11_reg;
        icmp_ln65_reg_831_pp0_iter13_reg <= icmp_ln65_reg_831_pp0_iter12_reg;
        icmp_ln65_reg_831_pp0_iter14_reg <= icmp_ln65_reg_831_pp0_iter13_reg;
        icmp_ln65_reg_831_pp0_iter15_reg <= icmp_ln65_reg_831_pp0_iter14_reg;
        icmp_ln65_reg_831_pp0_iter16_reg <= icmp_ln65_reg_831_pp0_iter15_reg;
        icmp_ln65_reg_831_pp0_iter17_reg <= icmp_ln65_reg_831_pp0_iter16_reg;
        icmp_ln65_reg_831_pp0_iter18_reg <= icmp_ln65_reg_831_pp0_iter17_reg;
        icmp_ln65_reg_831_pp0_iter19_reg <= icmp_ln65_reg_831_pp0_iter18_reg;
        icmp_ln65_reg_831_pp0_iter20_reg <= icmp_ln65_reg_831_pp0_iter19_reg;
        icmp_ln65_reg_831_pp0_iter21_reg <= icmp_ln65_reg_831_pp0_iter20_reg;
        icmp_ln65_reg_831_pp0_iter22_reg <= icmp_ln65_reg_831_pp0_iter21_reg;
        icmp_ln65_reg_831_pp0_iter23_reg <= icmp_ln65_reg_831_pp0_iter22_reg;
        icmp_ln65_reg_831_pp0_iter2_reg <= icmp_ln65_reg_831_pp0_iter1_reg;
        icmp_ln65_reg_831_pp0_iter3_reg <= icmp_ln65_reg_831_pp0_iter2_reg;
        icmp_ln65_reg_831_pp0_iter4_reg <= icmp_ln65_reg_831_pp0_iter3_reg;
        icmp_ln65_reg_831_pp0_iter5_reg <= icmp_ln65_reg_831_pp0_iter4_reg;
        icmp_ln65_reg_831_pp0_iter6_reg <= icmp_ln65_reg_831_pp0_iter5_reg;
        icmp_ln65_reg_831_pp0_iter7_reg <= icmp_ln65_reg_831_pp0_iter6_reg;
        icmp_ln65_reg_831_pp0_iter8_reg <= icmp_ln65_reg_831_pp0_iter7_reg;
        icmp_ln65_reg_831_pp0_iter9_reg <= icmp_ln65_reg_831_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        i_2_reg_826 <= ap_sig_allocacmp_i_2;
        i_2_reg_826_pp0_iter1_reg <= i_2_reg_826;
        icmp_ln65_reg_831 <= icmp_ln65_fu_315_p2;
        icmp_ln65_reg_831_pp0_iter1_reg <= icmp_ln65_reg_831;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        tmp_reg_835 <= {{phi_mul_fu_170[51:32]}};
        tobool_reg_821 <= tobool_fu_286_p2;
        zext_ln52_cast_reg_816[2 : 0] <= zext_ln52_cast_fu_282_p1[2 : 0];
        zext_ln56_cast_reg_811[9 : 0] <= zext_ln56_cast_fu_278_p1[9 : 0];
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        PV2_COS8_ce0_local = 1'b1;
    end else begin
        PV2_COS8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        PV2_SIN8_ce0_local = 1'b1;
    end else begin
        PV2_SIN8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter24_reg == 1'b1) & (icmp_ln65_reg_831_pp0_iter23_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        acc_out_ap_vld = 1'b1;
    end else begin
        acc_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln65_fu_315_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter24_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_2 = 26'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_174;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_270_ce = 1'b1;
    end else begin
        grp_fu_270_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_274_ce = 1'b1;
    end else begin
        grp_fu_274_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        grp_fu_355_ce = 1'b1;
    end else begin
        grp_fu_355_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_749_ce = 1'b1;
    end else begin
        grp_fu_749_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_758_ce = 1'b1;
    end else begin
        grp_fu_758_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'd1 == and_ln72_reg_851_pp0_iter15_reg))) begin
        m_axi_vox_0_ARVALID = 1'b1;
    end else begin
        m_axi_vox_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln96_reg_866_pp0_iter23_reg == 1'd0))) begin
        m_axi_vox_0_RREADY = 1'b1;
    end else begin
        m_axi_vox_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (1'd1 == and_ln72_reg_851_pp0_iter15_reg))) begin
        vox_blk_n_AR = m_axi_vox_0_ARREADY;
    end else begin
        vox_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (icmp_ln96_reg_866_pp0_iter23_reg == 1'd0))) begin
        vox_blk_n_R = m_axi_vox_0_RVALID;
    end else begin
        vox_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign PV2_COS8_address0 = zext_ln78_fu_473_p1;

assign PV2_SIN8_address0 = zext_ln78_fu_473_p1;

assign acc_1_fu_735_p2 = (v_reg_985 ^ acc_fu_178);

assign acc_out = acc_fu_178;

assign add_ln69_fu_335_p2 = (phi_mul_fu_170 + 52'd79536432);

assign add_ln72_fu_386_p2 = (phi_mul3_fu_166 + 53'd106048576);

assign add_ln76_fu_449_p2 = (trunc_ln75_fu_439_p1 + 10'd421);

assign add_ln86_fu_553_p2 = ($signed(sext_ln81_1_fu_535_p1) + $signed(25'd128));

assign add_ln91_fu_681_p2 = (select_ln91_fu_673_p3 + zext_ln89_fu_649_p1);

assign add_ln92_fu_707_p2 = (zext_ln92_1_fu_703_p1 + voxel);

assign and_ln72_fu_380_p2 = (icmp_ln72_fu_372_p2 & icmp_ln72_1_fu_376_p2);

assign and_ln87_fu_629_p2 = (xor_ln88_fu_618_p2 & icmp_ln88_fu_624_p2);

assign angle_1_fu_455_p3 = ((icmp_ln76_fu_443_p2[0:0] == 1'b1) ? add_ln76_fu_449_p2 : trunc_ln75_fu_439_p1);

assign angle_fu_434_p2 = (trunc_ln5_fu_392_p4 + zext_ln56_cast_reg_811);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b1 == ap_block_state25_pp0_stage0_iter24_grp1)) | ((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b1 == ap_block_state17_io_grp1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b1 == ap_block_state25_pp0_stage0_iter24_grp1)) | ((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b1 == ap_block_state17_io_grp1)));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b1 == ap_block_state25_pp0_stage0_iter24_grp1)) | ((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b1 == ap_block_state17_io_grp1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state17_io_grp1 = ((1'd1 == and_ln72_reg_851_pp0_iter15_reg) & (m_axi_vox_0_ARREADY == 1'b0));
end

always @ (*) begin
    ap_block_state25_pp0_stage0_iter24_grp1 = ((icmp_ln96_reg_866_pp0_iter23_reg == 1'd0) & (m_axi_vox_0_RVALID == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_355_p0 = grp_fu_355_p00;

assign grp_fu_355_p00 = tmp_fu_341_p4;

assign grp_fu_355_p1 = 26'd54;

assign grp_fu_749_p2 = 29'd128;

assign grp_fu_758_p0 = sext_ln85_reg_907;

assign i_1_fu_321_p2 = (ap_sig_allocacmp_i_2 + 26'd1);

assign icmp_ln65_fu_315_p2 = ((ap_sig_allocacmp_i_2 == mul_ln65) ? 1'b1 : 1'b0);

assign icmp_ln72_1_fu_376_p2 = ((tmp_reg_835_pp0_iter4_reg < zext_ln59) ? 1'b1 : 1'b0);

assign icmp_ln72_fu_372_p2 = ((i_2_reg_826_pp0_iter4_reg == mul_ln72_reg_846) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_443_p2 = ((angle_fu_434_p2 > 13'd602) ? 1'b1 : 1'b0);

assign icmp_ln87_fu_605_p2 = ((rx_reg_943 < 22'd192) ? 1'b1 : 1'b0);

assign icmp_ln88_fu_624_p2 = (($signed(rz_reg_949) < $signed(22'd192)) ? 1'b1 : 1'b0);

assign icmp_ln96_fu_463_p2 = ((zext_ln69_1_fu_369_p1 < zext_ln52_cast_reg_816) ? 1'b1 : 1'b0);

assign inside_fu_635_p2 = (icmp_ln87_fu_605_p2 & and_ln87_fu_629_p2);

assign m_axi_vox_0_ARADDR = sext_ln92_fu_722_p1;

assign m_axi_vox_0_ARBURST = 2'd0;

assign m_axi_vox_0_ARCACHE = 4'd0;

assign m_axi_vox_0_ARID = 1'd0;

assign m_axi_vox_0_ARLEN = 64'd54;

assign m_axi_vox_0_ARLOCK = 2'd0;

assign m_axi_vox_0_ARPROT = 3'd0;

assign m_axi_vox_0_ARQOS = 4'd0;

assign m_axi_vox_0_ARREGION = 4'd0;

assign m_axi_vox_0_ARSIZE = 3'd0;

assign m_axi_vox_0_ARUSER = 1'd0;

assign m_axi_vox_0_AWADDR = 64'd0;

assign m_axi_vox_0_AWBURST = 2'd0;

assign m_axi_vox_0_AWCACHE = 4'd0;

assign m_axi_vox_0_AWID = 1'd0;

assign m_axi_vox_0_AWLEN = 32'd0;

assign m_axi_vox_0_AWLOCK = 2'd0;

assign m_axi_vox_0_AWPROT = 3'd0;

assign m_axi_vox_0_AWQOS = 4'd0;

assign m_axi_vox_0_AWREGION = 4'd0;

assign m_axi_vox_0_AWSIZE = 3'd0;

assign m_axi_vox_0_AWUSER = 1'd0;

assign m_axi_vox_0_AWVALID = 1'b0;

assign m_axi_vox_0_BREADY = 1'b0;

assign m_axi_vox_0_WDATA = 64'd0;

assign m_axi_vox_0_WID = 1'd0;

assign m_axi_vox_0_WLAST = 1'b0;

assign m_axi_vox_0_WSTRB = 8'd0;

assign m_axi_vox_0_WUSER = 1'd0;

assign m_axi_vox_0_WVALID = 1'b0;

assign mul_ln92_fu_690_p0 = mul_ln92_fu_690_p00;

assign mul_ln92_fu_690_p00 = add_ln91_reg_965;

assign mul_ln92_fu_690_p1 = 21'd54;

assign p_shl1_fu_402_p3 = {{trunc_ln5_fu_392_p4}, {8'd0}};

assign p_shl2_fu_660_p3 = {{trunc_ln91_1_reg_960}, {6'd0}};

assign p_shl_fu_653_p3 = {{trunc_ln91_reg_955}, {8'd0}};

assign px_fu_428_p2 = (sub_ln74_fu_422_p2 + zext_ln69_1_fu_369_p1);

assign rx_fu_566_p2 = ($signed(sext_ln85_2_fu_563_p1) + $signed(22'd96));

assign rz_fu_585_p2 = ($signed(sext_ln86_2_fu_581_p1) + $signed(22'd96));

assign select_ln91_fu_673_p3 = ((inside_fu_635_p2[0:0] == 1'b1) ? sub_ln91_fu_667_p2 : 16'd0);

assign sext_ln81_1_fu_535_p1 = $signed(off_z_q8_reg_928);

assign sext_ln81_fu_532_p1 = $signed(trunc_ln7_reg_923);

assign sext_ln85_2_fu_563_p1 = $signed(trunc_ln8_reg_933);

assign sext_ln85_fu_503_p1 = u_2_reg_880_pp0_iter7_reg;

assign sext_ln86_2_fu_581_p1 = $signed(trunc_ln9_fu_572_p4);

assign sext_ln91_fu_602_p1 = rz_reg_949;

assign sext_ln92_fu_722_p1 = $signed(trunc_ln_reg_975);

assign shl_ln_fu_696_p3 = {{mul_ln92_reg_970}, {3'd0}};

assign sub_ln74_fu_422_p2 = (zext_ln74_fu_418_p1 - p_shl1_fu_402_p3);

assign sub_ln85_fu_538_p2 = ($signed(grp_fu_749_p3) - $signed(sext_ln81_fu_532_p1));

assign sub_ln91_fu_667_p2 = (p_shl_fu_653_p3 - p_shl2_fu_660_p3);

assign tmp_1_fu_410_p3 = {{trunc_ln5_fu_392_p4}, {6'd0}};

assign tmp_2_fu_610_p3 = sext_ln91_fu_602_p1[32'd24];

assign tmp_fu_341_p4 = {{phi_mul_fu_170[51:32]}};

assign tobool_fu_286_p2 = ((mirror_u != 32'd0) ? 1'b1 : 1'b0);

assign trunc_ln5_fu_392_p4 = {{phi_mul3_fu_166[52:40]}};

assign trunc_ln75_fu_439_p1 = angle_fu_434_p2[9:0];

assign trunc_ln85_fu_599_p1 = rx_reg_943[7:0];

assign trunc_ln91_1_fu_595_p1 = rz_fu_585_p2[9:0];

assign trunc_ln91_fu_591_p1 = rz_fu_585_p2[7:0];

assign trunc_ln9_fu_572_p4 = {{grp_fu_758_p3[28:8]}};

assign u_1_fu_483_p2 = (21'd96 - px_reg_855);

assign u_2_fu_488_p3 = ((tobool_reg_821[0:0] == 1'b1) ? u_1_fu_483_p2 : u_fu_478_p2);

assign u_fu_478_p2 = ($signed(px_reg_855) + $signed(21'd2097056));

assign vx_fu_641_p3 = ((inside_fu_635_p2[0:0] == 1'b1) ? trunc_ln85_fu_599_p1 : 8'd0);

assign xor_ln88_fu_618_p2 = (tmp_2_fu_610_p3 ^ 1'd1);

assign zext_ln52_cast_fu_282_p1 = zext_ln52;

assign zext_ln56_cast_fu_278_p1 = zext_ln56;

assign zext_ln69_1_fu_369_p1 = tmp_reg_835_pp0_iter4_reg;

assign zext_ln74_fu_418_p1 = tmp_1_fu_410_p3;

assign zext_ln78_fu_473_p1 = angle_1_reg_861;

assign zext_ln89_fu_649_p1 = vx_fu_641_p3;

assign zext_ln92_1_fu_703_p1 = shl_ln_fu_696_p3;

always @ (posedge ap_clk) begin
    zext_ln56_cast_reg_811[12:10] <= 3'b000;
    zext_ln52_cast_reg_816[20:3] <= 18'b000000000000000000;
end

endmodule //pov_eta_rd_pov_eta_rd_Pipeline_FLAT
