// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="pov_eta_wr_pov_eta_wr,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-2,HLS_INPUT_CLOCK=6.670000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.869100,HLS_SYN_LAT=3908808,HLS_SYN_TPT=none,HLS_SYN_MEM=10,HLS_SYN_DSP=0,HLS_SYN_FF=6018,HLS_SYN_LUT=5794,HLS_VERSION=2024_2}" *)

module pov_eta_wr (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_vox_AWVALID,
        m_axi_vox_AWREADY,
        m_axi_vox_AWADDR,
        m_axi_vox_AWID,
        m_axi_vox_AWLEN,
        m_axi_vox_AWSIZE,
        m_axi_vox_AWBURST,
        m_axi_vox_AWLOCK,
        m_axi_vox_AWCACHE,
        m_axi_vox_AWPROT,
        m_axi_vox_AWQOS,
        m_axi_vox_AWREGION,
        m_axi_vox_AWUSER,
        m_axi_vox_WVALID,
        m_axi_vox_WREADY,
        m_axi_vox_WDATA,
        m_axi_vox_WSTRB,
        m_axi_vox_WLAST,
        m_axi_vox_WID,
        m_axi_vox_WUSER,
        m_axi_vox_ARVALID,
        m_axi_vox_ARREADY,
        m_axi_vox_ARADDR,
        m_axi_vox_ARID,
        m_axi_vox_ARLEN,
        m_axi_vox_ARSIZE,
        m_axi_vox_ARBURST,
        m_axi_vox_ARLOCK,
        m_axi_vox_ARCACHE,
        m_axi_vox_ARPROT,
        m_axi_vox_ARQOS,
        m_axi_vox_ARREGION,
        m_axi_vox_ARUSER,
        m_axi_vox_RVALID,
        m_axi_vox_RREADY,
        m_axi_vox_RDATA,
        m_axi_vox_RLAST,
        m_axi_vox_RID,
        m_axi_vox_RUSER,
        m_axi_vox_RRESP,
        m_axi_vox_BVALID,
        m_axi_vox_BREADY,
        m_axi_vox_BRESP,
        m_axi_vox_BID,
        m_axi_vox_BUSER,
        m_axi_out_r_AWVALID,
        m_axi_out_r_AWREADY,
        m_axi_out_r_AWADDR,
        m_axi_out_r_AWID,
        m_axi_out_r_AWLEN,
        m_axi_out_r_AWSIZE,
        m_axi_out_r_AWBURST,
        m_axi_out_r_AWLOCK,
        m_axi_out_r_AWCACHE,
        m_axi_out_r_AWPROT,
        m_axi_out_r_AWQOS,
        m_axi_out_r_AWREGION,
        m_axi_out_r_AWUSER,
        m_axi_out_r_WVALID,
        m_axi_out_r_WREADY,
        m_axi_out_r_WDATA,
        m_axi_out_r_WSTRB,
        m_axi_out_r_WLAST,
        m_axi_out_r_WID,
        m_axi_out_r_WUSER,
        m_axi_out_r_ARVALID,
        m_axi_out_r_ARREADY,
        m_axi_out_r_ARADDR,
        m_axi_out_r_ARID,
        m_axi_out_r_ARLEN,
        m_axi_out_r_ARSIZE,
        m_axi_out_r_ARBURST,
        m_axi_out_r_ARLOCK,
        m_axi_out_r_ARCACHE,
        m_axi_out_r_ARPROT,
        m_axi_out_r_ARQOS,
        m_axi_out_r_ARREGION,
        m_axi_out_r_ARUSER,
        m_axi_out_r_RVALID,
        m_axi_out_r_RREADY,
        m_axi_out_r_RDATA,
        m_axi_out_r_RLAST,
        m_axi_out_r_RID,
        m_axi_out_r_RUSER,
        m_axi_out_r_RRESP,
        m_axi_out_r_BVALID,
        m_axi_out_r_BREADY,
        m_axi_out_r_BRESP,
        m_axi_out_r_BID,
        m_axi_out_r_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_OUT_R_ID_WIDTH = 1;
parameter    C_M_AXI_OUT_R_ADDR_WIDTH = 64;
parameter    C_M_AXI_OUT_R_DATA_WIDTH = 64;
parameter    C_M_AXI_OUT_R_AWUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_R_ARUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_R_WUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_R_RUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_R_BUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_R_USER_VALUE = 0;
parameter    C_M_AXI_OUT_R_PROT_VALUE = 0;
parameter    C_M_AXI_OUT_R_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_VOX_ID_WIDTH = 1;
parameter    C_M_AXI_VOX_ADDR_WIDTH = 64;
parameter    C_M_AXI_VOX_DATA_WIDTH = 64;
parameter    C_M_AXI_VOX_AWUSER_WIDTH = 1;
parameter    C_M_AXI_VOX_ARUSER_WIDTH = 1;
parameter    C_M_AXI_VOX_WUSER_WIDTH = 1;
parameter    C_M_AXI_VOX_RUSER_WIDTH = 1;
parameter    C_M_AXI_VOX_BUSER_WIDTH = 1;
parameter    C_M_AXI_VOX_USER_VALUE = 0;
parameter    C_M_AXI_VOX_PROT_VALUE = 0;
parameter    C_M_AXI_VOX_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_OUT_R_WSTRB_WIDTH = (64 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_VOX_WSTRB_WIDTH = (64 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_vox_AWVALID;
input   m_axi_vox_AWREADY;
output  [C_M_AXI_VOX_ADDR_WIDTH - 1:0] m_axi_vox_AWADDR;
output  [C_M_AXI_VOX_ID_WIDTH - 1:0] m_axi_vox_AWID;
output  [7:0] m_axi_vox_AWLEN;
output  [2:0] m_axi_vox_AWSIZE;
output  [1:0] m_axi_vox_AWBURST;
output  [1:0] m_axi_vox_AWLOCK;
output  [3:0] m_axi_vox_AWCACHE;
output  [2:0] m_axi_vox_AWPROT;
output  [3:0] m_axi_vox_AWQOS;
output  [3:0] m_axi_vox_AWREGION;
output  [C_M_AXI_VOX_AWUSER_WIDTH - 1:0] m_axi_vox_AWUSER;
output   m_axi_vox_WVALID;
input   m_axi_vox_WREADY;
output  [C_M_AXI_VOX_DATA_WIDTH - 1:0] m_axi_vox_WDATA;
output  [C_M_AXI_VOX_WSTRB_WIDTH - 1:0] m_axi_vox_WSTRB;
output   m_axi_vox_WLAST;
output  [C_M_AXI_VOX_ID_WIDTH - 1:0] m_axi_vox_WID;
output  [C_M_AXI_VOX_WUSER_WIDTH - 1:0] m_axi_vox_WUSER;
output   m_axi_vox_ARVALID;
input   m_axi_vox_ARREADY;
output  [C_M_AXI_VOX_ADDR_WIDTH - 1:0] m_axi_vox_ARADDR;
output  [C_M_AXI_VOX_ID_WIDTH - 1:0] m_axi_vox_ARID;
output  [7:0] m_axi_vox_ARLEN;
output  [2:0] m_axi_vox_ARSIZE;
output  [1:0] m_axi_vox_ARBURST;
output  [1:0] m_axi_vox_ARLOCK;
output  [3:0] m_axi_vox_ARCACHE;
output  [2:0] m_axi_vox_ARPROT;
output  [3:0] m_axi_vox_ARQOS;
output  [3:0] m_axi_vox_ARREGION;
output  [C_M_AXI_VOX_ARUSER_WIDTH - 1:0] m_axi_vox_ARUSER;
input   m_axi_vox_RVALID;
output   m_axi_vox_RREADY;
input  [C_M_AXI_VOX_DATA_WIDTH - 1:0] m_axi_vox_RDATA;
input   m_axi_vox_RLAST;
input  [C_M_AXI_VOX_ID_WIDTH - 1:0] m_axi_vox_RID;
input  [C_M_AXI_VOX_RUSER_WIDTH - 1:0] m_axi_vox_RUSER;
input  [1:0] m_axi_vox_RRESP;
input   m_axi_vox_BVALID;
output   m_axi_vox_BREADY;
input  [1:0] m_axi_vox_BRESP;
input  [C_M_AXI_VOX_ID_WIDTH - 1:0] m_axi_vox_BID;
input  [C_M_AXI_VOX_BUSER_WIDTH - 1:0] m_axi_vox_BUSER;
output   m_axi_out_r_AWVALID;
input   m_axi_out_r_AWREADY;
output  [C_M_AXI_OUT_R_ADDR_WIDTH - 1:0] m_axi_out_r_AWADDR;
output  [C_M_AXI_OUT_R_ID_WIDTH - 1:0] m_axi_out_r_AWID;
output  [7:0] m_axi_out_r_AWLEN;
output  [2:0] m_axi_out_r_AWSIZE;
output  [1:0] m_axi_out_r_AWBURST;
output  [1:0] m_axi_out_r_AWLOCK;
output  [3:0] m_axi_out_r_AWCACHE;
output  [2:0] m_axi_out_r_AWPROT;
output  [3:0] m_axi_out_r_AWQOS;
output  [3:0] m_axi_out_r_AWREGION;
output  [C_M_AXI_OUT_R_AWUSER_WIDTH - 1:0] m_axi_out_r_AWUSER;
output   m_axi_out_r_WVALID;
input   m_axi_out_r_WREADY;
output  [C_M_AXI_OUT_R_DATA_WIDTH - 1:0] m_axi_out_r_WDATA;
output  [C_M_AXI_OUT_R_WSTRB_WIDTH - 1:0] m_axi_out_r_WSTRB;
output   m_axi_out_r_WLAST;
output  [C_M_AXI_OUT_R_ID_WIDTH - 1:0] m_axi_out_r_WID;
output  [C_M_AXI_OUT_R_WUSER_WIDTH - 1:0] m_axi_out_r_WUSER;
output   m_axi_out_r_ARVALID;
input   m_axi_out_r_ARREADY;
output  [C_M_AXI_OUT_R_ADDR_WIDTH - 1:0] m_axi_out_r_ARADDR;
output  [C_M_AXI_OUT_R_ID_WIDTH - 1:0] m_axi_out_r_ARID;
output  [7:0] m_axi_out_r_ARLEN;
output  [2:0] m_axi_out_r_ARSIZE;
output  [1:0] m_axi_out_r_ARBURST;
output  [1:0] m_axi_out_r_ARLOCK;
output  [3:0] m_axi_out_r_ARCACHE;
output  [2:0] m_axi_out_r_ARPROT;
output  [3:0] m_axi_out_r_ARQOS;
output  [3:0] m_axi_out_r_ARREGION;
output  [C_M_AXI_OUT_R_ARUSER_WIDTH - 1:0] m_axi_out_r_ARUSER;
input   m_axi_out_r_RVALID;
output   m_axi_out_r_RREADY;
input  [C_M_AXI_OUT_R_DATA_WIDTH - 1:0] m_axi_out_r_RDATA;
input   m_axi_out_r_RLAST;
input  [C_M_AXI_OUT_R_ID_WIDTH - 1:0] m_axi_out_r_RID;
input  [C_M_AXI_OUT_R_RUSER_WIDTH - 1:0] m_axi_out_r_RUSER;
input  [1:0] m_axi_out_r_RRESP;
input   m_axi_out_r_BVALID;
output   m_axi_out_r_BREADY;
input  [1:0] m_axi_out_r_BRESP;
input  [C_M_AXI_OUT_R_ID_WIDTH - 1:0] m_axi_out_r_BID;
input  [C_M_AXI_OUT_R_BUSER_WIDTH - 1:0] m_axi_out_r_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] voxel;
wire   [63:0] slot_base;
wire   [31:0] phase;
wire   [31:0] slot_start;
wire   [31:0] n_slots;
wire   [31:0] axis_off_q8;
wire   [31:0] mirror_u;
reg    out_r_blk_n_AW;
wire    ap_CS_fsm_state4;
reg    out_r_blk_n_B;
wire    ap_CS_fsm_state11;
reg   [31:0] mirror_u_read_reg_426;
reg   [31:0] axis_off_q8_read_reg_431;
reg   [31:0] phase_read_reg_436;
reg   [63:0] slot_base_read_reg_441;
reg   [63:0] voxel_read_reg_446;
wire   [30:0] trunc_ln14_1_fu_198_p1;
reg   [30:0] trunc_ln14_1_reg_451;
reg   [0:0] tmp_reg_457;
wire   [30:0] select_ln43_fu_218_p3;
reg   [30:0] select_ln43_reg_462;
wire   [0:0] empty_28_fu_226_p2;
reg   [0:0] empty_28_reg_470;
wire   [0:0] icmp_ln46_fu_238_p2;
reg   [0:0] icmp_ln46_reg_475;
wire    ap_CS_fsm_state2;
wire   [44:0] add_ln46_3_fu_286_p2;
reg   [44:0] add_ln46_3_reg_480;
wire   [47:0] add_ln46_5_fu_331_p2;
reg   [47:0] add_ln46_5_reg_485;
wire   [30:0] smax_fu_337_p3;
reg   [30:0] smax_reg_490;
reg   [60:0] trunc_ln1_reg_497;
wire    ap_CS_fsm_state3;
wire   [44:0] empty_fu_361_p3;
reg   [44:0] empty_reg_503;
wire   [44:0] add_ln14_1_fu_420_p2;
reg   [44:0] add_ln14_1_reg_513;
wire    grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_start;
wire    grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_done;
wire    grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_idle;
wire    grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_ready;
wire    grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWVALID;
wire   [63:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWADDR;
wire   [0:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWID;
wire   [31:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWLEN;
wire   [2:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWSIZE;
wire   [1:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWBURST;
wire   [1:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWLOCK;
wire   [3:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWCACHE;
wire   [2:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWPROT;
wire   [3:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWQOS;
wire   [3:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWREGION;
wire   [0:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWUSER;
wire    grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WVALID;
wire   [63:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WDATA;
wire   [7:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WSTRB;
wire    grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WLAST;
wire   [0:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WID;
wire   [0:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WUSER;
wire    grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARVALID;
wire   [63:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARADDR;
wire   [0:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARID;
wire   [31:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARLEN;
wire   [2:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARSIZE;
wire   [1:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARBURST;
wire   [1:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARLOCK;
wire   [3:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARCACHE;
wire   [2:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARPROT;
wire   [3:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARQOS;
wire   [3:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARREGION;
wire   [0:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARUSER;
wire    grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_RREADY;
wire    grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_BREADY;
wire    grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWVALID;
wire   [63:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWADDR;
wire   [0:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWID;
wire   [31:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWLEN;
wire   [2:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWSIZE;
wire   [1:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWBURST;
wire   [1:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWLOCK;
wire   [3:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWCACHE;
wire   [2:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWPROT;
wire   [3:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWQOS;
wire   [3:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWREGION;
wire   [0:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWUSER;
wire    grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WVALID;
wire   [63:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WDATA;
wire   [7:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WSTRB;
wire    grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WLAST;
wire   [0:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WID;
wire   [0:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WUSER;
wire    grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARVALID;
wire   [63:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARADDR;
wire   [0:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARID;
wire   [31:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARLEN;
wire   [2:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARSIZE;
wire   [1:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARBURST;
wire   [1:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARLOCK;
wire   [3:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARCACHE;
wire   [2:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARPROT;
wire   [3:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARQOS;
wire   [3:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARREGION;
wire   [0:0] grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARUSER;
wire    grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_RREADY;
wire    grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_BREADY;
reg    out_r_0_AWVALID;
wire    out_r_0_AWREADY;
reg   [63:0] out_r_0_AWADDR;
reg   [31:0] out_r_0_AWLEN;
reg    out_r_0_WVALID;
wire    out_r_0_WREADY;
wire    out_r_0_ARREADY;
wire    out_r_0_RVALID;
wire   [63:0] out_r_0_RDATA;
wire   [8:0] out_r_0_RFIFONUM;
wire    out_r_0_BVALID;
reg    out_r_0_BREADY;
wire    vox_0_AWREADY;
wire    vox_0_WREADY;
reg    vox_0_ARVALID;
wire    vox_0_ARREADY;
wire    vox_0_RVALID;
reg    vox_0_RREADY;
wire   [63:0] vox_0_RDATA;
wire   [10:0] vox_0_RFIFONUM;
wire    vox_0_BVALID;
reg    grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_start_reg;
reg   [10:0] ap_NS_fsm;
wire    ap_NS_fsm_state5;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire  signed [63:0] sext_ln46_fu_367_p1;
wire   [63:0] zext_ln46_3_fu_377_p1;
wire   [0:0] tmp_3_fu_210_p3;
wire   [30:0] trunc_ln14_fu_194_p1;
wire   [30:0] select_ln42_fu_232_p3;
wire   [43:0] tmp_4_fu_244_p3;
wire   [41:0] tmp_5_fu_256_p3;
wire   [44:0] zext_ln46_fu_252_p1;
wire   [44:0] zext_ln46_1_fu_264_p1;
wire   [37:0] tmp_6_fu_274_p3;
wire   [44:0] add_ln46_2_fu_268_p2;
wire   [44:0] zext_ln46_4_fu_282_p1;
wire   [46:0] tmp_7_fu_292_p3;
wire   [44:0] tmp_8_fu_303_p3;
wire   [47:0] zext_ln46_5_fu_299_p1;
wire   [47:0] zext_ln46_6_fu_310_p1;
wire   [40:0] tmp_9_fu_320_p3;
wire   [47:0] add_ln46_4_fu_314_p2;
wire   [47:0] zext_ln46_7_fu_327_p1;
wire   [63:0] zext_ln46_2_fu_343_p1;
wire   [63:0] add_ln46_fu_346_p2;
wire   [43:0] tmp_10_fu_381_p3;
wire   [41:0] tmp_11_fu_392_p3;
wire   [44:0] zext_ln14_fu_388_p1;
wire   [44:0] zext_ln14_1_fu_399_p1;
wire   [37:0] tmp_12_fu_409_p3;
wire   [44:0] add_ln14_fu_403_p2;
wire   [44:0] zext_ln14_2_fu_416_p1;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_start_reg = 1'b0;
end

pov_eta_wr_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_start),
    .ap_done(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_done),
    .ap_idle(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_idle),
    .ap_ready(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_ready),
    .m_axi_vox_0_AWVALID(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWVALID),
    .m_axi_vox_0_AWREADY(1'b0),
    .m_axi_vox_0_AWADDR(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWADDR),
    .m_axi_vox_0_AWID(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWID),
    .m_axi_vox_0_AWLEN(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWLEN),
    .m_axi_vox_0_AWSIZE(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWSIZE),
    .m_axi_vox_0_AWBURST(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWBURST),
    .m_axi_vox_0_AWLOCK(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWLOCK),
    .m_axi_vox_0_AWCACHE(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWCACHE),
    .m_axi_vox_0_AWPROT(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWPROT),
    .m_axi_vox_0_AWQOS(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWQOS),
    .m_axi_vox_0_AWREGION(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWREGION),
    .m_axi_vox_0_AWUSER(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_AWUSER),
    .m_axi_vox_0_WVALID(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WVALID),
    .m_axi_vox_0_WREADY(1'b0),
    .m_axi_vox_0_WDATA(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WDATA),
    .m_axi_vox_0_WSTRB(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WSTRB),
    .m_axi_vox_0_WLAST(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WLAST),
    .m_axi_vox_0_WID(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WID),
    .m_axi_vox_0_WUSER(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_WUSER),
    .m_axi_vox_0_ARVALID(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARVALID),
    .m_axi_vox_0_ARREADY(vox_0_ARREADY),
    .m_axi_vox_0_ARADDR(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARADDR),
    .m_axi_vox_0_ARID(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARID),
    .m_axi_vox_0_ARLEN(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARLEN),
    .m_axi_vox_0_ARSIZE(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARSIZE),
    .m_axi_vox_0_ARBURST(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARBURST),
    .m_axi_vox_0_ARLOCK(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARLOCK),
    .m_axi_vox_0_ARCACHE(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARCACHE),
    .m_axi_vox_0_ARPROT(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARPROT),
    .m_axi_vox_0_ARQOS(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARQOS),
    .m_axi_vox_0_ARREGION(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARREGION),
    .m_axi_vox_0_ARUSER(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARUSER),
    .m_axi_vox_0_RVALID(vox_0_RVALID),
    .m_axi_vox_0_RREADY(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_RREADY),
    .m_axi_vox_0_RDATA(vox_0_RDATA),
    .m_axi_vox_0_RLAST(1'b0),
    .m_axi_vox_0_RID(1'd0),
    .m_axi_vox_0_RFIFONUM(vox_0_RFIFONUM),
    .m_axi_vox_0_RUSER(1'd0),
    .m_axi_vox_0_RRESP(2'd0),
    .m_axi_vox_0_BVALID(1'b0),
    .m_axi_vox_0_BREADY(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_BREADY),
    .m_axi_vox_0_BRESP(2'd0),
    .m_axi_vox_0_BID(1'd0),
    .m_axi_vox_0_BUSER(1'd0),
    .m_axi_out_r_0_AWVALID(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWVALID),
    .m_axi_out_r_0_AWREADY(out_r_0_AWREADY),
    .m_axi_out_r_0_AWADDR(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWADDR),
    .m_axi_out_r_0_AWID(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWID),
    .m_axi_out_r_0_AWLEN(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWLEN),
    .m_axi_out_r_0_AWSIZE(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWSIZE),
    .m_axi_out_r_0_AWBURST(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWBURST),
    .m_axi_out_r_0_AWLOCK(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWLOCK),
    .m_axi_out_r_0_AWCACHE(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWCACHE),
    .m_axi_out_r_0_AWPROT(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWPROT),
    .m_axi_out_r_0_AWQOS(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWQOS),
    .m_axi_out_r_0_AWREGION(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWREGION),
    .m_axi_out_r_0_AWUSER(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWUSER),
    .m_axi_out_r_0_WVALID(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WVALID),
    .m_axi_out_r_0_WREADY(out_r_0_WREADY),
    .m_axi_out_r_0_WDATA(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WDATA),
    .m_axi_out_r_0_WSTRB(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WSTRB),
    .m_axi_out_r_0_WLAST(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WLAST),
    .m_axi_out_r_0_WID(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WID),
    .m_axi_out_r_0_WUSER(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WUSER),
    .m_axi_out_r_0_ARVALID(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARVALID),
    .m_axi_out_r_0_ARREADY(1'b0),
    .m_axi_out_r_0_ARADDR(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARADDR),
    .m_axi_out_r_0_ARID(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARID),
    .m_axi_out_r_0_ARLEN(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARLEN),
    .m_axi_out_r_0_ARSIZE(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARSIZE),
    .m_axi_out_r_0_ARBURST(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARBURST),
    .m_axi_out_r_0_ARLOCK(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARLOCK),
    .m_axi_out_r_0_ARCACHE(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARCACHE),
    .m_axi_out_r_0_ARPROT(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARPROT),
    .m_axi_out_r_0_ARQOS(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARQOS),
    .m_axi_out_r_0_ARREGION(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARREGION),
    .m_axi_out_r_0_ARUSER(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_ARUSER),
    .m_axi_out_r_0_RVALID(1'b0),
    .m_axi_out_r_0_RREADY(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_RREADY),
    .m_axi_out_r_0_RDATA(64'd0),
    .m_axi_out_r_0_RLAST(1'b0),
    .m_axi_out_r_0_RID(1'd0),
    .m_axi_out_r_0_RFIFONUM(9'd0),
    .m_axi_out_r_0_RUSER(1'd0),
    .m_axi_out_r_0_RRESP(2'd0),
    .m_axi_out_r_0_BVALID(out_r_0_BVALID),
    .m_axi_out_r_0_BREADY(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_BREADY),
    .m_axi_out_r_0_BRESP(2'd0),
    .m_axi_out_r_0_BID(1'd0),
    .m_axi_out_r_0_BUSER(1'd0),
    .mul_ln14(add_ln14_1_reg_513),
    .sext_ln46(trunc_ln1_reg_497),
    .phase(phase_read_reg_436),
    .zext_ln18(select_ln43_reg_462),
    .axis_off_q8(axis_off_q8_read_reg_431),
    .voxel(voxel_read_reg_446),
    .mirror_u(mirror_u_read_reg_426)
);

pov_eta_wr_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .voxel(voxel),
    .slot_base(slot_base),
    .phase(phase),
    .slot_start(slot_start),
    .n_slots(n_slots),
    .axis_off_q8(axis_off_q8),
    .mirror_u(mirror_u)
);

pov_eta_wr_out_r_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 64 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_OUT_R_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_OUT_R_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_OUT_R_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_OUT_R_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_OUT_R_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_OUT_R_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_OUT_R_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_OUT_R_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_OUT_R_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_OUT_R_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_OUT_R_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 64 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 0 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
out_r_m_axi_U(
    .AWVALID(m_axi_out_r_AWVALID),
    .AWREADY(m_axi_out_r_AWREADY),
    .AWADDR(m_axi_out_r_AWADDR),
    .AWID(m_axi_out_r_AWID),
    .AWLEN(m_axi_out_r_AWLEN),
    .AWSIZE(m_axi_out_r_AWSIZE),
    .AWBURST(m_axi_out_r_AWBURST),
    .AWLOCK(m_axi_out_r_AWLOCK),
    .AWCACHE(m_axi_out_r_AWCACHE),
    .AWPROT(m_axi_out_r_AWPROT),
    .AWQOS(m_axi_out_r_AWQOS),
    .AWREGION(m_axi_out_r_AWREGION),
    .AWUSER(m_axi_out_r_AWUSER),
    .WVALID(m_axi_out_r_WVALID),
    .WREADY(m_axi_out_r_WREADY),
    .WDATA(m_axi_out_r_WDATA),
    .WSTRB(m_axi_out_r_WSTRB),
    .WLAST(m_axi_out_r_WLAST),
    .WID(m_axi_out_r_WID),
    .WUSER(m_axi_out_r_WUSER),
    .ARVALID(m_axi_out_r_ARVALID),
    .ARREADY(m_axi_out_r_ARREADY),
    .ARADDR(m_axi_out_r_ARADDR),
    .ARID(m_axi_out_r_ARID),
    .ARLEN(m_axi_out_r_ARLEN),
    .ARSIZE(m_axi_out_r_ARSIZE),
    .ARBURST(m_axi_out_r_ARBURST),
    .ARLOCK(m_axi_out_r_ARLOCK),
    .ARCACHE(m_axi_out_r_ARCACHE),
    .ARPROT(m_axi_out_r_ARPROT),
    .ARQOS(m_axi_out_r_ARQOS),
    .ARREGION(m_axi_out_r_ARREGION),
    .ARUSER(m_axi_out_r_ARUSER),
    .RVALID(m_axi_out_r_RVALID),
    .RREADY(m_axi_out_r_RREADY),
    .RDATA(m_axi_out_r_RDATA),
    .RLAST(m_axi_out_r_RLAST),
    .RID(m_axi_out_r_RID),
    .RUSER(m_axi_out_r_RUSER),
    .RRESP(m_axi_out_r_RRESP),
    .BVALID(m_axi_out_r_BVALID),
    .BREADY(m_axi_out_r_BREADY),
    .BRESP(m_axi_out_r_BRESP),
    .BID(m_axi_out_r_BID),
    .BUSER(m_axi_out_r_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(1'b0),
    .I_CH0_ARREADY(out_r_0_ARREADY),
    .I_CH0_ARADDR(64'd0),
    .I_CH0_ARLEN(32'd0),
    .I_CH0_RVALID(out_r_0_RVALID),
    .I_CH0_RREADY(1'b0),
    .I_CH0_RDATA(out_r_0_RDATA),
    .I_CH0_RFIFONUM(out_r_0_RFIFONUM),
    .I_CH0_AWVALID(out_r_0_AWVALID),
    .I_CH0_AWREADY(out_r_0_AWREADY),
    .I_CH0_AWADDR(out_r_0_AWADDR),
    .I_CH0_AWLEN(out_r_0_AWLEN),
    .I_CH0_WVALID(out_r_0_WVALID),
    .I_CH0_WREADY(out_r_0_WREADY),
    .I_CH0_WDATA(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WDATA),
    .I_CH0_WSTRB(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WSTRB),
    .I_CH0_BVALID(out_r_0_BVALID),
    .I_CH0_BREADY(out_r_0_BREADY)
);

pov_eta_wr_vox_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 64 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_VOX_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_VOX_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_VOX_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_VOX_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_VOX_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_VOX_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_VOX_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_VOX_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_VOX_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_VOX_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_VOX_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 11 ),
    .CH0_USER_DW( 64 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
vox_m_axi_U(
    .AWVALID(m_axi_vox_AWVALID),
    .AWREADY(m_axi_vox_AWREADY),
    .AWADDR(m_axi_vox_AWADDR),
    .AWID(m_axi_vox_AWID),
    .AWLEN(m_axi_vox_AWLEN),
    .AWSIZE(m_axi_vox_AWSIZE),
    .AWBURST(m_axi_vox_AWBURST),
    .AWLOCK(m_axi_vox_AWLOCK),
    .AWCACHE(m_axi_vox_AWCACHE),
    .AWPROT(m_axi_vox_AWPROT),
    .AWQOS(m_axi_vox_AWQOS),
    .AWREGION(m_axi_vox_AWREGION),
    .AWUSER(m_axi_vox_AWUSER),
    .WVALID(m_axi_vox_WVALID),
    .WREADY(m_axi_vox_WREADY),
    .WDATA(m_axi_vox_WDATA),
    .WSTRB(m_axi_vox_WSTRB),
    .WLAST(m_axi_vox_WLAST),
    .WID(m_axi_vox_WID),
    .WUSER(m_axi_vox_WUSER),
    .ARVALID(m_axi_vox_ARVALID),
    .ARREADY(m_axi_vox_ARREADY),
    .ARADDR(m_axi_vox_ARADDR),
    .ARID(m_axi_vox_ARID),
    .ARLEN(m_axi_vox_ARLEN),
    .ARSIZE(m_axi_vox_ARSIZE),
    .ARBURST(m_axi_vox_ARBURST),
    .ARLOCK(m_axi_vox_ARLOCK),
    .ARCACHE(m_axi_vox_ARCACHE),
    .ARPROT(m_axi_vox_ARPROT),
    .ARQOS(m_axi_vox_ARQOS),
    .ARREGION(m_axi_vox_ARREGION),
    .ARUSER(m_axi_vox_ARUSER),
    .RVALID(m_axi_vox_RVALID),
    .RREADY(m_axi_vox_RREADY),
    .RDATA(m_axi_vox_RDATA),
    .RLAST(m_axi_vox_RLAST),
    .RID(m_axi_vox_RID),
    .RUSER(m_axi_vox_RUSER),
    .RRESP(m_axi_vox_RRESP),
    .BVALID(m_axi_vox_BVALID),
    .BREADY(m_axi_vox_BREADY),
    .BRESP(m_axi_vox_BRESP),
    .BID(m_axi_vox_BID),
    .BUSER(m_axi_vox_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(vox_0_ARVALID),
    .I_CH0_ARREADY(vox_0_ARREADY),
    .I_CH0_ARADDR(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARADDR),
    .I_CH0_ARLEN(grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARLEN),
    .I_CH0_RVALID(vox_0_RVALID),
    .I_CH0_RREADY(vox_0_RREADY),
    .I_CH0_RDATA(vox_0_RDATA),
    .I_CH0_RFIFONUM(vox_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(vox_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(vox_0_WREADY),
    .I_CH0_WDATA(64'd0),
    .I_CH0_WSTRB(8'd0),
    .I_CH0_BVALID(vox_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state5) & (1'b1 == ap_CS_fsm_state4))) begin
            grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_start_reg <= 1'b1;
        end else if ((grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_ready == 1'b1)) begin
            grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln14_1_reg_513[44 : 7] <= add_ln14_1_fu_420_p2[44 : 7];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln46_3_reg_480[44 : 7] <= add_ln46_3_fu_286_p2[44 : 7];
        add_ln46_5_reg_485[47 : 10] <= add_ln46_5_fu_331_p2[47 : 10];
        icmp_ln46_reg_475 <= icmp_ln46_fu_238_p2;
        smax_reg_490 <= smax_fu_337_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        axis_off_q8_read_reg_431 <= axis_off_q8;
        empty_28_reg_470 <= empty_28_fu_226_p2;
        mirror_u_read_reg_426 <= mirror_u;
        phase_read_reg_436 <= phase;
        select_ln43_reg_462 <= select_ln43_fu_218_p3;
        slot_base_read_reg_441 <= slot_base;
        tmp_reg_457 <= n_slots[32'd31];
        trunc_ln14_1_reg_451 <= trunc_ln14_1_fu_198_p1;
        voxel_read_reg_446 <= voxel;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        empty_reg_503[44 : 7] <= empty_fu_361_p3[44 : 7];
        trunc_ln1_reg_497 <= {{add_ln46_fu_346_p2[63:3]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((out_r_0_BVALID == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((out_r_0_AWREADY == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((out_r_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((out_r_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((out_r_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_r_0_AWADDR = sext_ln46_fu_367_p1;
    end else if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        out_r_0_AWADDR = grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWADDR;
    end else begin
        out_r_0_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((out_r_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_r_0_AWLEN = zext_ln46_3_fu_377_p1;
    end else if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        out_r_0_AWLEN = grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWLEN;
    end else begin
        out_r_0_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((out_r_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_r_0_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        out_r_0_AWVALID = grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_AWVALID;
    end else begin
        out_r_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((out_r_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        out_r_0_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        out_r_0_BREADY = grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_BREADY;
    end else begin
        out_r_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        out_r_0_WVALID = grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_out_r_0_WVALID;
    end else begin
        out_r_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out_r_blk_n_AW = m_axi_out_r_AWREADY;
    end else begin
        out_r_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        out_r_blk_n_B = m_axi_out_r_BVALID;
    end else begin
        out_r_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        vox_0_ARVALID = grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_ARVALID;
    end else begin
        vox_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        vox_0_RREADY = grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_m_axi_vox_0_RREADY;
    end else begin
        vox_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((out_r_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((out_r_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln14_1_fu_420_p2 = (add_ln14_fu_403_p2 + zext_ln14_2_fu_416_p1);

assign add_ln14_fu_403_p2 = (zext_ln14_fu_388_p1 + zext_ln14_1_fu_399_p1);

assign add_ln46_2_fu_268_p2 = (zext_ln46_fu_252_p1 + zext_ln46_1_fu_264_p1);

assign add_ln46_3_fu_286_p2 = (add_ln46_2_fu_268_p2 + zext_ln46_4_fu_282_p1);

assign add_ln46_4_fu_314_p2 = (zext_ln46_5_fu_299_p1 + zext_ln46_6_fu_310_p1);

assign add_ln46_5_fu_331_p2 = (add_ln46_4_fu_314_p2 + zext_ln46_7_fu_327_p1);

assign add_ln46_fu_346_p2 = (zext_ln46_2_fu_343_p1 + slot_base_read_reg_441);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_NS_fsm_state5 = ap_NS_fsm[32'd4];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_28_fu_226_p2 = (($signed(n_slots) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign empty_fu_361_p3 = ((icmp_ln46_reg_475[0:0] == 1'b1) ? add_ln46_3_reg_480 : 45'd0);

assign grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_start = grp_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_fu_175_ap_start_reg;

assign icmp_ln46_fu_238_p2 = ((select_ln42_fu_232_p3 != 31'd0) ? 1'b1 : 1'b0);

assign select_ln42_fu_232_p3 = ((tmp_reg_457[0:0] == 1'b1) ? 31'd0 : trunc_ln14_1_reg_451);

assign select_ln43_fu_218_p3 = ((tmp_3_fu_210_p3[0:0] == 1'b1) ? 31'd0 : trunc_ln14_fu_194_p1);

assign sext_ln46_fu_367_p1 = $signed(trunc_ln1_reg_497);

assign smax_fu_337_p3 = ((empty_28_reg_470[0:0] == 1'b1) ? trunc_ln14_1_reg_451 : 31'd0);

assign tmp_10_fu_381_p3 = {{smax_reg_490}, {13'd0}};

assign tmp_11_fu_392_p3 = {{smax_reg_490}, {11'd0}};

assign tmp_12_fu_409_p3 = {{smax_reg_490}, {7'd0}};

assign tmp_3_fu_210_p3 = slot_start[32'd31];

assign tmp_4_fu_244_p3 = {{select_ln42_fu_232_p3}, {13'd0}};

assign tmp_5_fu_256_p3 = {{select_ln42_fu_232_p3}, {11'd0}};

assign tmp_6_fu_274_p3 = {{select_ln42_fu_232_p3}, {7'd0}};

assign tmp_7_fu_292_p3 = {{select_ln43_reg_462}, {16'd0}};

assign tmp_8_fu_303_p3 = {{select_ln43_reg_462}, {14'd0}};

assign tmp_9_fu_320_p3 = {{select_ln43_reg_462}, {10'd0}};

assign trunc_ln14_1_fu_198_p1 = n_slots[30:0];

assign trunc_ln14_fu_194_p1 = slot_start[30:0];

assign zext_ln14_1_fu_399_p1 = tmp_11_fu_392_p3;

assign zext_ln14_2_fu_416_p1 = tmp_12_fu_409_p3;

assign zext_ln14_fu_388_p1 = tmp_10_fu_381_p3;

assign zext_ln46_1_fu_264_p1 = tmp_5_fu_256_p3;

assign zext_ln46_2_fu_343_p1 = add_ln46_5_reg_485;

assign zext_ln46_3_fu_377_p1 = empty_reg_503;

assign zext_ln46_4_fu_282_p1 = tmp_6_fu_274_p3;

assign zext_ln46_5_fu_299_p1 = tmp_7_fu_292_p3;

assign zext_ln46_6_fu_310_p1 = tmp_8_fu_303_p3;

assign zext_ln46_7_fu_327_p1 = tmp_9_fu_320_p3;

assign zext_ln46_fu_252_p1 = tmp_4_fu_244_p3;

always @ (posedge ap_clk) begin
    add_ln46_3_reg_480[6:0] <= 7'b0000000;
    add_ln46_5_reg_485[9:0] <= 10'b0000000000;
    empty_reg_503[6:0] <= 7'b0000000;
    add_ln14_1_reg_513[6:0] <= 7'b0000000;
end

endmodule //pov_eta_wr
