// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pov_eta_wr_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_vox_0_AWVALID,
        m_axi_vox_0_AWREADY,
        m_axi_vox_0_AWADDR,
        m_axi_vox_0_AWID,
        m_axi_vox_0_AWLEN,
        m_axi_vox_0_AWSIZE,
        m_axi_vox_0_AWBURST,
        m_axi_vox_0_AWLOCK,
        m_axi_vox_0_AWCACHE,
        m_axi_vox_0_AWPROT,
        m_axi_vox_0_AWQOS,
        m_axi_vox_0_AWREGION,
        m_axi_vox_0_AWUSER,
        m_axi_vox_0_WVALID,
        m_axi_vox_0_WREADY,
        m_axi_vox_0_WDATA,
        m_axi_vox_0_WSTRB,
        m_axi_vox_0_WLAST,
        m_axi_vox_0_WID,
        m_axi_vox_0_WUSER,
        m_axi_vox_0_ARVALID,
        m_axi_vox_0_ARREADY,
        m_axi_vox_0_ARADDR,
        m_axi_vox_0_ARID,
        m_axi_vox_0_ARLEN,
        m_axi_vox_0_ARSIZE,
        m_axi_vox_0_ARBURST,
        m_axi_vox_0_ARLOCK,
        m_axi_vox_0_ARCACHE,
        m_axi_vox_0_ARPROT,
        m_axi_vox_0_ARQOS,
        m_axi_vox_0_ARREGION,
        m_axi_vox_0_ARUSER,
        m_axi_vox_0_RVALID,
        m_axi_vox_0_RREADY,
        m_axi_vox_0_RDATA,
        m_axi_vox_0_RLAST,
        m_axi_vox_0_RID,
        m_axi_vox_0_RFIFONUM,
        m_axi_vox_0_RUSER,
        m_axi_vox_0_RRESP,
        m_axi_vox_0_BVALID,
        m_axi_vox_0_BREADY,
        m_axi_vox_0_BRESP,
        m_axi_vox_0_BID,
        m_axi_vox_0_BUSER,
        m_axi_out_r_0_AWVALID,
        m_axi_out_r_0_AWREADY,
        m_axi_out_r_0_AWADDR,
        m_axi_out_r_0_AWID,
        m_axi_out_r_0_AWLEN,
        m_axi_out_r_0_AWSIZE,
        m_axi_out_r_0_AWBURST,
        m_axi_out_r_0_AWLOCK,
        m_axi_out_r_0_AWCACHE,
        m_axi_out_r_0_AWPROT,
        m_axi_out_r_0_AWQOS,
        m_axi_out_r_0_AWREGION,
        m_axi_out_r_0_AWUSER,
        m_axi_out_r_0_WVALID,
        m_axi_out_r_0_WREADY,
        m_axi_out_r_0_WDATA,
        m_axi_out_r_0_WSTRB,
        m_axi_out_r_0_WLAST,
        m_axi_out_r_0_WID,
        m_axi_out_r_0_WUSER,
        m_axi_out_r_0_ARVALID,
        m_axi_out_r_0_ARREADY,
        m_axi_out_r_0_ARADDR,
        m_axi_out_r_0_ARID,
        m_axi_out_r_0_ARLEN,
        m_axi_out_r_0_ARSIZE,
        m_axi_out_r_0_ARBURST,
        m_axi_out_r_0_ARLOCK,
        m_axi_out_r_0_ARCACHE,
        m_axi_out_r_0_ARPROT,
        m_axi_out_r_0_ARQOS,
        m_axi_out_r_0_ARREGION,
        m_axi_out_r_0_ARUSER,
        m_axi_out_r_0_RVALID,
        m_axi_out_r_0_RREADY,
        m_axi_out_r_0_RDATA,
        m_axi_out_r_0_RLAST,
        m_axi_out_r_0_RID,
        m_axi_out_r_0_RFIFONUM,
        m_axi_out_r_0_RUSER,
        m_axi_out_r_0_RRESP,
        m_axi_out_r_0_BVALID,
        m_axi_out_r_0_BREADY,
        m_axi_out_r_0_BRESP,
        m_axi_out_r_0_BID,
        m_axi_out_r_0_BUSER,
        mul_ln14,
        sext_ln46,
        phase,
        zext_ln18,
        axis_off_q8,
        voxel,
        mirror_u
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_vox_0_AWVALID;
input   m_axi_vox_0_AWREADY;
output  [63:0] m_axi_vox_0_AWADDR;
output  [0:0] m_axi_vox_0_AWID;
output  [31:0] m_axi_vox_0_AWLEN;
output  [2:0] m_axi_vox_0_AWSIZE;
output  [1:0] m_axi_vox_0_AWBURST;
output  [1:0] m_axi_vox_0_AWLOCK;
output  [3:0] m_axi_vox_0_AWCACHE;
output  [2:0] m_axi_vox_0_AWPROT;
output  [3:0] m_axi_vox_0_AWQOS;
output  [3:0] m_axi_vox_0_AWREGION;
output  [0:0] m_axi_vox_0_AWUSER;
output   m_axi_vox_0_WVALID;
input   m_axi_vox_0_WREADY;
output  [63:0] m_axi_vox_0_WDATA;
output  [7:0] m_axi_vox_0_WSTRB;
output   m_axi_vox_0_WLAST;
output  [0:0] m_axi_vox_0_WID;
output  [0:0] m_axi_vox_0_WUSER;
output   m_axi_vox_0_ARVALID;
input   m_axi_vox_0_ARREADY;
output  [63:0] m_axi_vox_0_ARADDR;
output  [0:0] m_axi_vox_0_ARID;
output  [31:0] m_axi_vox_0_ARLEN;
output  [2:0] m_axi_vox_0_ARSIZE;
output  [1:0] m_axi_vox_0_ARBURST;
output  [1:0] m_axi_vox_0_ARLOCK;
output  [3:0] m_axi_vox_0_ARCACHE;
output  [2:0] m_axi_vox_0_ARPROT;
output  [3:0] m_axi_vox_0_ARQOS;
output  [3:0] m_axi_vox_0_ARREGION;
output  [0:0] m_axi_vox_0_ARUSER;
input   m_axi_vox_0_RVALID;
output   m_axi_vox_0_RREADY;
input  [63:0] m_axi_vox_0_RDATA;
input   m_axi_vox_0_RLAST;
input  [0:0] m_axi_vox_0_RID;
input  [10:0] m_axi_vox_0_RFIFONUM;
input  [0:0] m_axi_vox_0_RUSER;
input  [1:0] m_axi_vox_0_RRESP;
input   m_axi_vox_0_BVALID;
output   m_axi_vox_0_BREADY;
input  [1:0] m_axi_vox_0_BRESP;
input  [0:0] m_axi_vox_0_BID;
input  [0:0] m_axi_vox_0_BUSER;
output   m_axi_out_r_0_AWVALID;
input   m_axi_out_r_0_AWREADY;
output  [63:0] m_axi_out_r_0_AWADDR;
output  [0:0] m_axi_out_r_0_AWID;
output  [31:0] m_axi_out_r_0_AWLEN;
output  [2:0] m_axi_out_r_0_AWSIZE;
output  [1:0] m_axi_out_r_0_AWBURST;
output  [1:0] m_axi_out_r_0_AWLOCK;
output  [3:0] m_axi_out_r_0_AWCACHE;
output  [2:0] m_axi_out_r_0_AWPROT;
output  [3:0] m_axi_out_r_0_AWQOS;
output  [3:0] m_axi_out_r_0_AWREGION;
output  [0:0] m_axi_out_r_0_AWUSER;
output   m_axi_out_r_0_WVALID;
input   m_axi_out_r_0_WREADY;
output  [63:0] m_axi_out_r_0_WDATA;
output  [7:0] m_axi_out_r_0_WSTRB;
output   m_axi_out_r_0_WLAST;
output  [0:0] m_axi_out_r_0_WID;
output  [0:0] m_axi_out_r_0_WUSER;
output   m_axi_out_r_0_ARVALID;
input   m_axi_out_r_0_ARREADY;
output  [63:0] m_axi_out_r_0_ARADDR;
output  [0:0] m_axi_out_r_0_ARID;
output  [31:0] m_axi_out_r_0_ARLEN;
output  [2:0] m_axi_out_r_0_ARSIZE;
output  [1:0] m_axi_out_r_0_ARBURST;
output  [1:0] m_axi_out_r_0_ARLOCK;
output  [3:0] m_axi_out_r_0_ARCACHE;
output  [2:0] m_axi_out_r_0_ARPROT;
output  [3:0] m_axi_out_r_0_ARQOS;
output  [3:0] m_axi_out_r_0_ARREGION;
output  [0:0] m_axi_out_r_0_ARUSER;
input   m_axi_out_r_0_RVALID;
output   m_axi_out_r_0_RREADY;
input  [63:0] m_axi_out_r_0_RDATA;
input   m_axi_out_r_0_RLAST;
input  [0:0] m_axi_out_r_0_RID;
input  [8:0] m_axi_out_r_0_RFIFONUM;
input  [0:0] m_axi_out_r_0_RUSER;
input  [1:0] m_axi_out_r_0_RRESP;
input   m_axi_out_r_0_BVALID;
output   m_axi_out_r_0_BREADY;
input  [1:0] m_axi_out_r_0_BRESP;
input  [0:0] m_axi_out_r_0_BID;
input  [0:0] m_axi_out_r_0_BUSER;
input  [44:0] mul_ln14;
input  [60:0] sext_ln46;
input  [31:0] phase;
input  [30:0] zext_ln18;
input  [31:0] axis_off_q8;
input  [63:0] voxel;
input  [31:0] mirror_u;

reg ap_idle;
reg m_axi_vox_0_ARVALID;
reg m_axi_vox_0_RREADY;
reg m_axi_out_r_0_WVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg    ap_enable_reg_pp0_iter36;
reg    ap_enable_reg_pp0_iter37;
reg    ap_enable_reg_pp0_iter38;
reg    ap_enable_reg_pp0_iter39;
reg    ap_enable_reg_pp0_iter40;
reg    ap_enable_reg_pp0_iter41;
reg    ap_enable_reg_pp0_iter42;
reg    ap_enable_reg_pp0_iter43;
reg    ap_enable_reg_pp0_iter44;
reg    ap_enable_reg_pp0_iter45;
reg    ap_enable_reg_pp0_iter46;
reg    ap_enable_reg_pp0_iter47;
reg    ap_enable_reg_pp0_iter48;
reg    ap_enable_reg_pp0_iter49;
reg    ap_enable_reg_pp0_iter50;
reg    ap_enable_reg_pp0_iter51;
reg    ap_enable_reg_pp0_iter52;
reg    ap_enable_reg_pp0_iter53;
reg    ap_enable_reg_pp0_iter54;
reg    ap_enable_reg_pp0_iter55;
reg    ap_enable_reg_pp0_iter56;
reg    ap_enable_reg_pp0_iter57;
reg    ap_enable_reg_pp0_iter58;
reg    ap_enable_reg_pp0_iter59;
reg    ap_enable_reg_pp0_iter60;
reg    ap_enable_reg_pp0_iter61;
reg    ap_enable_reg_pp0_iter62;
reg    ap_idle_pp0;
reg   [0:0] first_iter_0_mid2_reg_890;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter51_reg;
reg   [0:0] inside_reg_1008;
reg   [0:0] inside_reg_1008_pp0_iter51_reg;
reg    ap_predicate_op234_readreq_state53;
reg    ap_block_state53_io;
reg   [0:0] icmp_ln46_reg_871;
reg   [0:0] icmp_ln46_reg_871_pp0_iter59_reg;
reg   [0:0] inside_reg_1008_pp0_iter59_reg;
reg    ap_predicate_op243_read_state61;
reg    ap_block_state61_pp0_stage0_iter60;
reg   [0:0] icmp_ln46_reg_871_pp0_iter61_reg;
reg    ap_block_state63_io;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln46_fu_327_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [9:0] PV2_COS8_address0;
wire   [9:0] PV2_COS8_q0;
wire   [9:0] PV2_SIN8_address0;
wire   [9:0] PV2_SIN8_q0;
reg    out_r_blk_n_W;
wire    ap_block_pp0_stage0;
reg    vox_blk_n_R;
reg    vox_blk_n_AR;
reg   [0:0] first_iter_0_reg_264;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] zext_ln18_cast_fu_285_p1;
reg   [31:0] zext_ln18_cast_reg_856;
wire   [0:0] tobool_fu_293_p2;
reg   [0:0] tobool_reg_866;
reg   [0:0] icmp_ln46_reg_871_pp0_iter2_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter3_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter4_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter5_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter6_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter7_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter8_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter9_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter10_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter11_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter12_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter13_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter14_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter15_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter16_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter17_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter18_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter19_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter20_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter21_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter22_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter23_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter24_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter25_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter26_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter27_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter28_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter29_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter30_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter31_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter32_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter33_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter34_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter35_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter36_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter37_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter38_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter39_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter40_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter41_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter42_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter43_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter44_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter45_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter46_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter47_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter48_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter49_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter50_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter51_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter52_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter53_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter54_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter55_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter56_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter57_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter58_reg;
reg   [0:0] icmp_ln46_reg_871_pp0_iter60_reg;
wire   [0:0] icmp_ln71_fu_352_p2;
reg   [0:0] icmp_ln71_reg_875;
reg   [0:0] icmp_ln71_reg_875_pp0_iter3_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter4_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter5_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter6_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter7_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter8_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter9_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter10_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter11_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter12_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter13_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter14_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter15_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter16_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter17_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter18_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter19_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter20_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter21_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter22_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter23_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter24_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter25_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter26_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter27_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter28_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter29_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter30_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter31_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter32_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter33_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter34_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter35_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter36_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter37_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter38_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter39_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter40_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter41_reg;
reg   [0:0] icmp_ln71_reg_875_pp0_iter42_reg;
wire   [0:0] and_ln46_fu_376_p2;
reg   [0:0] and_ln46_reg_880;
reg   [0:0] and_ln46_reg_880_pp0_iter3_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter4_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter5_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter6_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter7_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter8_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter9_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter10_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter11_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter12_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter13_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter14_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter15_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter16_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter17_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter18_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter19_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter20_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter21_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter22_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter23_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter24_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter25_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter26_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter27_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter28_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter29_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter30_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter31_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter32_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter33_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter34_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter35_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter36_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter37_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter38_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter39_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter40_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter41_reg;
reg   [0:0] and_ln46_reg_880_pp0_iter42_reg;
wire   [30:0] select_ln46_1_fu_388_p3;
reg   [30:0] select_ln46_1_reg_885;
wire   [0:0] first_iter_0_mid2_fu_396_p2;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter3_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter4_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter5_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter6_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter7_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter8_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter9_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter10_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter11_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter12_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter13_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter14_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter15_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter16_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter17_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter18_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter19_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter20_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter21_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter22_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter23_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter24_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter25_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter26_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter27_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter28_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter29_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter30_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter31_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter32_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter33_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter34_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter35_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter36_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter37_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter38_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter39_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter40_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter41_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter42_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter43_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter44_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter45_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter46_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter47_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter48_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter49_reg;
reg   [0:0] first_iter_0_mid2_reg_890_pp0_iter50_reg;
wire   [31:0] add_ln50_1_fu_459_p2;
reg   [31:0] add_ln50_1_reg_894;
wire   [9:0] trunc_ln50_fu_469_p1;
reg   [9:0] trunc_ln50_reg_899;
reg   [0:0] tmp_reg_905;
wire   [9:0] angle_1_fu_486_p3;
reg   [9:0] angle_1_reg_910;
reg  signed [9:0] cs_reg_925;
reg  signed [9:0] cs_reg_925_pp0_iter43_reg;
reg  signed [9:0] sn_reg_931;
reg  signed [9:0] sn_reg_931_pp0_iter43_reg;
wire   [7:0] u_1_fu_540_p3;
reg   [7:0] u_1_reg_947;
wire  signed [17:0] sext_ln74_fu_558_p1;
reg   [23:0] trunc_ln3_reg_968;
reg   [23:0] off_z_q8_reg_973;
reg   [16:0] trunc_ln4_reg_988;
reg   [16:0] trunc_ln5_reg_993;
wire   [7:0] trunc_ln78_fu_626_p1;
reg   [7:0] trunc_ln78_reg_998;
wire   [7:0] trunc_ln79_fu_643_p1;
reg   [7:0] trunc_ln79_reg_1003;
wire   [0:0] inside_fu_679_p2;
reg   [0:0] inside_reg_1008_pp0_iter49_reg;
reg   [0:0] inside_reg_1008_pp0_iter50_reg;
reg   [0:0] inside_reg_1008_pp0_iter52_reg;
reg   [0:0] inside_reg_1008_pp0_iter53_reg;
reg   [0:0] inside_reg_1008_pp0_iter54_reg;
reg   [0:0] inside_reg_1008_pp0_iter55_reg;
reg   [0:0] inside_reg_1008_pp0_iter56_reg;
reg   [0:0] inside_reg_1008_pp0_iter57_reg;
reg   [0:0] inside_reg_1008_pp0_iter58_reg;
reg   [0:0] inside_reg_1008_pp0_iter60_reg;
wire   [15:0] add_ln91_fu_727_p2;
reg   [15:0] add_ln91_reg_1015;
wire   [24:0] mul_ln95_fu_736_p2;
reg   [24:0] mul_ln95_reg_1020;
reg   [60:0] trunc_ln6_reg_1025;
reg   [63:0] v_reg_1036;
wire   [63:0] select_ln99_fu_770_p3;
reg   [63:0] select_ln99_reg_1041;
reg    ap_condition_exit_pp0_iter2_stage0;
reg   [0:0] ap_phi_mux_first_iter_0_phi_fu_269_p4;
wire    ap_loop_init;
wire   [63:0] zext_ln53_fu_492_p1;
wire  signed [63:0] sext_ln95_fu_760_p1;
reg    ap_block_pp0_stage0_01001;
reg   [5:0] b_fu_156;
wire   [5:0] select_ln95_fu_414_p3;
reg   [7:0] px_fu_160;
wire   [7:0] select_ln71_fu_513_p3;
reg   [13:0] indvar_flatten_fu_164;
wire   [13:0] select_ln71_1_fu_428_p3;
reg   [30:0] s_fu_168;
reg   [44:0] indvar_flatten13_fu_172;
wire   [44:0] add_ln46_fu_332_p2;
reg    PV2_COS8_ce0_local;
reg    PV2_SIN8_ce0_local;
wire   [0:0] icmp_ln95_fu_370_p2;
wire   [0:0] xor_ln46_fu_364_p2;
wire   [30:0] add_ln46_1_fu_382_p2;
wire   [0:0] or_ln46_fu_358_p2;
wire   [0:0] or_ln95_fu_408_p2;
wire   [5:0] add_ln95_1_fu_402_p2;
wire   [13:0] add_ln71_1_fu_422_p2;
wire   [31:0] zext_ln50_fu_451_p1;
wire   [31:0] add_ln50_fu_454_p2;
wire   [10:0] grp_fu_464_p1;
wire   [31:0] grp_fu_464_p2;
wire   [9:0] add_ln51_fu_481_p2;
wire   [7:0] select_ln46_fu_500_p3;
wire   [7:0] px_2_fu_507_p2;
wire   [7:0] sub_ln75_fu_534_p2;
wire   [7:0] u_fu_528_p2;
wire   [31:0] grp_fu_277_p2;
wire   [31:0] grp_fu_281_p2;
wire  signed [24:0] sext_ln66_fu_581_p1;
wire  signed [24:0] sext_ln66_1_fu_584_p1;
wire  signed [24:0] grp_fu_782_p3;
wire  signed [24:0] grp_fu_791_p3;
wire  signed [17:0] sext_ln78_1_fu_617_p1;
wire   [17:0] rx_fu_620_p2;
wire  signed [17:0] sext_ln79_1_fu_630_p1;
wire  signed [17:0] rz_fu_633_p2;
wire  signed [24:0] sext_ln79_2_fu_639_p1;
wire   [0:0] tmp_1_fu_653_p3;
wire   [0:0] icmp_ln82_fu_667_p2;
wire   [0:0] xor_ln82_fu_661_p2;
wire   [0:0] and_ln81_fu_673_p2;
wire   [0:0] icmp_ln81_fu_647_p2;
wire   [7:0] vz_fu_691_p3;
wire   [13:0] tmp_2_fu_705_p3;
wire   [15:0] p_shl_fu_697_p3;
wire   [15:0] zext_ln91_fu_713_p1;
wire   [7:0] vx_fu_685_p3;
wire   [15:0] sub_ln91_fu_717_p2;
wire   [15:0] zext_ln91_1_fu_723_p1;
wire   [15:0] mul_ln95_fu_736_p0;
wire   [9:0] mul_ln95_fu_736_p1;
wire   [63:0] zext_ln95_1_fu_742_p1;
wire   [63:0] add_ln95_fu_745_p2;
wire  signed [7:0] grp_fu_782_p1;
wire  signed [24:0] grp_fu_782_p2;
wire  signed [7:0] grp_fu_791_p1;
wire  signed [24:0] grp_fu_791_p2;
reg    grp_fu_277_ce;
reg    grp_fu_281_ce;
reg    grp_fu_464_ce;
reg    grp_fu_782_ce;
reg    grp_fu_791_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg    ap_loop_exit_ready_pp0_iter32_reg;
reg    ap_loop_exit_ready_pp0_iter33_reg;
reg    ap_loop_exit_ready_pp0_iter34_reg;
reg    ap_loop_exit_ready_pp0_iter35_reg;
reg    ap_loop_exit_ready_pp0_iter36_reg;
reg    ap_loop_exit_ready_pp0_iter37_reg;
reg    ap_loop_exit_ready_pp0_iter38_reg;
reg    ap_loop_exit_ready_pp0_iter39_reg;
reg    ap_loop_exit_ready_pp0_iter40_reg;
reg    ap_loop_exit_ready_pp0_iter41_reg;
reg    ap_loop_exit_ready_pp0_iter42_reg;
reg    ap_loop_exit_ready_pp0_iter43_reg;
reg    ap_loop_exit_ready_pp0_iter44_reg;
reg    ap_loop_exit_ready_pp0_iter45_reg;
reg    ap_loop_exit_ready_pp0_iter46_reg;
reg    ap_loop_exit_ready_pp0_iter47_reg;
reg    ap_loop_exit_ready_pp0_iter48_reg;
reg    ap_loop_exit_ready_pp0_iter49_reg;
reg    ap_loop_exit_ready_pp0_iter50_reg;
reg    ap_loop_exit_ready_pp0_iter51_reg;
reg    ap_loop_exit_ready_pp0_iter52_reg;
reg    ap_loop_exit_ready_pp0_iter53_reg;
reg    ap_loop_exit_ready_pp0_iter54_reg;
reg    ap_loop_exit_ready_pp0_iter55_reg;
reg    ap_loop_exit_ready_pp0_iter56_reg;
reg    ap_loop_exit_ready_pp0_iter57_reg;
reg    ap_loop_exit_ready_pp0_iter58_reg;
reg    ap_loop_exit_ready_pp0_iter59_reg;
reg    ap_loop_exit_ready_pp0_iter60_reg;
reg    ap_loop_exit_ready_pp0_iter61_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [24:0] mul_ln95_fu_736_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 ap_enable_reg_pp0_iter36 = 1'b0;
#0 ap_enable_reg_pp0_iter37 = 1'b0;
#0 ap_enable_reg_pp0_iter38 = 1'b0;
#0 ap_enable_reg_pp0_iter39 = 1'b0;
#0 ap_enable_reg_pp0_iter40 = 1'b0;
#0 ap_enable_reg_pp0_iter41 = 1'b0;
#0 ap_enable_reg_pp0_iter42 = 1'b0;
#0 ap_enable_reg_pp0_iter43 = 1'b0;
#0 ap_enable_reg_pp0_iter44 = 1'b0;
#0 ap_enable_reg_pp0_iter45 = 1'b0;
#0 ap_enable_reg_pp0_iter46 = 1'b0;
#0 ap_enable_reg_pp0_iter47 = 1'b0;
#0 ap_enable_reg_pp0_iter48 = 1'b0;
#0 ap_enable_reg_pp0_iter49 = 1'b0;
#0 ap_enable_reg_pp0_iter50 = 1'b0;
#0 ap_enable_reg_pp0_iter51 = 1'b0;
#0 ap_enable_reg_pp0_iter52 = 1'b0;
#0 ap_enable_reg_pp0_iter53 = 1'b0;
#0 ap_enable_reg_pp0_iter54 = 1'b0;
#0 ap_enable_reg_pp0_iter55 = 1'b0;
#0 ap_enable_reg_pp0_iter56 = 1'b0;
#0 ap_enable_reg_pp0_iter57 = 1'b0;
#0 ap_enable_reg_pp0_iter58 = 1'b0;
#0 ap_enable_reg_pp0_iter59 = 1'b0;
#0 ap_enable_reg_pp0_iter60 = 1'b0;
#0 ap_enable_reg_pp0_iter61 = 1'b0;
#0 ap_enable_reg_pp0_iter62 = 1'b0;
#0 b_fu_156 = 6'd0;
#0 px_fu_160 = 8'd0;
#0 indvar_flatten_fu_164 = 14'd0;
#0 s_fu_168 = 31'd0;
#0 indvar_flatten13_fu_172 = 45'd0;
#0 ap_done_reg = 1'b0;
end

pov_eta_wr_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_PV2_COS8_ROM_AUTO_1R #(
    .DataWidth( 10 ),
    .AddressRange( 603 ),
    .AddressWidth( 10 ))
PV2_COS8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(PV2_COS8_address0),
    .ce0(PV2_COS8_ce0_local),
    .q0(PV2_COS8_q0)
);

pov_eta_wr_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN_PV2_SIN8_ROM_AUTO_1R #(
    .DataWidth( 10 ),
    .AddressRange( 603 ),
    .AddressWidth( 10 ))
PV2_SIN8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(PV2_SIN8_address0),
    .ce0(PV2_SIN8_ce0_local),
    .q0(PV2_SIN8_q0)
);

pov_eta_wr_mul_10s_32s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_10s_32s_32_3_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sn_reg_931),
    .din1(axis_off_q8),
    .ce(grp_fu_277_ce),
    .dout(grp_fu_277_p2)
);

pov_eta_wr_mul_10s_32s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_10s_32s_32_3_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(cs_reg_925),
    .din1(axis_off_q8),
    .ce(grp_fu_281_ce),
    .dout(grp_fu_281_p2)
);

pov_eta_wr_srem_32ns_11ns_32_36_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
srem_32ns_11ns_32_36_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln50_1_reg_894),
    .din1(grp_fu_464_p1),
    .ce(grp_fu_464_ce),
    .dout(grp_fu_464_p2)
);

pov_eta_wr_mul_16ns_10ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 25 ))
mul_16ns_10ns_25_1_1_U4(
    .din0(mul_ln95_fu_736_p0),
    .din1(mul_ln95_fu_736_p1),
    .dout(mul_ln95_fu_736_p2)
);

pov_eta_wr_mac_muladd_10s_8s_25s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 25 ),
    .dout_WIDTH( 25 ))
mac_muladd_10s_8s_25s_25_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(cs_reg_925_pp0_iter43_reg),
    .din1(grp_fu_782_p1),
    .din2(grp_fu_782_p2),
    .ce(grp_fu_782_ce),
    .dout(grp_fu_782_p3)
);

pov_eta_wr_mac_muladd_10s_8s_25s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 25 ),
    .dout_WIDTH( 25 ))
mac_muladd_10s_8s_25s_25_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sn_reg_931_pp0_iter43_reg),
    .din1(grp_fu_791_p1),
    .din2(grp_fu_791_p2),
    .ce(grp_fu_791_ce),
    .dout(grp_fu_791_p3)
);

pov_eta_wr_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter61_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter36 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter37 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter37 <= ap_enable_reg_pp0_iter36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter38 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter38 <= ap_enable_reg_pp0_iter37;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter39 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter39 <= ap_enable_reg_pp0_iter38;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter40 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter40 <= ap_enable_reg_pp0_iter39;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter41 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter41 <= ap_enable_reg_pp0_iter40;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter42 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter42 <= ap_enable_reg_pp0_iter41;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter43 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter43 <= ap_enable_reg_pp0_iter42;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter44 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter44 <= ap_enable_reg_pp0_iter43;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter45 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter45 <= ap_enable_reg_pp0_iter44;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter46 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter46 <= ap_enable_reg_pp0_iter45;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter47 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter47 <= ap_enable_reg_pp0_iter46;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter48 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter48 <= ap_enable_reg_pp0_iter47;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter49 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter49 <= ap_enable_reg_pp0_iter48;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter50 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter50 <= ap_enable_reg_pp0_iter49;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter51 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter51 <= ap_enable_reg_pp0_iter50;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter52 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter52 <= ap_enable_reg_pp0_iter51;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter53 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter53 <= ap_enable_reg_pp0_iter52;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter54 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter54 <= ap_enable_reg_pp0_iter53;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter55 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter55 <= ap_enable_reg_pp0_iter54;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter56 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter56 <= ap_enable_reg_pp0_iter55;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter57 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter57 <= ap_enable_reg_pp0_iter56;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter58 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter58 <= ap_enable_reg_pp0_iter57;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter59 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter59 <= ap_enable_reg_pp0_iter58;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter60 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter60 <= ap_enable_reg_pp0_iter59;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter61 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter61 <= ap_enable_reg_pp0_iter60;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter62 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter62 <= ap_enable_reg_pp0_iter61;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            b_fu_156 <= 6'd0;
        end else if (((icmp_ln46_reg_871 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            b_fu_156 <= select_ln95_fu_414_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_reg_871_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        first_iter_0_reg_264 <= 1'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        first_iter_0_reg_264 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten13_fu_172 <= 45'd0;
        end else if (((icmp_ln46_fu_327_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten13_fu_172 <= add_ln46_fu_332_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            indvar_flatten_fu_164 <= 14'd0;
        end else if (((icmp_ln46_reg_871 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            indvar_flatten_fu_164 <= select_ln71_1_fu_428_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            px_fu_160 <= 8'd0;
        end else if (((icmp_ln46_reg_871_pp0_iter42_reg == 1'd0) & (ap_enable_reg_pp0_iter43 == 1'b1))) begin
            px_fu_160 <= select_ln71_fu_513_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            s_fu_168 <= 31'd0;
        end else if (((icmp_ln46_reg_871 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            s_fu_168 <= select_ln46_1_fu_388_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln50_1_reg_894 <= add_ln50_1_fu_459_p2;
        add_ln91_reg_1015 <= add_ln91_fu_727_p2;
        and_ln46_reg_880 <= and_ln46_fu_376_p2;
        and_ln46_reg_880_pp0_iter10_reg <= and_ln46_reg_880_pp0_iter9_reg;
        and_ln46_reg_880_pp0_iter11_reg <= and_ln46_reg_880_pp0_iter10_reg;
        and_ln46_reg_880_pp0_iter12_reg <= and_ln46_reg_880_pp0_iter11_reg;
        and_ln46_reg_880_pp0_iter13_reg <= and_ln46_reg_880_pp0_iter12_reg;
        and_ln46_reg_880_pp0_iter14_reg <= and_ln46_reg_880_pp0_iter13_reg;
        and_ln46_reg_880_pp0_iter15_reg <= and_ln46_reg_880_pp0_iter14_reg;
        and_ln46_reg_880_pp0_iter16_reg <= and_ln46_reg_880_pp0_iter15_reg;
        and_ln46_reg_880_pp0_iter17_reg <= and_ln46_reg_880_pp0_iter16_reg;
        and_ln46_reg_880_pp0_iter18_reg <= and_ln46_reg_880_pp0_iter17_reg;
        and_ln46_reg_880_pp0_iter19_reg <= and_ln46_reg_880_pp0_iter18_reg;
        and_ln46_reg_880_pp0_iter20_reg <= and_ln46_reg_880_pp0_iter19_reg;
        and_ln46_reg_880_pp0_iter21_reg <= and_ln46_reg_880_pp0_iter20_reg;
        and_ln46_reg_880_pp0_iter22_reg <= and_ln46_reg_880_pp0_iter21_reg;
        and_ln46_reg_880_pp0_iter23_reg <= and_ln46_reg_880_pp0_iter22_reg;
        and_ln46_reg_880_pp0_iter24_reg <= and_ln46_reg_880_pp0_iter23_reg;
        and_ln46_reg_880_pp0_iter25_reg <= and_ln46_reg_880_pp0_iter24_reg;
        and_ln46_reg_880_pp0_iter26_reg <= and_ln46_reg_880_pp0_iter25_reg;
        and_ln46_reg_880_pp0_iter27_reg <= and_ln46_reg_880_pp0_iter26_reg;
        and_ln46_reg_880_pp0_iter28_reg <= and_ln46_reg_880_pp0_iter27_reg;
        and_ln46_reg_880_pp0_iter29_reg <= and_ln46_reg_880_pp0_iter28_reg;
        and_ln46_reg_880_pp0_iter30_reg <= and_ln46_reg_880_pp0_iter29_reg;
        and_ln46_reg_880_pp0_iter31_reg <= and_ln46_reg_880_pp0_iter30_reg;
        and_ln46_reg_880_pp0_iter32_reg <= and_ln46_reg_880_pp0_iter31_reg;
        and_ln46_reg_880_pp0_iter33_reg <= and_ln46_reg_880_pp0_iter32_reg;
        and_ln46_reg_880_pp0_iter34_reg <= and_ln46_reg_880_pp0_iter33_reg;
        and_ln46_reg_880_pp0_iter35_reg <= and_ln46_reg_880_pp0_iter34_reg;
        and_ln46_reg_880_pp0_iter36_reg <= and_ln46_reg_880_pp0_iter35_reg;
        and_ln46_reg_880_pp0_iter37_reg <= and_ln46_reg_880_pp0_iter36_reg;
        and_ln46_reg_880_pp0_iter38_reg <= and_ln46_reg_880_pp0_iter37_reg;
        and_ln46_reg_880_pp0_iter39_reg <= and_ln46_reg_880_pp0_iter38_reg;
        and_ln46_reg_880_pp0_iter3_reg <= and_ln46_reg_880;
        and_ln46_reg_880_pp0_iter40_reg <= and_ln46_reg_880_pp0_iter39_reg;
        and_ln46_reg_880_pp0_iter41_reg <= and_ln46_reg_880_pp0_iter40_reg;
        and_ln46_reg_880_pp0_iter42_reg <= and_ln46_reg_880_pp0_iter41_reg;
        and_ln46_reg_880_pp0_iter4_reg <= and_ln46_reg_880_pp0_iter3_reg;
        and_ln46_reg_880_pp0_iter5_reg <= and_ln46_reg_880_pp0_iter4_reg;
        and_ln46_reg_880_pp0_iter6_reg <= and_ln46_reg_880_pp0_iter5_reg;
        and_ln46_reg_880_pp0_iter7_reg <= and_ln46_reg_880_pp0_iter6_reg;
        and_ln46_reg_880_pp0_iter8_reg <= and_ln46_reg_880_pp0_iter7_reg;
        and_ln46_reg_880_pp0_iter9_reg <= and_ln46_reg_880_pp0_iter8_reg;
        angle_1_reg_910 <= angle_1_fu_486_p3;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
        ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
        ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
        ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
        ap_loop_exit_ready_pp0_iter35_reg <= ap_loop_exit_ready_pp0_iter34_reg;
        ap_loop_exit_ready_pp0_iter36_reg <= ap_loop_exit_ready_pp0_iter35_reg;
        ap_loop_exit_ready_pp0_iter37_reg <= ap_loop_exit_ready_pp0_iter36_reg;
        ap_loop_exit_ready_pp0_iter38_reg <= ap_loop_exit_ready_pp0_iter37_reg;
        ap_loop_exit_ready_pp0_iter39_reg <= ap_loop_exit_ready_pp0_iter38_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter40_reg <= ap_loop_exit_ready_pp0_iter39_reg;
        ap_loop_exit_ready_pp0_iter41_reg <= ap_loop_exit_ready_pp0_iter40_reg;
        ap_loop_exit_ready_pp0_iter42_reg <= ap_loop_exit_ready_pp0_iter41_reg;
        ap_loop_exit_ready_pp0_iter43_reg <= ap_loop_exit_ready_pp0_iter42_reg;
        ap_loop_exit_ready_pp0_iter44_reg <= ap_loop_exit_ready_pp0_iter43_reg;
        ap_loop_exit_ready_pp0_iter45_reg <= ap_loop_exit_ready_pp0_iter44_reg;
        ap_loop_exit_ready_pp0_iter46_reg <= ap_loop_exit_ready_pp0_iter45_reg;
        ap_loop_exit_ready_pp0_iter47_reg <= ap_loop_exit_ready_pp0_iter46_reg;
        ap_loop_exit_ready_pp0_iter48_reg <= ap_loop_exit_ready_pp0_iter47_reg;
        ap_loop_exit_ready_pp0_iter49_reg <= ap_loop_exit_ready_pp0_iter48_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter50_reg <= ap_loop_exit_ready_pp0_iter49_reg;
        ap_loop_exit_ready_pp0_iter51_reg <= ap_loop_exit_ready_pp0_iter50_reg;
        ap_loop_exit_ready_pp0_iter52_reg <= ap_loop_exit_ready_pp0_iter51_reg;
        ap_loop_exit_ready_pp0_iter53_reg <= ap_loop_exit_ready_pp0_iter52_reg;
        ap_loop_exit_ready_pp0_iter54_reg <= ap_loop_exit_ready_pp0_iter53_reg;
        ap_loop_exit_ready_pp0_iter55_reg <= ap_loop_exit_ready_pp0_iter54_reg;
        ap_loop_exit_ready_pp0_iter56_reg <= ap_loop_exit_ready_pp0_iter55_reg;
        ap_loop_exit_ready_pp0_iter57_reg <= ap_loop_exit_ready_pp0_iter56_reg;
        ap_loop_exit_ready_pp0_iter58_reg <= ap_loop_exit_ready_pp0_iter57_reg;
        ap_loop_exit_ready_pp0_iter59_reg <= ap_loop_exit_ready_pp0_iter58_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter60_reg <= ap_loop_exit_ready_pp0_iter59_reg;
        ap_loop_exit_ready_pp0_iter61_reg <= ap_loop_exit_ready_pp0_iter60_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        cs_reg_925 <= PV2_COS8_q0;
        cs_reg_925_pp0_iter43_reg <= cs_reg_925;
        first_iter_0_mid2_reg_890 <= first_iter_0_mid2_fu_396_p2;
        first_iter_0_mid2_reg_890_pp0_iter10_reg <= first_iter_0_mid2_reg_890_pp0_iter9_reg;
        first_iter_0_mid2_reg_890_pp0_iter11_reg <= first_iter_0_mid2_reg_890_pp0_iter10_reg;
        first_iter_0_mid2_reg_890_pp0_iter12_reg <= first_iter_0_mid2_reg_890_pp0_iter11_reg;
        first_iter_0_mid2_reg_890_pp0_iter13_reg <= first_iter_0_mid2_reg_890_pp0_iter12_reg;
        first_iter_0_mid2_reg_890_pp0_iter14_reg <= first_iter_0_mid2_reg_890_pp0_iter13_reg;
        first_iter_0_mid2_reg_890_pp0_iter15_reg <= first_iter_0_mid2_reg_890_pp0_iter14_reg;
        first_iter_0_mid2_reg_890_pp0_iter16_reg <= first_iter_0_mid2_reg_890_pp0_iter15_reg;
        first_iter_0_mid2_reg_890_pp0_iter17_reg <= first_iter_0_mid2_reg_890_pp0_iter16_reg;
        first_iter_0_mid2_reg_890_pp0_iter18_reg <= first_iter_0_mid2_reg_890_pp0_iter17_reg;
        first_iter_0_mid2_reg_890_pp0_iter19_reg <= first_iter_0_mid2_reg_890_pp0_iter18_reg;
        first_iter_0_mid2_reg_890_pp0_iter20_reg <= first_iter_0_mid2_reg_890_pp0_iter19_reg;
        first_iter_0_mid2_reg_890_pp0_iter21_reg <= first_iter_0_mid2_reg_890_pp0_iter20_reg;
        first_iter_0_mid2_reg_890_pp0_iter22_reg <= first_iter_0_mid2_reg_890_pp0_iter21_reg;
        first_iter_0_mid2_reg_890_pp0_iter23_reg <= first_iter_0_mid2_reg_890_pp0_iter22_reg;
        first_iter_0_mid2_reg_890_pp0_iter24_reg <= first_iter_0_mid2_reg_890_pp0_iter23_reg;
        first_iter_0_mid2_reg_890_pp0_iter25_reg <= first_iter_0_mid2_reg_890_pp0_iter24_reg;
        first_iter_0_mid2_reg_890_pp0_iter26_reg <= first_iter_0_mid2_reg_890_pp0_iter25_reg;
        first_iter_0_mid2_reg_890_pp0_iter27_reg <= first_iter_0_mid2_reg_890_pp0_iter26_reg;
        first_iter_0_mid2_reg_890_pp0_iter28_reg <= first_iter_0_mid2_reg_890_pp0_iter27_reg;
        first_iter_0_mid2_reg_890_pp0_iter29_reg <= first_iter_0_mid2_reg_890_pp0_iter28_reg;
        first_iter_0_mid2_reg_890_pp0_iter30_reg <= first_iter_0_mid2_reg_890_pp0_iter29_reg;
        first_iter_0_mid2_reg_890_pp0_iter31_reg <= first_iter_0_mid2_reg_890_pp0_iter30_reg;
        first_iter_0_mid2_reg_890_pp0_iter32_reg <= first_iter_0_mid2_reg_890_pp0_iter31_reg;
        first_iter_0_mid2_reg_890_pp0_iter33_reg <= first_iter_0_mid2_reg_890_pp0_iter32_reg;
        first_iter_0_mid2_reg_890_pp0_iter34_reg <= first_iter_0_mid2_reg_890_pp0_iter33_reg;
        first_iter_0_mid2_reg_890_pp0_iter35_reg <= first_iter_0_mid2_reg_890_pp0_iter34_reg;
        first_iter_0_mid2_reg_890_pp0_iter36_reg <= first_iter_0_mid2_reg_890_pp0_iter35_reg;
        first_iter_0_mid2_reg_890_pp0_iter37_reg <= first_iter_0_mid2_reg_890_pp0_iter36_reg;
        first_iter_0_mid2_reg_890_pp0_iter38_reg <= first_iter_0_mid2_reg_890_pp0_iter37_reg;
        first_iter_0_mid2_reg_890_pp0_iter39_reg <= first_iter_0_mid2_reg_890_pp0_iter38_reg;
        first_iter_0_mid2_reg_890_pp0_iter3_reg <= first_iter_0_mid2_reg_890;
        first_iter_0_mid2_reg_890_pp0_iter40_reg <= first_iter_0_mid2_reg_890_pp0_iter39_reg;
        first_iter_0_mid2_reg_890_pp0_iter41_reg <= first_iter_0_mid2_reg_890_pp0_iter40_reg;
        first_iter_0_mid2_reg_890_pp0_iter42_reg <= first_iter_0_mid2_reg_890_pp0_iter41_reg;
        first_iter_0_mid2_reg_890_pp0_iter43_reg <= first_iter_0_mid2_reg_890_pp0_iter42_reg;
        first_iter_0_mid2_reg_890_pp0_iter44_reg <= first_iter_0_mid2_reg_890_pp0_iter43_reg;
        first_iter_0_mid2_reg_890_pp0_iter45_reg <= first_iter_0_mid2_reg_890_pp0_iter44_reg;
        first_iter_0_mid2_reg_890_pp0_iter46_reg <= first_iter_0_mid2_reg_890_pp0_iter45_reg;
        first_iter_0_mid2_reg_890_pp0_iter47_reg <= first_iter_0_mid2_reg_890_pp0_iter46_reg;
        first_iter_0_mid2_reg_890_pp0_iter48_reg <= first_iter_0_mid2_reg_890_pp0_iter47_reg;
        first_iter_0_mid2_reg_890_pp0_iter49_reg <= first_iter_0_mid2_reg_890_pp0_iter48_reg;
        first_iter_0_mid2_reg_890_pp0_iter4_reg <= first_iter_0_mid2_reg_890_pp0_iter3_reg;
        first_iter_0_mid2_reg_890_pp0_iter50_reg <= first_iter_0_mid2_reg_890_pp0_iter49_reg;
        first_iter_0_mid2_reg_890_pp0_iter51_reg <= first_iter_0_mid2_reg_890_pp0_iter50_reg;
        first_iter_0_mid2_reg_890_pp0_iter5_reg <= first_iter_0_mid2_reg_890_pp0_iter4_reg;
        first_iter_0_mid2_reg_890_pp0_iter6_reg <= first_iter_0_mid2_reg_890_pp0_iter5_reg;
        first_iter_0_mid2_reg_890_pp0_iter7_reg <= first_iter_0_mid2_reg_890_pp0_iter6_reg;
        first_iter_0_mid2_reg_890_pp0_iter8_reg <= first_iter_0_mid2_reg_890_pp0_iter7_reg;
        first_iter_0_mid2_reg_890_pp0_iter9_reg <= first_iter_0_mid2_reg_890_pp0_iter8_reg;
        icmp_ln46_reg_871_pp0_iter10_reg <= icmp_ln46_reg_871_pp0_iter9_reg;
        icmp_ln46_reg_871_pp0_iter11_reg <= icmp_ln46_reg_871_pp0_iter10_reg;
        icmp_ln46_reg_871_pp0_iter12_reg <= icmp_ln46_reg_871_pp0_iter11_reg;
        icmp_ln46_reg_871_pp0_iter13_reg <= icmp_ln46_reg_871_pp0_iter12_reg;
        icmp_ln46_reg_871_pp0_iter14_reg <= icmp_ln46_reg_871_pp0_iter13_reg;
        icmp_ln46_reg_871_pp0_iter15_reg <= icmp_ln46_reg_871_pp0_iter14_reg;
        icmp_ln46_reg_871_pp0_iter16_reg <= icmp_ln46_reg_871_pp0_iter15_reg;
        icmp_ln46_reg_871_pp0_iter17_reg <= icmp_ln46_reg_871_pp0_iter16_reg;
        icmp_ln46_reg_871_pp0_iter18_reg <= icmp_ln46_reg_871_pp0_iter17_reg;
        icmp_ln46_reg_871_pp0_iter19_reg <= icmp_ln46_reg_871_pp0_iter18_reg;
        icmp_ln46_reg_871_pp0_iter20_reg <= icmp_ln46_reg_871_pp0_iter19_reg;
        icmp_ln46_reg_871_pp0_iter21_reg <= icmp_ln46_reg_871_pp0_iter20_reg;
        icmp_ln46_reg_871_pp0_iter22_reg <= icmp_ln46_reg_871_pp0_iter21_reg;
        icmp_ln46_reg_871_pp0_iter23_reg <= icmp_ln46_reg_871_pp0_iter22_reg;
        icmp_ln46_reg_871_pp0_iter24_reg <= icmp_ln46_reg_871_pp0_iter23_reg;
        icmp_ln46_reg_871_pp0_iter25_reg <= icmp_ln46_reg_871_pp0_iter24_reg;
        icmp_ln46_reg_871_pp0_iter26_reg <= icmp_ln46_reg_871_pp0_iter25_reg;
        icmp_ln46_reg_871_pp0_iter27_reg <= icmp_ln46_reg_871_pp0_iter26_reg;
        icmp_ln46_reg_871_pp0_iter28_reg <= icmp_ln46_reg_871_pp0_iter27_reg;
        icmp_ln46_reg_871_pp0_iter29_reg <= icmp_ln46_reg_871_pp0_iter28_reg;
        icmp_ln46_reg_871_pp0_iter2_reg <= icmp_ln46_reg_871;
        icmp_ln46_reg_871_pp0_iter30_reg <= icmp_ln46_reg_871_pp0_iter29_reg;
        icmp_ln46_reg_871_pp0_iter31_reg <= icmp_ln46_reg_871_pp0_iter30_reg;
        icmp_ln46_reg_871_pp0_iter32_reg <= icmp_ln46_reg_871_pp0_iter31_reg;
        icmp_ln46_reg_871_pp0_iter33_reg <= icmp_ln46_reg_871_pp0_iter32_reg;
        icmp_ln46_reg_871_pp0_iter34_reg <= icmp_ln46_reg_871_pp0_iter33_reg;
        icmp_ln46_reg_871_pp0_iter35_reg <= icmp_ln46_reg_871_pp0_iter34_reg;
        icmp_ln46_reg_871_pp0_iter36_reg <= icmp_ln46_reg_871_pp0_iter35_reg;
        icmp_ln46_reg_871_pp0_iter37_reg <= icmp_ln46_reg_871_pp0_iter36_reg;
        icmp_ln46_reg_871_pp0_iter38_reg <= icmp_ln46_reg_871_pp0_iter37_reg;
        icmp_ln46_reg_871_pp0_iter39_reg <= icmp_ln46_reg_871_pp0_iter38_reg;
        icmp_ln46_reg_871_pp0_iter3_reg <= icmp_ln46_reg_871_pp0_iter2_reg;
        icmp_ln46_reg_871_pp0_iter40_reg <= icmp_ln46_reg_871_pp0_iter39_reg;
        icmp_ln46_reg_871_pp0_iter41_reg <= icmp_ln46_reg_871_pp0_iter40_reg;
        icmp_ln46_reg_871_pp0_iter42_reg <= icmp_ln46_reg_871_pp0_iter41_reg;
        icmp_ln46_reg_871_pp0_iter43_reg <= icmp_ln46_reg_871_pp0_iter42_reg;
        icmp_ln46_reg_871_pp0_iter44_reg <= icmp_ln46_reg_871_pp0_iter43_reg;
        icmp_ln46_reg_871_pp0_iter45_reg <= icmp_ln46_reg_871_pp0_iter44_reg;
        icmp_ln46_reg_871_pp0_iter46_reg <= icmp_ln46_reg_871_pp0_iter45_reg;
        icmp_ln46_reg_871_pp0_iter47_reg <= icmp_ln46_reg_871_pp0_iter46_reg;
        icmp_ln46_reg_871_pp0_iter48_reg <= icmp_ln46_reg_871_pp0_iter47_reg;
        icmp_ln46_reg_871_pp0_iter49_reg <= icmp_ln46_reg_871_pp0_iter48_reg;
        icmp_ln46_reg_871_pp0_iter4_reg <= icmp_ln46_reg_871_pp0_iter3_reg;
        icmp_ln46_reg_871_pp0_iter50_reg <= icmp_ln46_reg_871_pp0_iter49_reg;
        icmp_ln46_reg_871_pp0_iter51_reg <= icmp_ln46_reg_871_pp0_iter50_reg;
        icmp_ln46_reg_871_pp0_iter52_reg <= icmp_ln46_reg_871_pp0_iter51_reg;
        icmp_ln46_reg_871_pp0_iter53_reg <= icmp_ln46_reg_871_pp0_iter52_reg;
        icmp_ln46_reg_871_pp0_iter54_reg <= icmp_ln46_reg_871_pp0_iter53_reg;
        icmp_ln46_reg_871_pp0_iter55_reg <= icmp_ln46_reg_871_pp0_iter54_reg;
        icmp_ln46_reg_871_pp0_iter56_reg <= icmp_ln46_reg_871_pp0_iter55_reg;
        icmp_ln46_reg_871_pp0_iter57_reg <= icmp_ln46_reg_871_pp0_iter56_reg;
        icmp_ln46_reg_871_pp0_iter58_reg <= icmp_ln46_reg_871_pp0_iter57_reg;
        icmp_ln46_reg_871_pp0_iter59_reg <= icmp_ln46_reg_871_pp0_iter58_reg;
        icmp_ln46_reg_871_pp0_iter5_reg <= icmp_ln46_reg_871_pp0_iter4_reg;
        icmp_ln46_reg_871_pp0_iter60_reg <= icmp_ln46_reg_871_pp0_iter59_reg;
        icmp_ln46_reg_871_pp0_iter61_reg <= icmp_ln46_reg_871_pp0_iter60_reg;
        icmp_ln46_reg_871_pp0_iter6_reg <= icmp_ln46_reg_871_pp0_iter5_reg;
        icmp_ln46_reg_871_pp0_iter7_reg <= icmp_ln46_reg_871_pp0_iter6_reg;
        icmp_ln46_reg_871_pp0_iter8_reg <= icmp_ln46_reg_871_pp0_iter7_reg;
        icmp_ln46_reg_871_pp0_iter9_reg <= icmp_ln46_reg_871_pp0_iter8_reg;
        icmp_ln71_reg_875 <= icmp_ln71_fu_352_p2;
        icmp_ln71_reg_875_pp0_iter10_reg <= icmp_ln71_reg_875_pp0_iter9_reg;
        icmp_ln71_reg_875_pp0_iter11_reg <= icmp_ln71_reg_875_pp0_iter10_reg;
        icmp_ln71_reg_875_pp0_iter12_reg <= icmp_ln71_reg_875_pp0_iter11_reg;
        icmp_ln71_reg_875_pp0_iter13_reg <= icmp_ln71_reg_875_pp0_iter12_reg;
        icmp_ln71_reg_875_pp0_iter14_reg <= icmp_ln71_reg_875_pp0_iter13_reg;
        icmp_ln71_reg_875_pp0_iter15_reg <= icmp_ln71_reg_875_pp0_iter14_reg;
        icmp_ln71_reg_875_pp0_iter16_reg <= icmp_ln71_reg_875_pp0_iter15_reg;
        icmp_ln71_reg_875_pp0_iter17_reg <= icmp_ln71_reg_875_pp0_iter16_reg;
        icmp_ln71_reg_875_pp0_iter18_reg <= icmp_ln71_reg_875_pp0_iter17_reg;
        icmp_ln71_reg_875_pp0_iter19_reg <= icmp_ln71_reg_875_pp0_iter18_reg;
        icmp_ln71_reg_875_pp0_iter20_reg <= icmp_ln71_reg_875_pp0_iter19_reg;
        icmp_ln71_reg_875_pp0_iter21_reg <= icmp_ln71_reg_875_pp0_iter20_reg;
        icmp_ln71_reg_875_pp0_iter22_reg <= icmp_ln71_reg_875_pp0_iter21_reg;
        icmp_ln71_reg_875_pp0_iter23_reg <= icmp_ln71_reg_875_pp0_iter22_reg;
        icmp_ln71_reg_875_pp0_iter24_reg <= icmp_ln71_reg_875_pp0_iter23_reg;
        icmp_ln71_reg_875_pp0_iter25_reg <= icmp_ln71_reg_875_pp0_iter24_reg;
        icmp_ln71_reg_875_pp0_iter26_reg <= icmp_ln71_reg_875_pp0_iter25_reg;
        icmp_ln71_reg_875_pp0_iter27_reg <= icmp_ln71_reg_875_pp0_iter26_reg;
        icmp_ln71_reg_875_pp0_iter28_reg <= icmp_ln71_reg_875_pp0_iter27_reg;
        icmp_ln71_reg_875_pp0_iter29_reg <= icmp_ln71_reg_875_pp0_iter28_reg;
        icmp_ln71_reg_875_pp0_iter30_reg <= icmp_ln71_reg_875_pp0_iter29_reg;
        icmp_ln71_reg_875_pp0_iter31_reg <= icmp_ln71_reg_875_pp0_iter30_reg;
        icmp_ln71_reg_875_pp0_iter32_reg <= icmp_ln71_reg_875_pp0_iter31_reg;
        icmp_ln71_reg_875_pp0_iter33_reg <= icmp_ln71_reg_875_pp0_iter32_reg;
        icmp_ln71_reg_875_pp0_iter34_reg <= icmp_ln71_reg_875_pp0_iter33_reg;
        icmp_ln71_reg_875_pp0_iter35_reg <= icmp_ln71_reg_875_pp0_iter34_reg;
        icmp_ln71_reg_875_pp0_iter36_reg <= icmp_ln71_reg_875_pp0_iter35_reg;
        icmp_ln71_reg_875_pp0_iter37_reg <= icmp_ln71_reg_875_pp0_iter36_reg;
        icmp_ln71_reg_875_pp0_iter38_reg <= icmp_ln71_reg_875_pp0_iter37_reg;
        icmp_ln71_reg_875_pp0_iter39_reg <= icmp_ln71_reg_875_pp0_iter38_reg;
        icmp_ln71_reg_875_pp0_iter3_reg <= icmp_ln71_reg_875;
        icmp_ln71_reg_875_pp0_iter40_reg <= icmp_ln71_reg_875_pp0_iter39_reg;
        icmp_ln71_reg_875_pp0_iter41_reg <= icmp_ln71_reg_875_pp0_iter40_reg;
        icmp_ln71_reg_875_pp0_iter42_reg <= icmp_ln71_reg_875_pp0_iter41_reg;
        icmp_ln71_reg_875_pp0_iter4_reg <= icmp_ln71_reg_875_pp0_iter3_reg;
        icmp_ln71_reg_875_pp0_iter5_reg <= icmp_ln71_reg_875_pp0_iter4_reg;
        icmp_ln71_reg_875_pp0_iter6_reg <= icmp_ln71_reg_875_pp0_iter5_reg;
        icmp_ln71_reg_875_pp0_iter7_reg <= icmp_ln71_reg_875_pp0_iter6_reg;
        icmp_ln71_reg_875_pp0_iter8_reg <= icmp_ln71_reg_875_pp0_iter7_reg;
        icmp_ln71_reg_875_pp0_iter9_reg <= icmp_ln71_reg_875_pp0_iter8_reg;
        inside_reg_1008 <= inside_fu_679_p2;
        inside_reg_1008_pp0_iter49_reg <= inside_reg_1008;
        inside_reg_1008_pp0_iter50_reg <= inside_reg_1008_pp0_iter49_reg;
        inside_reg_1008_pp0_iter51_reg <= inside_reg_1008_pp0_iter50_reg;
        inside_reg_1008_pp0_iter52_reg <= inside_reg_1008_pp0_iter51_reg;
        inside_reg_1008_pp0_iter53_reg <= inside_reg_1008_pp0_iter52_reg;
        inside_reg_1008_pp0_iter54_reg <= inside_reg_1008_pp0_iter53_reg;
        inside_reg_1008_pp0_iter55_reg <= inside_reg_1008_pp0_iter54_reg;
        inside_reg_1008_pp0_iter56_reg <= inside_reg_1008_pp0_iter55_reg;
        inside_reg_1008_pp0_iter57_reg <= inside_reg_1008_pp0_iter56_reg;
        inside_reg_1008_pp0_iter58_reg <= inside_reg_1008_pp0_iter57_reg;
        inside_reg_1008_pp0_iter59_reg <= inside_reg_1008_pp0_iter58_reg;
        inside_reg_1008_pp0_iter60_reg <= inside_reg_1008_pp0_iter59_reg;
        mul_ln95_reg_1020 <= mul_ln95_fu_736_p2;
        off_z_q8_reg_973 <= {{grp_fu_281_p2[31:8]}};
        select_ln46_1_reg_885 <= select_ln46_1_fu_388_p3;
        select_ln99_reg_1041 <= select_ln99_fu_770_p3;
        sn_reg_931 <= PV2_SIN8_q0;
        sn_reg_931_pp0_iter43_reg <= sn_reg_931;
        tmp_reg_905 <= grp_fu_464_p2[32'd10];
        trunc_ln3_reg_968 <= {{grp_fu_277_p2[31:8]}};
        trunc_ln4_reg_988 <= {{grp_fu_782_p3[24:8]}};
        trunc_ln50_reg_899 <= trunc_ln50_fu_469_p1;
        trunc_ln5_reg_993 <= {{grp_fu_791_p3[24:8]}};
        trunc_ln6_reg_1025 <= {{add_ln95_fu_745_p2[63:3]}};
        trunc_ln78_reg_998 <= trunc_ln78_fu_626_p1;
        trunc_ln79_reg_1003 <= trunc_ln79_fu_643_p1;
        u_1_reg_947 <= u_1_fu_540_p3;
        v_reg_1036 <= m_axi_vox_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln46_reg_871 <= icmp_ln46_fu_327_p2;
        tobool_reg_866 <= tobool_fu_293_p2;
        zext_ln18_cast_reg_856[30 : 0] <= zext_ln18_cast_fu_285_p1[30 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter41 == 1'b1))) begin
        PV2_COS8_ce0_local = 1'b1;
    end else begin
        PV2_COS8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter41 == 1'b1))) begin
        PV2_SIN8_ce0_local = 1'b1;
    end else begin
        PV2_SIN8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln46_fu_327_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln46_reg_871 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter61_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter62 == 1'b0) 
    & (ap_enable_reg_pp0_iter61 == 1'b0) & (ap_enable_reg_pp0_iter60 == 1'b0) & (ap_enable_reg_pp0_iter59 == 1'b0) & (ap_enable_reg_pp0_iter58 == 1'b0) & (ap_enable_reg_pp0_iter57 == 1'b0) & (ap_enable_reg_pp0_iter56 == 1'b0) & (ap_enable_reg_pp0_iter55 == 1'b0) & (ap_enable_reg_pp0_iter54 == 1'b0) & (ap_enable_reg_pp0_iter53 == 1'b0) & (ap_enable_reg_pp0_iter52 == 1'b0) & (ap_enable_reg_pp0_iter51 == 1'b0) & (ap_enable_reg_pp0_iter50 == 1'b0) & (ap_enable_reg_pp0_iter49 == 1'b0) & (ap_enable_reg_pp0_iter48 == 1'b0) & (ap_enable_reg_pp0_iter47 == 1'b0) & (ap_enable_reg_pp0_iter46 == 1'b0) & (ap_enable_reg_pp0_iter45 == 1'b0) & (ap_enable_reg_pp0_iter44 == 1'b0) & (ap_enable_reg_pp0_iter43 == 1'b0) & (ap_enable_reg_pp0_iter42 == 1'b0) & (ap_enable_reg_pp0_iter41 == 1'b0) & (ap_enable_reg_pp0_iter40 == 1'b0) & (ap_enable_reg_pp0_iter39 == 1'b0) & (ap_enable_reg_pp0_iter38 == 1'b0) & (ap_enable_reg_pp0_iter37 == 1'b0) & (ap_enable_reg_pp0_iter36 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 
    == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln46_reg_871_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_phi_mux_first_iter_0_phi_fu_269_p4 = 1'd0;
    end else begin
        ap_phi_mux_first_iter_0_phi_fu_269_p4 = first_iter_0_reg_264;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_277_ce = 1'b1;
    end else begin
        grp_fu_277_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_281_ce = 1'b1;
    end else begin
        grp_fu_281_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_464_ce = 1'b1;
    end else begin
        grp_fu_464_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_782_ce = 1'b1;
    end else begin
        grp_fu_782_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_791_ce = 1'b1;
    end else begin
        grp_fu_791_ce = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln46_reg_871_pp0_iter61_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter62 == 1'b1))) begin
        m_axi_out_r_0_WVALID = 1'b1;
    end else begin
        m_axi_out_r_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op234_readreq_state53 == 1'b1) & (ap_enable_reg_pp0_iter52 == 1'b1))) begin
        m_axi_vox_0_ARVALID = 1'b1;
    end else begin
        m_axi_vox_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op243_read_state61 == 1'b1) & (ap_enable_reg_pp0_iter60 == 1'b1))) begin
        m_axi_vox_0_RREADY = 1'b1;
    end else begin
        m_axi_vox_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln46_reg_871_pp0_iter61_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter62 == 1'b1))) begin
        out_r_blk_n_W = m_axi_out_r_0_WREADY;
    end else begin
        out_r_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op234_readreq_state53 == 1'b1) & (ap_enable_reg_pp0_iter52 == 1'b1))) begin
        vox_blk_n_AR = m_axi_vox_0_ARREADY;
    end else begin
        vox_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op243_read_state61 == 1'b1) & (ap_enable_reg_pp0_iter60 == 1'b1))) begin
        vox_blk_n_R = m_axi_vox_0_RVALID;
    end else begin
        vox_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign PV2_COS8_address0 = zext_ln53_fu_492_p1;

assign PV2_SIN8_address0 = zext_ln53_fu_492_p1;

assign add_ln46_1_fu_382_p2 = (s_fu_168 + 31'd1);

assign add_ln46_fu_332_p2 = (indvar_flatten13_fu_172 + 45'd1);

assign add_ln50_1_fu_459_p2 = (add_ln50_fu_454_p2 + zext_ln18_cast_reg_856);

assign add_ln50_fu_454_p2 = (zext_ln50_fu_451_p1 + phase);

assign add_ln51_fu_481_p2 = ($signed(trunc_ln50_reg_899) + $signed(10'd603));

assign add_ln71_1_fu_422_p2 = (indvar_flatten_fu_164 + 14'd1);

assign add_ln91_fu_727_p2 = (sub_ln91_fu_717_p2 + zext_ln91_1_fu_723_p1);

assign add_ln95_1_fu_402_p2 = (b_fu_156 + 6'd1);

assign add_ln95_fu_745_p2 = (zext_ln95_1_fu_742_p1 + voxel);

assign and_ln46_fu_376_p2 = (xor_ln46_fu_364_p2 & icmp_ln95_fu_370_p2);

assign and_ln81_fu_673_p2 = (xor_ln82_fu_661_p2 & icmp_ln82_fu_667_p2);

assign angle_1_fu_486_p3 = ((tmp_reg_905[0:0] == 1'b1) ? add_ln51_fu_481_p2 : trunc_ln50_reg_899);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter60 == 1'b1) & (1'b1 == ap_block_state61_pp0_stage0_iter60));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter62 == 1'b1) & (1'b1 == ap_block_state63_io)) | ((ap_enable_reg_pp0_iter60 == 1'b1) & (1'b1 == ap_block_state61_pp0_stage0_iter60)) | ((ap_enable_reg_pp0_iter52 == 1'b1) & (1'b1 == ap_block_state53_io)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter62 == 1'b1) & (1'b1 == ap_block_state63_io)) | ((ap_enable_reg_pp0_iter60 == 1'b1) & (1'b1 == ap_block_state61_pp0_stage0_iter60)) | ((ap_enable_reg_pp0_iter52 == 1'b1) & (1'b1 == ap_block_state53_io)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state53_io = ((ap_predicate_op234_readreq_state53 == 1'b1) & (m_axi_vox_0_ARREADY == 1'b0));
end

always @ (*) begin
    ap_block_state61_pp0_stage0_iter60 = ((ap_predicate_op243_read_state61 == 1'b1) & (m_axi_vox_0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state63_io = ((icmp_ln46_reg_871_pp0_iter61_reg == 1'd0) & (m_axi_out_r_0_WREADY == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

always @ (*) begin
    ap_predicate_op234_readreq_state53 = ((inside_reg_1008_pp0_iter51_reg == 1'd1) & (first_iter_0_mid2_reg_890_pp0_iter51_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op243_read_state61 = ((inside_reg_1008_pp0_iter59_reg == 1'd1) & (icmp_ln46_reg_871_pp0_iter59_reg == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign first_iter_0_mid2_fu_396_p2 = (or_ln46_fu_358_p2 | and_ln46_fu_376_p2);

assign grp_fu_464_p1 = 32'd603;

assign grp_fu_782_p1 = sext_ln74_fu_558_p1;

assign grp_fu_782_p2 = ($signed(25'd128) - $signed(sext_ln66_fu_581_p1));

assign grp_fu_791_p1 = sext_ln74_fu_558_p1;

assign grp_fu_791_p2 = ($signed(sext_ln66_1_fu_584_p1) + $signed(25'd128));

assign icmp_ln46_fu_327_p2 = ((indvar_flatten13_fu_172 == mul_ln14) ? 1'b1 : 1'b0);

assign icmp_ln71_fu_352_p2 = ((indvar_flatten_fu_164 == 14'd10368) ? 1'b1 : 1'b0);

assign icmp_ln81_fu_647_p2 = ((rx_fu_620_p2 < 18'd192) ? 1'b1 : 1'b0);

assign icmp_ln82_fu_667_p2 = (($signed(rz_fu_633_p2) < $signed(18'd192)) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_370_p2 = ((b_fu_156 == 6'd54) ? 1'b1 : 1'b0);

assign inside_fu_679_p2 = (icmp_ln81_fu_647_p2 & and_ln81_fu_673_p2);

assign m_axi_out_r_0_ARADDR = 64'd0;

assign m_axi_out_r_0_ARBURST = 2'd0;

assign m_axi_out_r_0_ARCACHE = 4'd0;

assign m_axi_out_r_0_ARID = 1'd0;

assign m_axi_out_r_0_ARLEN = 32'd0;

assign m_axi_out_r_0_ARLOCK = 2'd0;

assign m_axi_out_r_0_ARPROT = 3'd0;

assign m_axi_out_r_0_ARQOS = 4'd0;

assign m_axi_out_r_0_ARREGION = 4'd0;

assign m_axi_out_r_0_ARSIZE = 3'd0;

assign m_axi_out_r_0_ARUSER = 1'd0;

assign m_axi_out_r_0_ARVALID = 1'b0;

assign m_axi_out_r_0_AWADDR = 64'd0;

assign m_axi_out_r_0_AWBURST = 2'd0;

assign m_axi_out_r_0_AWCACHE = 4'd0;

assign m_axi_out_r_0_AWID = 1'd0;

assign m_axi_out_r_0_AWLEN = 32'd0;

assign m_axi_out_r_0_AWLOCK = 2'd0;

assign m_axi_out_r_0_AWPROT = 3'd0;

assign m_axi_out_r_0_AWQOS = 4'd0;

assign m_axi_out_r_0_AWREGION = 4'd0;

assign m_axi_out_r_0_AWSIZE = 3'd0;

assign m_axi_out_r_0_AWUSER = 1'd0;

assign m_axi_out_r_0_AWVALID = 1'b0;

assign m_axi_out_r_0_BREADY = 1'b0;

assign m_axi_out_r_0_RREADY = 1'b0;

assign m_axi_out_r_0_WDATA = select_ln99_reg_1041;

assign m_axi_out_r_0_WID = 1'd0;

assign m_axi_out_r_0_WLAST = 1'b0;

assign m_axi_out_r_0_WSTRB = 8'd255;

assign m_axi_out_r_0_WUSER = 1'd0;

assign m_axi_vox_0_ARADDR = sext_ln95_fu_760_p1;

assign m_axi_vox_0_ARBURST = 2'd0;

assign m_axi_vox_0_ARCACHE = 4'd0;

assign m_axi_vox_0_ARID = 1'd0;

assign m_axi_vox_0_ARLEN = 64'd54;

assign m_axi_vox_0_ARLOCK = 2'd0;

assign m_axi_vox_0_ARPROT = 3'd0;

assign m_axi_vox_0_ARQOS = 4'd0;

assign m_axi_vox_0_ARREGION = 4'd0;

assign m_axi_vox_0_ARSIZE = 3'd0;

assign m_axi_vox_0_ARUSER = 1'd0;

assign m_axi_vox_0_AWADDR = 64'd0;

assign m_axi_vox_0_AWBURST = 2'd0;

assign m_axi_vox_0_AWCACHE = 4'd0;

assign m_axi_vox_0_AWID = 1'd0;

assign m_axi_vox_0_AWLEN = 32'd0;

assign m_axi_vox_0_AWLOCK = 2'd0;

assign m_axi_vox_0_AWPROT = 3'd0;

assign m_axi_vox_0_AWQOS = 4'd0;

assign m_axi_vox_0_AWREGION = 4'd0;

assign m_axi_vox_0_AWSIZE = 3'd0;

assign m_axi_vox_0_AWUSER = 1'd0;

assign m_axi_vox_0_AWVALID = 1'b0;

assign m_axi_vox_0_BREADY = 1'b0;

assign m_axi_vox_0_WDATA = 64'd0;

assign m_axi_vox_0_WID = 1'd0;

assign m_axi_vox_0_WLAST = 1'b0;

assign m_axi_vox_0_WSTRB = 8'd0;

assign m_axi_vox_0_WUSER = 1'd0;

assign m_axi_vox_0_WVALID = 1'b0;

assign mul_ln95_fu_736_p0 = mul_ln95_fu_736_p00;

assign mul_ln95_fu_736_p00 = add_ln91_reg_1015;

assign mul_ln95_fu_736_p1 = 25'd432;

assign or_ln46_fu_358_p2 = (icmp_ln71_fu_352_p2 | ap_phi_mux_first_iter_0_phi_fu_269_p4);

assign or_ln95_fu_408_p2 = (icmp_ln71_fu_352_p2 | and_ln46_fu_376_p2);

assign p_shl_fu_697_p3 = {{vz_fu_691_p3}, {8'd0}};

assign px_2_fu_507_p2 = (select_ln46_fu_500_p3 + 8'd1);

assign rx_fu_620_p2 = ($signed(sext_ln78_1_fu_617_p1) + $signed(18'd96));

assign rz_fu_633_p2 = ($signed(sext_ln79_1_fu_630_p1) + $signed(18'd96));

assign select_ln46_1_fu_388_p3 = ((icmp_ln71_fu_352_p2[0:0] == 1'b1) ? add_ln46_1_fu_382_p2 : s_fu_168);

assign select_ln46_fu_500_p3 = ((icmp_ln71_reg_875_pp0_iter42_reg[0:0] == 1'b1) ? 8'd0 : px_fu_160);

assign select_ln71_1_fu_428_p3 = ((icmp_ln71_fu_352_p2[0:0] == 1'b1) ? 14'd1 : add_ln71_1_fu_422_p2);

assign select_ln71_fu_513_p3 = ((and_ln46_reg_880_pp0_iter42_reg[0:0] == 1'b1) ? px_2_fu_507_p2 : select_ln46_fu_500_p3);

assign select_ln95_fu_414_p3 = ((or_ln95_fu_408_p2[0:0] == 1'b1) ? 6'd1 : add_ln95_1_fu_402_p2);

assign select_ln99_fu_770_p3 = ((inside_reg_1008_pp0_iter60_reg[0:0] == 1'b1) ? v_reg_1036 : 64'd0);

assign sext_ln66_1_fu_584_p1 = $signed(off_z_q8_reg_973);

assign sext_ln66_fu_581_p1 = $signed(trunc_ln3_reg_968);

assign sext_ln74_fu_558_p1 = $signed(u_1_reg_947);

assign sext_ln78_1_fu_617_p1 = $signed(trunc_ln4_reg_988);

assign sext_ln79_1_fu_630_p1 = $signed(trunc_ln5_reg_993);

assign sext_ln79_2_fu_639_p1 = rz_fu_633_p2;

assign sext_ln95_fu_760_p1 = $signed(trunc_ln6_reg_1025);

assign sub_ln75_fu_534_p2 = (8'd96 - select_ln71_fu_513_p3);

assign sub_ln91_fu_717_p2 = (p_shl_fu_697_p3 - zext_ln91_fu_713_p1);

assign tmp_1_fu_653_p3 = sext_ln79_2_fu_639_p1[32'd24];

assign tmp_2_fu_705_p3 = {{vz_fu_691_p3}, {6'd0}};

assign tobool_fu_293_p2 = ((mirror_u != 32'd0) ? 1'b1 : 1'b0);

assign trunc_ln50_fu_469_p1 = grp_fu_464_p2[9:0];

assign trunc_ln78_fu_626_p1 = rx_fu_620_p2[7:0];

assign trunc_ln79_fu_643_p1 = rz_fu_633_p2[7:0];

assign u_1_fu_540_p3 = ((tobool_reg_866[0:0] == 1'b1) ? sub_ln75_fu_534_p2 : u_fu_528_p2);

assign u_fu_528_p2 = ($signed(select_ln71_fu_513_p3) + $signed(8'd160));

assign vx_fu_685_p3 = ((inside_reg_1008[0:0] == 1'b1) ? trunc_ln78_reg_998 : 8'd0);

assign vz_fu_691_p3 = ((inside_reg_1008[0:0] == 1'b1) ? trunc_ln79_reg_1003 : 8'd0);

assign xor_ln46_fu_364_p2 = (icmp_ln71_fu_352_p2 ^ 1'd1);

assign xor_ln82_fu_661_p2 = (tmp_1_fu_653_p3 ^ 1'd1);

assign zext_ln18_cast_fu_285_p1 = zext_ln18;

assign zext_ln50_fu_451_p1 = select_ln46_1_reg_885;

assign zext_ln53_fu_492_p1 = angle_1_reg_910;

assign zext_ln91_1_fu_723_p1 = vx_fu_685_p3;

assign zext_ln91_fu_713_p1 = tmp_2_fu_705_p3;

assign zext_ln95_1_fu_742_p1 = mul_ln95_reg_1020;

always @ (posedge ap_clk) begin
    zext_ln18_cast_reg_856[31] <= 1'b0;
end

endmodule //pov_eta_wr_pov_eta_wr_Pipeline_SLICES_COLUMNS_COPY_COLUMN
