"""Convert any image → 48×12 panel_image_data.c for LED panel.

Workflow:
  1. Load source (PNG/JPG path, OR build-in test patterns 'face' / 'heart' / 'cat')
  2. Resize to 48×12 with Lanczos + contrast boost
  3. Threshold each channel > 128 (1-bit per RGB)
  4. Emit C file with strong panel_image[] definition (overrides led_panel.c weak)

Run:
  python image_to_panel.py [src_path|test_name] [out.c]
"""
import sys, os
from PIL import Image, ImageDraw, ImageEnhance

W, H = 48, 12
SRC = sys.argv[1] if len(sys.argv) > 1 else "face"
OUT = sys.argv[2] if len(sys.argv) > 2 else \
      r"D:\workspace\zynq_pov\02_hello_zynq\vitis_ws\hello_world\src\panel_image_data.c"

def make_face():
    """Anime-style face on 48×12: cyan hair top, skin-tone face, big eyes, smile."""
    img = Image.new("RGB", (W, H), "black")
    d = ImageDraw.Draw(img)
    # hair (top 3 rows, cyan/purple)
    d.rectangle([8, 0, 39, 3], fill=(80, 0, 180))
    # face oval (skin tone yellow-orange)
    d.rectangle([12, 3, 35, 10], fill=(255, 220, 150))
    # left eye (white sclera + black pupil)
    d.rectangle([15, 5, 20, 7], fill=(255, 255, 255))
    d.point([(17, 6)], fill=(0, 0, 0))
    d.point([(18, 6)], fill=(0, 0, 0))
    # right eye
    d.rectangle([27, 5, 32, 7], fill=(255, 255, 255))
    d.point([(29, 6)], fill=(0, 0, 0))
    d.point([(30, 6)], fill=(0, 0, 0))
    # smile (red arc)
    d.line([(20, 9), (27, 9)], fill=(255, 50, 50))
    d.point([(19, 8)], fill=(255, 50, 50))
    d.point([(28, 8)], fill=(255, 50, 50))
    # cheek blush
    d.point([(14, 8)], fill=(255, 100, 100))
    d.point([(33, 8)], fill=(255, 100, 100))
    return img

def make_heart():
    img = Image.new("RGB", (W, H), "black")
    d = ImageDraw.Draw(img)
    # ascii-heart-ish, all red
    pat = [
        "                                                ",
        "        ##  ##         ##  ##                  ",
        "      ######  ######   ######  ######          ",
        "      ##############   ##############          ",
        "      ##############   ##############          ",
        "        ##########       ##########            ",
        "          ######           ######              ",
        "            ##               ##                ",
        "                                                ",
        "                                                ",
        "                                                ",
        "                                                ",
    ]
    for y, row in enumerate(pat[:H]):
        for x, c in enumerate(row[:W]):
            if c == '#':
                d.point([(x, y)], fill=(255, 30, 30))
    return img

def make_cat():
    img = Image.new("RGB", (W, H), "black")
    d = ImageDraw.Draw(img)
    # orange cat head, green eyes
    # ears
    d.polygon([(14, 0), (18, 3), (14, 3)], fill=(255, 140, 0))
    d.polygon([(33, 0), (29, 3), (33, 3)], fill=(255, 140, 0))
    # face
    d.rectangle([14, 3, 33, 10], fill=(255, 140, 0))
    # eyes (green)
    d.rectangle([17, 5, 19, 7], fill=(0, 255, 0))
    d.rectangle([28, 5, 30, 7], fill=(0, 255, 0))
    # nose (pink)
    d.point([(23, 8)], fill=(255, 100, 200))
    d.point([(24, 8)], fill=(255, 100, 200))
    # whiskers
    d.line([(14, 9), (10, 8)], fill=(255, 255, 255))
    d.line([(33, 9), (37, 8)], fill=(255, 255, 255))
    return img

TEST_PATTERNS = {"face": make_face, "heart": make_heart, "cat": make_cat}

# --- load image ---
if SRC in TEST_PATTERNS:
    img = TEST_PATTERNS[SRC]()
    src_label = f"test:{SRC}"
elif os.path.isfile(SRC):
    img = Image.open(SRC).convert("RGB")
    # Boost contrast/saturation since 1-bit threshold is harsh
    img = ImageEnhance.Contrast(img).enhance(1.4)
    img = ImageEnhance.Color(img).enhance(1.6)
    img = img.resize((W, H), Image.LANCZOS)
    src_label = os.path.basename(SRC)
else:
    print(f"ERROR: '{SRC}' not a file and not in {list(TEST_PATTERNS)}")
    sys.exit(1)

print(f"source: {src_label}, {W}×{H}")

# --- emit C file ---
pixels = img.load()
with open(OUT, "w") as f:
    f.write(f"/* auto-generated by image_to_panel.py from {src_label}. */\n")
    f.write("#include \"xil_types.h\"\n\n")
    f.write(f"const u8 panel_image[{H}][{W}][3] = {{\n")
    for y in range(H):
        f.write("    {")
        for x in range(W):
            r, g, b = pixels[x, y][:3]
            f.write(f"{{{r:3d},{g:3d},{b:3d}}}")
            if x < W - 1: f.write(",")
        f.write(" },\n")
    f.write("};\n")
print(f"wrote {OUT}")

# Also print ascii preview for sanity (1-char per pixel, R/G/B/W/K)
print("\npreview (1 char/pixel: R=red G=green B=blue Y=yellow C=cyan M=mag W=white K=black .=dark):")
for y in range(H):
    row = ""
    for x in range(W):
        r, g, b = pixels[x, y][:3]
        on_r, on_g, on_b = r > 128, g > 128, b > 128
        bits = (on_r << 2) | (on_g << 1) | on_b
        ch = ".KBGCRMYW"[bits if bits < 9 else 8]
        # Color mapping: 0=K 1=B 2=G 3=C 4=R 5=M 6=Y 7=W
        ch = "K B G C R M Y W".split()[bits]
        if bits == 0: ch = "."
        row += ch
    print(f"  {row}")
