#!/usr/bin/env python3
"""gen_voxel.py -- random RGB565 voxel grid (192x192x216, 15,925,248 B) + host-side expectations.

Writes (default into eta_test/build_common/):
  voxel.bin            what xsdb 'dow -data' puts at VOX_BASE (content is irrelevant to the IP -- it reads
                       unconditionally, see pov_slice_v2.cpp -- but random data lets us PROVE the data path)
  voxel_expect.tcl     expected words + expected XOR checksums, sourced by tools/run_eta.tcl:
                         EXPECT(head)        first 4 x 32-bit words of the file          (mrd VOX_BASE 4)
                         EXPECT(seq_off)     byte offset of slice 0 at angle 0 (= 96*192*432 = 7,962,624)
                         EXPECT(seq_head)    4 x 32-bit words at seq_off                (mrd VOX_BASE+seq_off 4)
                         EXPECT(xor,P,N)     64-bit XOR the rd gauge must return for phase=P, n_slots=N,
                                             axis_off=0, mirror=0 -- same address algorithm as pov_slice_v2.cpp
The reference below is a literal transcription of pov_slice_v2.cpp's address math (u -> rx,rz -> clamp -> src).
Only WSL numpy is needed (no pip packages).
"""
import argparse, os, re, sys
import numpy as np

here = os.path.dirname(os.path.abspath(__file__))
root = os.path.normpath(os.path.join(here, '..'))
lut_h = os.path.join(root, '..', 'hls_proj', 'pov_slice_v2_lut_603.h')

W, H, NA = 192, 216, 603            # PV2_PANEL_W / PV2_PANEL_H / PV2_LUT_N  (target config)
XZ, CX, HALF = W, W // 2, W // 2
COL_BEATS = H // 4                  # 54 x 64-bit words per column
SLOT_BYTES = W * H * 2              # 82,944

def load_lut():
    txt = open(lut_h, encoding='utf-8').read()
    def arr(name):
        m = re.search(name + r'\[603\]\s*=\s*\{([^}]*)\}', txt)
        vals = [int(v) for v in re.findall(r'-?\d+', m.group(1))]
        assert len(vals) == 603, (name, len(vals))
        return np.array(vals, dtype=np.int64)
    return arr('PV2_COS8'), arr('PV2_SIN8')

def column_srcs(phase, n_slots, axis_off_q8, mirror_u, cos8, sin8):
    """word index (uint64 units) of the first beat of every column, in the order the IP reads them"""
    srcs = []
    for s in range(n_slots):
        angle = (phase + s) % NA
        cs, sn = int(cos8[angle]), int(sin8[angle])
        off_x = -((axis_off_q8 * sn) >> 8)
        off_z = ((axis_off_q8 * cs) >> 8)
        px = np.arange(W)
        u = px - CX
        if mirror_u:
            u = -u
        rx = ((u * cs + off_x + 128) >> 8) + HALF
        rz = ((u * sn + off_z + 128) >> 8) + HALF
        inside = (rx >= 0) & (rx < XZ) & (rz >= 0) & (rz < XZ)
        vx = np.where(inside, rx, 0)
        vz = np.where(inside, rz, 0)
        srcs.append((vz * XZ + vx) * COL_BEATS)
    return np.concatenate(srcs) if srcs else np.zeros(0, dtype=np.int64)

def xor64(words, srcs):
    acc = np.uint64(0)
    for base in srcs:
        acc ^= np.bitwise_xor.reduce(words[base:base + COL_BEATS])
    return int(acc)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', default=os.path.join(root, 'build_common'))
    ap.add_argument('--seed', type=int, default=20260903)
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)

    rng = np.random.default_rng(args.seed)
    vox = rng.integers(0, 1 << 16, size=XZ * XZ * H, dtype=np.uint16)     # 192*192*216 RGB565
    raw = vox.astype('<u2').tobytes()
    assert len(raw) == 15_925_248
    fn = os.path.join(args.out, 'voxel.bin')
    open(fn, 'wb').write(raw)
    words64 = np.frombuffer(raw, dtype='<u8')
    words32 = np.frombuffer(raw, dtype='<u4')

    cos8, sin8 = load_lut()
    seq_off = (HALF * XZ) * COL_BEATS * 8
    # sanity: slice 0 at angle 0 must be one contiguous 82,944-byte run starting at seq_off
    s0 = column_srcs(0, 1, 0, 0, cos8, sin8)
    assert s0[0] * 8 == seq_off and np.all(np.diff(s0) == COL_BEATS), "angle-0 slice is not contiguous?!"

    lines = ['# generated by gen_voxel.py -- do not edit',
             f'set EXPECT(bytes) {len(raw)}',
             f'set EXPECT(file) {{{fn}}}',
             'set EXPECT(head) {' + ' '.join(f'0x{int(w):08X}' for w in words32[:4]) + '}',
             f'set EXPECT(seq_off) {seq_off}',
             'set EXPECT(seq_head) {' + ' '.join(f'0x{int(w):08X}' for w in words32[seq_off // 4: seq_off // 4 + 4]) + '}',
             f'set EXPECT(slot_bytes) {SLOT_BYTES}']
    for phase, n in [(0, 1), (151, 1), (0, 603), (151, 603)]:
        x = xor64(words64, column_srcs(phase, n, 0, 0, cos8, sin8))
        lines.append(f'set EXPECT(xor,{phase},{n}) 0x{x:016X}')
        print(f'xor phase={phase:3d} n={n:3d} = 0x{x:016X}')
    tcl = os.path.join(args.out, 'voxel_expect.tcl')
    open(tcl, 'w').write('\n'.join(lines) + '\n')
    print('wrote', fn, f'({len(raw)} B)')
    print('wrote', tcl)
    print('strided check: phase=151 column stride =', (np.diff(column_srcs(151, 1, 0, 0, cos8, sin8)) * 8)[:3], 'B')

if __name__ == '__main__':
    main()
